/* tslint:disable */
/* eslint-disable */
/**
 * Badminton Court Management System API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AttendanceRequest
 */
export interface AttendanceRequest {
    /**
     * 
     * @type {number}
     * @memberof AttendanceRequest
     */
    id?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AttendanceRequest
     */
    staffId?: number;
    /**
     * 
     * @type {number}
     * @memberof AttendanceRequest
     */
    shiftId?: number;
    /**
     * 
     * @type {Date}
     * @memberof AttendanceRequest
     */
    date?: Date;
    /**
     * 
     * @type {string}
     * @memberof AttendanceRequest
     */
    checkInTime?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AttendanceRequest
     */
    checkOutTime?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AttendanceRequest
     */
    notes?: string | null;
}

/**
 * Check if a given object implements the AttendanceRequest interface.
 */
export function instanceOfAttendanceRequest(value: object): value is AttendanceRequest {
    return true;
}

export function AttendanceRequestFromJSON(json: any): AttendanceRequest {
    return AttendanceRequestFromJSONTyped(json, false);
}

export function AttendanceRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AttendanceRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'staffId': json['staffId'] == null ? undefined : json['staffId'],
        'shiftId': json['shiftId'] == null ? undefined : json['shiftId'],
        'date': json['date'] == null ? undefined : (new Date(json['date'])),
        'checkInTime': json['checkInTime'] == null ? undefined : json['checkInTime'],
        'checkOutTime': json['checkOutTime'] == null ? undefined : json['checkOutTime'],
        'notes': json['notes'] == null ? undefined : json['notes'],
    };
}

export function AttendanceRequestToJSON(json: any): AttendanceRequest {
    return AttendanceRequestToJSONTyped(json, false);
}

export function AttendanceRequestToJSONTyped(value?: AttendanceRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'staffId': value['staffId'],
        'shiftId': value['shiftId'],
        'date': value['date'] == null ? undefined : ((value['date']).toISOString()),
        'checkInTime': value['checkInTime'],
        'checkOutTime': value['checkOutTime'],
        'notes': value['notes'],
    };
}

