/* tslint:disable */
/* eslint-disable */
/**
 * Badminton Court Management System API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StaffResponse } from './StaffResponse';
import {
    StaffResponseFromJSON,
    StaffResponseFromJSONTyped,
    StaffResponseToJSON,
    StaffResponseToJSONTyped,
} from './StaffResponse';

/**
 * 
 * @export
 * @interface AttendanceResponse
 */
export interface AttendanceResponse {
    /**
     * 
     * @type {number}
     * @memberof AttendanceResponse
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof AttendanceResponse
     */
    staffId?: number;
    /**
     * 
     * @type {StaffResponse}
     * @memberof AttendanceResponse
     */
    staff?: StaffResponse;
    /**
     * 
     * @type {Date}
     * @memberof AttendanceResponse
     */
    date?: Date;
    /**
     * 
     * @type {string}
     * @memberof AttendanceResponse
     */
    checkInTime?: string;
    /**
     * 
     * @type {string}
     * @memberof AttendanceResponse
     */
    checkOutTime?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AttendanceResponse
     */
    notes?: string | null;
}

/**
 * Check if a given object implements the AttendanceResponse interface.
 */
export function instanceOfAttendanceResponse(value: object): value is AttendanceResponse {
    return true;
}

export function AttendanceResponseFromJSON(json: any): AttendanceResponse {
    return AttendanceResponseFromJSONTyped(json, false);
}

export function AttendanceResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AttendanceResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'staffId': json['staffId'] == null ? undefined : json['staffId'],
        'staff': json['staff'] == null ? undefined : StaffResponseFromJSON(json['staff']),
        'date': json['date'] == null ? undefined : (new Date(json['date'])),
        'checkInTime': json['checkInTime'] == null ? undefined : json['checkInTime'],
        'checkOutTime': json['checkOutTime'] == null ? undefined : json['checkOutTime'],
        'notes': json['notes'] == null ? undefined : json['notes'],
    };
}

export function AttendanceResponseToJSON(json: any): AttendanceResponse {
    return AttendanceResponseToJSONTyped(json, false);
}

export function AttendanceResponseToJSONTyped(value?: AttendanceResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'staffId': value['staffId'],
        'staff': StaffResponseToJSON(value['staff']),
        'date': value['date'] == null ? undefined : ((value['date']).toISOString()),
        'checkInTime': value['checkInTime'],
        'checkOutTime': value['checkOutTime'],
        'notes': value['notes'],
    };
}

