/* tslint:disable */
/* eslint-disable */
/**
 * Badminton Court Management System API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Blog
 */
export interface Blog {
    /**
     * 
     * @type {Date}
     * @memberof Blog
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Blog
     */
    updatedAt?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof Blog
     */
    createdBy?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Blog
     */
    updatedBy?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Blog
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof Blog
     */
    title: string | null;
    /**
     * 
     * @type {string}
     * @memberof Blog
     */
    content: string | null;
    /**
     * 
     * @type {string}
     * @memberof Blog
     */
    imageUrl: string | null;
    /**
     * 
     * @type {string}
     * @memberof Blog
     */
    status: string | null;
}

/**
 * Check if a given object implements the Blog interface.
 */
export function instanceOfBlog(value: object): value is Blog {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('imageUrl' in value) || value['imageUrl'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function BlogFromJSON(json: any): Blog {
    return BlogFromJSONTyped(json, false);
}

export function BlogFromJSONTyped(json: any, ignoreDiscriminator: boolean): Blog {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
        'createdBy': json['createdBy'] == null ? undefined : json['createdBy'],
        'updatedBy': json['updatedBy'] == null ? undefined : json['updatedBy'],
        'id': json['id'] == null ? undefined : json['id'],
        'title': json['title'],
        'content': json['content'],
        'imageUrl': json['imageUrl'],
        'status': json['status'],
    };
}

export function BlogToJSON(json: any): Blog {
    return BlogToJSONTyped(json, false);
}

export function BlogToJSONTyped(value?: Blog | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'updatedAt': value['updatedAt'] === null ? null : ((value['updatedAt'] as any)?.toISOString()),
        'createdBy': value['createdBy'],
        'updatedBy': value['updatedBy'],
        'id': value['id'],
        'title': value['title'],
        'content': value['content'],
        'imageUrl': value['imageUrl'],
        'status': value['status'],
    };
}

