/* tslint:disable */
/* eslint-disable */
/**
 * Badminton Court Management System API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WaitHandle } from './WaitHandle';
import {
    WaitHandleFromJSON,
    WaitHandleFromJSONTyped,
    WaitHandleToJSON,
    WaitHandleToJSONTyped,
} from './WaitHandle';

/**
 * 
 * @export
 * @interface CancellationToken
 */
export interface CancellationToken {
    /**
     * 
     * @type {boolean}
     * @memberof CancellationToken
     */
    readonly isCancellationRequested?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof CancellationToken
     */
    readonly canBeCanceled?: boolean;
    /**
     * 
     * @type {WaitHandle}
     * @memberof CancellationToken
     */
    waitHandle?: WaitHandle;
}

/**
 * Check if a given object implements the CancellationToken interface.
 */
export function instanceOfCancellationToken(value: object): value is CancellationToken {
    return true;
}

export function CancellationTokenFromJSON(json: any): CancellationToken {
    return CancellationTokenFromJSONTyped(json, false);
}

export function CancellationTokenFromJSONTyped(json: any, ignoreDiscriminator: boolean): CancellationToken {
    if (json == null) {
        return json;
    }
    return {
        
        'isCancellationRequested': json['isCancellationRequested'] == null ? undefined : json['isCancellationRequested'],
        'canBeCanceled': json['canBeCanceled'] == null ? undefined : json['canBeCanceled'],
        'waitHandle': json['waitHandle'] == null ? undefined : WaitHandleFromJSON(json['waitHandle']),
    };
}

export function CancellationTokenToJSON(json: any): CancellationToken {
    return CancellationTokenToJSONTyped(json, false);
}

export function CancellationTokenToJSONTyped(value?: Omit<CancellationToken, 'isCancellationRequested'|'canBeCanceled'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'waitHandle': WaitHandleToJSON(value['waitHandle']),
    };
}

