/* tslint:disable */
/* eslint-disable */
/**
 * Badminton Court Management System API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CheckoutResponse
 */
export interface CheckoutResponse {
    /**
     * 
     * @type {string}
     * @memberof CheckoutResponse
     */
    orderId?: string;
    /**
     * 
     * @type {string}
     * @memberof CheckoutResponse
     */
    orderCode?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CheckoutResponse
     */
    bookingId?: string;
    /**
     * 
     * @type {string}
     * @memberof CheckoutResponse
     */
    bookingCourtOccurrenceId?: string;
    /**
     * 
     * @type {number}
     * @memberof CheckoutResponse
     */
    customerId?: number;
    /**
     * 
     * @type {string}
     * @memberof CheckoutResponse
     */
    customerName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CheckoutResponse
     */
    courtName?: string | null;
    /**
     * 
     * @type {number}
     * @memberof CheckoutResponse
     */
    courtTotalAmount?: number;
    /**
     * 
     * @type {number}
     * @memberof CheckoutResponse
     */
    courtPaidAmount?: number;
    /**
     * 
     * @type {number}
     * @memberof CheckoutResponse
     */
    courtRemainingAmount?: number;
    /**
     * 
     * @type {number}
     * @memberof CheckoutResponse
     */
    itemsSubtotal?: number;
    /**
     * 
     * @type {number}
     * @memberof CheckoutResponse
     */
    servicesSubtotal?: number;
    /**
     * 
     * @type {number}
     * @memberof CheckoutResponse
     */
    lateFeePercentage?: number;
    /**
     * 
     * @type {number}
     * @memberof CheckoutResponse
     */
    lateFeeAmount?: number;
    /**
     * 
     * @type {number}
     * @memberof CheckoutResponse
     */
    overdueMinutes?: number;
    /**
     * 
     * @type {string}
     * @memberof CheckoutResponse
     */
    overdueDisplay?: string | null;
    /**
     * 
     * @type {number}
     * @memberof CheckoutResponse
     */
    voucherId?: number | null;
    /**
     * 
     * @type {number}
     * @memberof CheckoutResponse
     */
    discountAmount?: number;
    /**
     * 
     * @type {number}
     * @memberof CheckoutResponse
     */
    totalAmount?: number;
    /**
     * 
     * @type {string}
     * @memberof CheckoutResponse
     */
    paymentId?: string | null;
    /**
     * 
     * @type {number}
     * @memberof CheckoutResponse
     */
    paymentAmount?: number;
    /**
     * 
     * @type {string}
     * @memberof CheckoutResponse
     */
    paymentMethod?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CheckoutResponse
     */
    qrUrl?: string | null;
    /**
     * 
     * @type {number}
     * @memberof CheckoutResponse
     */
    holdMinutes?: number;
    /**
     * 
     * @type {Date}
     * @memberof CheckoutResponse
     */
    expiresAtUtc?: Date;
    /**
     * 
     * @type {Date}
     * @memberof CheckoutResponse
     */
    createdAt?: Date;
}

/**
 * Check if a given object implements the CheckoutResponse interface.
 */
export function instanceOfCheckoutResponse(value: object): value is CheckoutResponse {
    return true;
}

export function CheckoutResponseFromJSON(json: any): CheckoutResponse {
    return CheckoutResponseFromJSONTyped(json, false);
}

export function CheckoutResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CheckoutResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'orderId': json['orderId'] == null ? undefined : json['orderId'],
        'orderCode': json['orderCode'] == null ? undefined : json['orderCode'],
        'bookingId': json['bookingId'] == null ? undefined : json['bookingId'],
        'bookingCourtOccurrenceId': json['bookingCourtOccurrenceId'] == null ? undefined : json['bookingCourtOccurrenceId'],
        'customerId': json['customerId'] == null ? undefined : json['customerId'],
        'customerName': json['customerName'] == null ? undefined : json['customerName'],
        'courtName': json['courtName'] == null ? undefined : json['courtName'],
        'courtTotalAmount': json['courtTotalAmount'] == null ? undefined : json['courtTotalAmount'],
        'courtPaidAmount': json['courtPaidAmount'] == null ? undefined : json['courtPaidAmount'],
        'courtRemainingAmount': json['courtRemainingAmount'] == null ? undefined : json['courtRemainingAmount'],
        'itemsSubtotal': json['itemsSubtotal'] == null ? undefined : json['itemsSubtotal'],
        'servicesSubtotal': json['servicesSubtotal'] == null ? undefined : json['servicesSubtotal'],
        'lateFeePercentage': json['lateFeePercentage'] == null ? undefined : json['lateFeePercentage'],
        'lateFeeAmount': json['lateFeeAmount'] == null ? undefined : json['lateFeeAmount'],
        'overdueMinutes': json['overdueMinutes'] == null ? undefined : json['overdueMinutes'],
        'overdueDisplay': json['overdueDisplay'] == null ? undefined : json['overdueDisplay'],
        'voucherId': json['voucherId'] == null ? undefined : json['voucherId'],
        'discountAmount': json['discountAmount'] == null ? undefined : json['discountAmount'],
        'totalAmount': json['totalAmount'] == null ? undefined : json['totalAmount'],
        'paymentId': json['paymentId'] == null ? undefined : json['paymentId'],
        'paymentAmount': json['paymentAmount'] == null ? undefined : json['paymentAmount'],
        'paymentMethod': json['paymentMethod'] == null ? undefined : json['paymentMethod'],
        'qrUrl': json['qrUrl'] == null ? undefined : json['qrUrl'],
        'holdMinutes': json['holdMinutes'] == null ? undefined : json['holdMinutes'],
        'expiresAtUtc': json['expiresAtUtc'] == null ? undefined : (new Date(json['expiresAtUtc'])),
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
    };
}

export function CheckoutResponseToJSON(json: any): CheckoutResponse {
    return CheckoutResponseToJSONTyped(json, false);
}

export function CheckoutResponseToJSONTyped(value?: CheckoutResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'orderId': value['orderId'],
        'orderCode': value['orderCode'],
        'bookingId': value['bookingId'],
        'bookingCourtOccurrenceId': value['bookingCourtOccurrenceId'],
        'customerId': value['customerId'],
        'customerName': value['customerName'],
        'courtName': value['courtName'],
        'courtTotalAmount': value['courtTotalAmount'],
        'courtPaidAmount': value['courtPaidAmount'],
        'courtRemainingAmount': value['courtRemainingAmount'],
        'itemsSubtotal': value['itemsSubtotal'],
        'servicesSubtotal': value['servicesSubtotal'],
        'lateFeePercentage': value['lateFeePercentage'],
        'lateFeeAmount': value['lateFeeAmount'],
        'overdueMinutes': value['overdueMinutes'],
        'overdueDisplay': value['overdueDisplay'],
        'voucherId': value['voucherId'],
        'discountAmount': value['discountAmount'],
        'totalAmount': value['totalAmount'],
        'paymentId': value['paymentId'],
        'paymentAmount': value['paymentAmount'],
        'paymentMethod': value['paymentMethod'],
        'qrUrl': value['qrUrl'],
        'holdMinutes': value['holdMinutes'],
        'expiresAtUtc': value['expiresAtUtc'] == null ? undefined : ((value['expiresAtUtc']).toISOString()),
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
    };
}

