/* tslint:disable */
/* eslint-disable */
/**
 * Badminton Court Management System API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CheckOutBookingCourtRequest
 */
export interface CheckOutBookingCourtRequest {
    /**
     * 
     * @type {string}
     * @memberof CheckOutBookingCourtRequest
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof CheckOutBookingCourtRequest
     */
    note?: string | null;
}

/**
 * Check if a given object implements the CheckOutBookingCourtRequest interface.
 */
export function instanceOfCheckOutBookingCourtRequest(value: object): value is CheckOutBookingCourtRequest {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function CheckOutBookingCourtRequestFromJSON(json: any): CheckOutBookingCourtRequest {
    return CheckOutBookingCourtRequestFromJSONTyped(json, false);
}

export function CheckOutBookingCourtRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CheckOutBookingCourtRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'note': json['note'] == null ? undefined : json['note'],
    };
}

export function CheckOutBookingCourtRequestToJSON(json: any): CheckOutBookingCourtRequest {
    return CheckOutBookingCourtRequestToJSONTyped(json, false);
}

export function CheckOutBookingCourtRequestToJSONTyped(value?: CheckOutBookingCourtRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'note': value['note'],
    };
}

