/* tslint:disable */
/* eslint-disable */
/**
 * Badminton Court Management System API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CourtPricingRuleTemplateDto } from './CourtPricingRuleTemplateDto';
import {
    CourtPricingRuleTemplateDtoFromJSON,
    CourtPricingRuleTemplateDtoFromJSONTyped,
    CourtPricingRuleTemplateDtoToJSON,
    CourtPricingRuleTemplateDtoToJSONTyped,
} from './CourtPricingRuleTemplateDto';

/**
 * 
 * @export
 * @interface CourtPricingRuleTemplateDtoListApiResponse
 */
export interface CourtPricingRuleTemplateDtoListApiResponse {
    /**
     * 
     * @type {boolean}
     * @memberof CourtPricingRuleTemplateDtoListApiResponse
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof CourtPricingRuleTemplateDtoListApiResponse
     */
    message?: string | null;
    /**
     * 
     * @type {Array<CourtPricingRuleTemplateDto>}
     * @memberof CourtPricingRuleTemplateDtoListApiResponse
     */
    data?: Array<CourtPricingRuleTemplateDto> | null;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof CourtPricingRuleTemplateDtoListApiResponse
     */
    errors?: { [key: string]: string; } | null;
}

/**
 * Check if a given object implements the CourtPricingRuleTemplateDtoListApiResponse interface.
 */
export function instanceOfCourtPricingRuleTemplateDtoListApiResponse(value: object): value is CourtPricingRuleTemplateDtoListApiResponse {
    return true;
}

export function CourtPricingRuleTemplateDtoListApiResponseFromJSON(json: any): CourtPricingRuleTemplateDtoListApiResponse {
    return CourtPricingRuleTemplateDtoListApiResponseFromJSONTyped(json, false);
}

export function CourtPricingRuleTemplateDtoListApiResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CourtPricingRuleTemplateDtoListApiResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(CourtPricingRuleTemplateDtoFromJSON)),
        'errors': json['errors'] == null ? undefined : json['errors'],
    };
}

export function CourtPricingRuleTemplateDtoListApiResponseToJSON(json: any): CourtPricingRuleTemplateDtoListApiResponse {
    return CourtPricingRuleTemplateDtoListApiResponseToJSONTyped(json, false);
}

export function CourtPricingRuleTemplateDtoListApiResponseToJSONTyped(value?: CourtPricingRuleTemplateDtoListApiResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'message': value['message'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(CourtPricingRuleTemplateDtoToJSON)),
        'errors': value['errors'],
    };
}

