/* tslint:disable */
/* eslint-disable */
/**
 * Badminton Court Management System API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreatePaymentForMembershipRequest
 */
export interface CreatePaymentForMembershipRequest {
    /**
     * 
     * @type {number}
     * @memberof CreatePaymentForMembershipRequest
     */
    userMembershipId: number;
    /**
     * 
     * @type {number}
     * @memberof CreatePaymentForMembershipRequest
     */
    customerId: number;
    /**
     * 
     * @type {number}
     * @memberof CreatePaymentForMembershipRequest
     */
    amount: number;
    /**
     * 
     * @type {string}
     * @memberof CreatePaymentForMembershipRequest
     */
    paymentMethod?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreatePaymentForMembershipRequest
     */
    note?: string | null;
}

/**
 * Check if a given object implements the CreatePaymentForMembershipRequest interface.
 */
export function instanceOfCreatePaymentForMembershipRequest(value: object): value is CreatePaymentForMembershipRequest {
    if (!('userMembershipId' in value) || value['userMembershipId'] === undefined) return false;
    if (!('customerId' in value) || value['customerId'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    return true;
}

export function CreatePaymentForMembershipRequestFromJSON(json: any): CreatePaymentForMembershipRequest {
    return CreatePaymentForMembershipRequestFromJSONTyped(json, false);
}

export function CreatePaymentForMembershipRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePaymentForMembershipRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'userMembershipId': json['userMembershipId'],
        'customerId': json['customerId'],
        'amount': json['amount'],
        'paymentMethod': json['paymentMethod'] == null ? undefined : json['paymentMethod'],
        'note': json['note'] == null ? undefined : json['note'],
    };
}

export function CreatePaymentForMembershipRequestToJSON(json: any): CreatePaymentForMembershipRequest {
    return CreatePaymentForMembershipRequestToJSONTyped(json, false);
}

export function CreatePaymentForMembershipRequestToJSONTyped(value?: CreatePaymentForMembershipRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userMembershipId': value['userMembershipId'],
        'customerId': value['customerId'],
        'amount': value['amount'],
        'paymentMethod': value['paymentMethod'],
        'note': value['note'],
    };
}

