/* tslint:disable */
/* eslint-disable */
/**
 * Badminton Court Management System API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateServicePricingRuleRequest
 */
export interface CreateServicePricingRuleRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateServicePricingRuleRequest
     */
    serviceId: string;
    /**
     * 
     * @type {number}
     * @memberof CreateServicePricingRuleRequest
     */
    pricePerHour: number;
}

/**
 * Check if a given object implements the CreateServicePricingRuleRequest interface.
 */
export function instanceOfCreateServicePricingRuleRequest(value: object): value is CreateServicePricingRuleRequest {
    if (!('serviceId' in value) || value['serviceId'] === undefined) return false;
    if (!('pricePerHour' in value) || value['pricePerHour'] === undefined) return false;
    return true;
}

export function CreateServicePricingRuleRequestFromJSON(json: any): CreateServicePricingRuleRequest {
    return CreateServicePricingRuleRequestFromJSONTyped(json, false);
}

export function CreateServicePricingRuleRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateServicePricingRuleRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'serviceId': json['serviceId'],
        'pricePerHour': json['pricePerHour'],
    };
}

export function CreateServicePricingRuleRequestToJSON(json: any): CreateServicePricingRuleRequest {
    return CreateServicePricingRuleRequestToJSONTyped(json, false);
}

export function CreateServicePricingRuleRequestToJSONTyped(value?: CreateServicePricingRuleRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'serviceId': value['serviceId'],
        'pricePerHour': value['pricePerHour'],
    };
}

