/* tslint:disable */
/* eslint-disable */
/**
 * Badminton Court Management System API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateReturnGoodsItem } from './CreateReturnGoodsItem';
import {
    CreateReturnGoodsItemFromJSON,
    CreateReturnGoodsItemFromJSONTyped,
    CreateReturnGoodsItemToJSON,
    CreateReturnGoodsItemToJSONTyped,
} from './CreateReturnGoodsItem';

/**
 * 
 * @export
 * @interface CreateReturnGoodsRequest
 */
export interface CreateReturnGoodsRequest {
    /**
     * 
     * @type {Date}
     * @memberof CreateReturnGoodsRequest
     */
    returnTime: Date;
    /**
     * 
     * @type {number}
     * @memberof CreateReturnGoodsRequest
     */
    supplierId: number;
    /**
     * 
     * @type {string}
     * @memberof CreateReturnGoodsRequest
     */
    returnBy?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateReturnGoodsRequest
     */
    note?: string | null;
    /**
     * 
     * @type {number}
     * @memberof CreateReturnGoodsRequest
     */
    discount?: number;
    /**
     * 
     * @type {number}
     * @memberof CreateReturnGoodsRequest
     */
    supplierPaid?: number;
    /**
     * 
     * @type {number}
     * @memberof CreateReturnGoodsRequest
     */
    paymentMethod?: number;
    /**
     * 
     * @type {number}
     * @memberof CreateReturnGoodsRequest
     */
    storeBankAccountId?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof CreateReturnGoodsRequest
     */
    complete?: boolean;
    /**
     * 
     * @type {Array<CreateReturnGoodsItem>}
     * @memberof CreateReturnGoodsRequest
     */
    items: Array<CreateReturnGoodsItem>;
}

/**
 * Check if a given object implements the CreateReturnGoodsRequest interface.
 */
export function instanceOfCreateReturnGoodsRequest(value: object): value is CreateReturnGoodsRequest {
    if (!('returnTime' in value) || value['returnTime'] === undefined) return false;
    if (!('supplierId' in value) || value['supplierId'] === undefined) return false;
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function CreateReturnGoodsRequestFromJSON(json: any): CreateReturnGoodsRequest {
    return CreateReturnGoodsRequestFromJSONTyped(json, false);
}

export function CreateReturnGoodsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateReturnGoodsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'returnTime': (new Date(json['returnTime'])),
        'supplierId': json['supplierId'],
        'returnBy': json['returnBy'] == null ? undefined : json['returnBy'],
        'note': json['note'] == null ? undefined : json['note'],
        'discount': json['discount'] == null ? undefined : json['discount'],
        'supplierPaid': json['supplierPaid'] == null ? undefined : json['supplierPaid'],
        'paymentMethod': json['paymentMethod'] == null ? undefined : json['paymentMethod'],
        'storeBankAccountId': json['storeBankAccountId'] == null ? undefined : json['storeBankAccountId'],
        'complete': json['complete'] == null ? undefined : json['complete'],
        'items': ((json['items'] as Array<any>).map(CreateReturnGoodsItemFromJSON)),
    };
}

export function CreateReturnGoodsRequestToJSON(json: any): CreateReturnGoodsRequest {
    return CreateReturnGoodsRequestToJSONTyped(json, false);
}

export function CreateReturnGoodsRequestToJSONTyped(value?: CreateReturnGoodsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'returnTime': ((value['returnTime']).toISOString()),
        'supplierId': value['supplierId'],
        'returnBy': value['returnBy'],
        'note': value['note'],
        'discount': value['discount'],
        'supplierPaid': value['supplierPaid'],
        'paymentMethod': value['paymentMethod'],
        'storeBankAccountId': value['storeBankAccountId'],
        'complete': value['complete'],
        'items': ((value['items'] as Array<any>).map(CreateReturnGoodsItemToJSON)),
    };
}

