/* tslint:disable */
/* eslint-disable */
/**
 * Badminton Court Management System API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaymentMethod } from './PaymentMethod';
import {
    PaymentMethodFromJSON,
    PaymentMethodFromJSONTyped,
    PaymentMethodToJSON,
    PaymentMethodToJSONTyped,
} from './PaymentMethod';

/**
 * 
 * @export
 * @interface CreateCashflowRequest
 */
export interface CreateCashflowRequest {
    /**
     * 
     * @type {number}
     * @memberof CreateCashflowRequest
     */
    cashflowTypeId: number;
    /**
     * 
     * @type {number}
     * @memberof CreateCashflowRequest
     */
    value: number;
    /**
     * 
     * @type {number}
     * @memberof CreateCashflowRequest
     */
    relatedId?: number | null;
    /**
     * 
     * @type {string}
     * @memberof CreateCashflowRequest
     */
    relatedPerson?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateCashflowRequest
     */
    note?: string | null;
    /**
     * 
     * @type {PaymentMethod}
     * @memberof CreateCashflowRequest
     */
    paymentMethod?: PaymentMethod;
    /**
     * 
     * @type {boolean}
     * @memberof CreateCashflowRequest
     */
    accountInBusinessResults?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof CreateCashflowRequest
     */
    time?: Date | null;
}



/**
 * Check if a given object implements the CreateCashflowRequest interface.
 */
export function instanceOfCreateCashflowRequest(value: object): value is CreateCashflowRequest {
    if (!('cashflowTypeId' in value) || value['cashflowTypeId'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function CreateCashflowRequestFromJSON(json: any): CreateCashflowRequest {
    return CreateCashflowRequestFromJSONTyped(json, false);
}

export function CreateCashflowRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCashflowRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'cashflowTypeId': json['cashflowTypeId'],
        'value': json['value'],
        'relatedId': json['relatedId'] == null ? undefined : json['relatedId'],
        'relatedPerson': json['relatedPerson'] == null ? undefined : json['relatedPerson'],
        'note': json['note'] == null ? undefined : json['note'],
        'paymentMethod': json['paymentMethod'] == null ? undefined : PaymentMethodFromJSON(json['paymentMethod']),
        'accountInBusinessResults': json['accountInBusinessResults'] == null ? undefined : json['accountInBusinessResults'],
        'time': json['time'] == null ? undefined : (new Date(json['time'])),
    };
}

export function CreateCashflowRequestToJSON(json: any): CreateCashflowRequest {
    return CreateCashflowRequestToJSONTyped(json, false);
}

export function CreateCashflowRequestToJSONTyped(value?: CreateCashflowRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cashflowTypeId': value['cashflowTypeId'],
        'value': value['value'],
        'relatedId': value['relatedId'],
        'relatedPerson': value['relatedPerson'],
        'note': value['note'],
        'paymentMethod': PaymentMethodToJSON(value['paymentMethod']),
        'accountInBusinessResults': value['accountInBusinessResults'],
        'time': value['time'] === null ? null : ((value['time'] as any)?.toISOString()),
    };
}

