/* tslint:disable */
/* eslint-disable */
/**
 * Badminton Court Management System API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateInvoiceRequest
 */
export interface CreateInvoiceRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateInvoiceRequest
     */
    bookingId: string;
}

/**
 * Check if a given object implements the CreateInvoiceRequest interface.
 */
export function instanceOfCreateInvoiceRequest(value: object): value is CreateInvoiceRequest {
    if (!('bookingId' in value) || value['bookingId'] === undefined) return false;
    return true;
}

export function CreateInvoiceRequestFromJSON(json: any): CreateInvoiceRequest {
    return CreateInvoiceRequestFromJSONTyped(json, false);
}

export function CreateInvoiceRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateInvoiceRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'bookingId': json['bookingId'],
    };
}

export function CreateInvoiceRequestToJSON(json: any): CreateInvoiceRequest {
    return CreateInvoiceRequestToJSONTyped(json, false);
}

export function CreateInvoiceRequestToJSONTyped(value?: CreateInvoiceRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bookingId': value['bookingId'],
    };
}

