/* tslint:disable */
/* eslint-disable */
/**
 * Badminton Court Management System API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateReturnGoodsItem
 */
export interface CreateReturnGoodsItem {
    /**
     * 
     * @type {number}
     * @memberof CreateReturnGoodsItem
     */
    productId: number;
    /**
     * 
     * @type {number}
     * @memberof CreateReturnGoodsItem
     */
    quantity: number;
    /**
     * 
     * @type {number}
     * @memberof CreateReturnGoodsItem
     */
    importPrice: number;
    /**
     * 
     * @type {number}
     * @memberof CreateReturnGoodsItem
     */
    returnPrice: number;
    /**
     * 
     * @type {number}
     * @memberof CreateReturnGoodsItem
     */
    discount?: number;
    /**
     * 
     * @type {string}
     * @memberof CreateReturnGoodsItem
     */
    note?: string | null;
}

/**
 * Check if a given object implements the CreateReturnGoodsItem interface.
 */
export function instanceOfCreateReturnGoodsItem(value: object): value is CreateReturnGoodsItem {
    if (!('productId' in value) || value['productId'] === undefined) return false;
    if (!('quantity' in value) || value['quantity'] === undefined) return false;
    if (!('importPrice' in value) || value['importPrice'] === undefined) return false;
    if (!('returnPrice' in value) || value['returnPrice'] === undefined) return false;
    return true;
}

export function CreateReturnGoodsItemFromJSON(json: any): CreateReturnGoodsItem {
    return CreateReturnGoodsItemFromJSONTyped(json, false);
}

export function CreateReturnGoodsItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateReturnGoodsItem {
    if (json == null) {
        return json;
    }
    return {
        
        'productId': json['productId'],
        'quantity': json['quantity'],
        'importPrice': json['importPrice'],
        'returnPrice': json['returnPrice'],
        'discount': json['discount'] == null ? undefined : json['discount'],
        'note': json['note'] == null ? undefined : json['note'],
    };
}

export function CreateReturnGoodsItemToJSON(json: any): CreateReturnGoodsItem {
    return CreateReturnGoodsItemToJSONTyped(json, false);
}

export function CreateReturnGoodsItemToJSONTyped(value?: CreateReturnGoodsItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'productId': value['productId'],
        'quantity': value['quantity'],
        'importPrice': value['importPrice'],
        'returnPrice': value['returnPrice'],
        'discount': value['discount'],
        'note': value['note'],
    };
}

