/* tslint:disable */
/* eslint-disable */
/**
 * Badminton Court Management System API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateUserMembershipResponse
 */
export interface CreateUserMembershipResponse {
    /**
     * 
     * @type {number}
     * @memberof CreateUserMembershipResponse
     */
    userMembershipId?: number;
    /**
     * 
     * @type {number}
     * @memberof CreateUserMembershipResponse
     */
    customerId?: number;
    /**
     * 
     * @type {number}
     * @memberof CreateUserMembershipResponse
     */
    membershipId?: number;
    /**
     * 
     * @type {string}
     * @memberof CreateUserMembershipResponse
     */
    status?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof CreateUserMembershipResponse
     */
    isActive?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof CreateUserMembershipResponse
     */
    startDate?: Date;
    /**
     * 
     * @type {Date}
     * @memberof CreateUserMembershipResponse
     */
    endDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof CreateUserMembershipResponse
     */
    paymentId?: string | null;
    /**
     * 
     * @type {number}
     * @memberof CreateUserMembershipResponse
     */
    paymentAmount?: number;
    /**
     * 
     * @type {string}
     * @memberof CreateUserMembershipResponse
     */
    paymentMethod?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateUserMembershipResponse
     */
    qrUrl?: string | null;
    /**
     * 
     * @type {number}
     * @memberof CreateUserMembershipResponse
     */
    holdMinutes?: number;
    /**
     * 
     * @type {Date}
     * @memberof CreateUserMembershipResponse
     */
    expiresAtUtc?: Date;
}

/**
 * Check if a given object implements the CreateUserMembershipResponse interface.
 */
export function instanceOfCreateUserMembershipResponse(value: object): value is CreateUserMembershipResponse {
    return true;
}

export function CreateUserMembershipResponseFromJSON(json: any): CreateUserMembershipResponse {
    return CreateUserMembershipResponseFromJSONTyped(json, false);
}

export function CreateUserMembershipResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateUserMembershipResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'userMembershipId': json['userMembershipId'] == null ? undefined : json['userMembershipId'],
        'customerId': json['customerId'] == null ? undefined : json['customerId'],
        'membershipId': json['membershipId'] == null ? undefined : json['membershipId'],
        'status': json['status'] == null ? undefined : json['status'],
        'isActive': json['isActive'] == null ? undefined : json['isActive'],
        'startDate': json['startDate'] == null ? undefined : (new Date(json['startDate'])),
        'endDate': json['endDate'] == null ? undefined : (new Date(json['endDate'])),
        'paymentId': json['paymentId'] == null ? undefined : json['paymentId'],
        'paymentAmount': json['paymentAmount'] == null ? undefined : json['paymentAmount'],
        'paymentMethod': json['paymentMethod'] == null ? undefined : json['paymentMethod'],
        'qrUrl': json['qrUrl'] == null ? undefined : json['qrUrl'],
        'holdMinutes': json['holdMinutes'] == null ? undefined : json['holdMinutes'],
        'expiresAtUtc': json['expiresAtUtc'] == null ? undefined : (new Date(json['expiresAtUtc'])),
    };
}

export function CreateUserMembershipResponseToJSON(json: any): CreateUserMembershipResponse {
    return CreateUserMembershipResponseToJSONTyped(json, false);
}

export function CreateUserMembershipResponseToJSONTyped(value?: CreateUserMembershipResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userMembershipId': value['userMembershipId'],
        'customerId': value['customerId'],
        'membershipId': value['membershipId'],
        'status': value['status'],
        'isActive': value['isActive'],
        'startDate': value['startDate'] == null ? undefined : ((value['startDate']).toISOString()),
        'endDate': value['endDate'] == null ? undefined : ((value['endDate']).toISOString()),
        'paymentId': value['paymentId'],
        'paymentAmount': value['paymentAmount'],
        'paymentMethod': value['paymentMethod'],
        'qrUrl': value['qrUrl'],
        'holdMinutes': value['holdMinutes'],
        'expiresAtUtc': value['expiresAtUtc'] == null ? undefined : ((value['expiresAtUtc']).toISOString()),
    };
}

