/* tslint:disable */
/* eslint-disable */
/**
 * Badminton Court Management System API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateStoreBankAccountRequest
 */
export interface CreateStoreBankAccountRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateStoreBankAccountRequest
     */
    accountNumber: string;
    /**
     * 
     * @type {string}
     * @memberof CreateStoreBankAccountRequest
     */
    accountName: string;
    /**
     * 
     * @type {string}
     * @memberof CreateStoreBankAccountRequest
     */
    bankName: string;
}

/**
 * Check if a given object implements the CreateStoreBankAccountRequest interface.
 */
export function instanceOfCreateStoreBankAccountRequest(value: object): value is CreateStoreBankAccountRequest {
    if (!('accountNumber' in value) || value['accountNumber'] === undefined) return false;
    if (!('accountName' in value) || value['accountName'] === undefined) return false;
    if (!('bankName' in value) || value['bankName'] === undefined) return false;
    return true;
}

export function CreateStoreBankAccountRequestFromJSON(json: any): CreateStoreBankAccountRequest {
    return CreateStoreBankAccountRequestFromJSONTyped(json, false);
}

export function CreateStoreBankAccountRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateStoreBankAccountRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'accountNumber': json['accountNumber'],
        'accountName': json['accountName'],
        'bankName': json['bankName'],
    };
}

export function CreateStoreBankAccountRequestToJSON(json: any): CreateStoreBankAccountRequest {
    return CreateStoreBankAccountRequestToJSONTyped(json, false);
}

export function CreateStoreBankAccountRequestToJSONTyped(value?: CreateStoreBankAccountRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accountNumber': value['accountNumber'],
        'accountName': value['accountName'],
        'bankName': value['bankName'],
    };
}

