/* tslint:disable */
/* eslint-disable */
/**
 * Badminton Court Management System API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateBlogRequest
 */
export interface CreateBlogRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateBlogRequest
     */
    title: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateBlogRequest
     */
    content: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateBlogRequest
     */
    imageUrl: string | null;
}

/**
 * Check if a given object implements the CreateBlogRequest interface.
 */
export function instanceOfCreateBlogRequest(value: object): value is CreateBlogRequest {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('imageUrl' in value) || value['imageUrl'] === undefined) return false;
    return true;
}

export function CreateBlogRequestFromJSON(json: any): CreateBlogRequest {
    return CreateBlogRequestFromJSONTyped(json, false);
}

export function CreateBlogRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateBlogRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'content': json['content'],
        'imageUrl': json['imageUrl'],
    };
}

export function CreateBlogRequestToJSON(json: any): CreateBlogRequest {
    return CreateBlogRequestToJSONTyped(json, false);
}

export function CreateBlogRequestToJSONTyped(value?: CreateBlogRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'content': value['content'],
        'imageUrl': value['imageUrl'],
    };
}

