/* tslint:disable */
/* eslint-disable */
/**
 * Badminton Court Management System API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateCourtRequest
 */
export interface CreateCourtRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateCourtRequest
     */
    name: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateCourtRequest
     */
    imageUrl?: string | null;
    /**
     * 
     * @type {number}
     * @memberof CreateCourtRequest
     */
    price: number;
    /**
     * 
     * @type {number}
     * @memberof CreateCourtRequest
     */
    priceUnitId: number;
    /**
     * 
     * @type {number}
     * @memberof CreateCourtRequest
     */
    courtAreaId: number;
    /**
     * 
     * @type {string}
     * @memberof CreateCourtRequest
     */
    note?: string | null;
}

/**
 * Check if a given object implements the CreateCourtRequest interface.
 */
export function instanceOfCreateCourtRequest(value: object): value is CreateCourtRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('price' in value) || value['price'] === undefined) return false;
    if (!('priceUnitId' in value) || value['priceUnitId'] === undefined) return false;
    if (!('courtAreaId' in value) || value['courtAreaId'] === undefined) return false;
    return true;
}

export function CreateCourtRequestFromJSON(json: any): CreateCourtRequest {
    return CreateCourtRequestFromJSONTyped(json, false);
}

export function CreateCourtRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCourtRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'imageUrl': json['imageUrl'] == null ? undefined : json['imageUrl'],
        'price': json['price'],
        'priceUnitId': json['priceUnitId'],
        'courtAreaId': json['courtAreaId'],
        'note': json['note'] == null ? undefined : json['note'],
    };
}

export function CreateCourtRequestToJSON(json: any): CreateCourtRequest {
    return CreateCourtRequestToJSONTyped(json, false);
}

export function CreateCourtRequestToJSONTyped(value?: CreateCourtRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'imageUrl': value['imageUrl'],
        'price': value['price'],
        'priceUnitId': value['priceUnitId'],
        'courtAreaId': value['courtAreaId'],
        'note': value['note'],
    };
}

