/* tslint:disable */
/* eslint-disable */
/**
 * Badminton Court Management System API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CustomerInfo
 */
export interface CustomerInfo {
    /**
     * 
     * @type {string}
     * @memberof CustomerInfo
     */
    fullName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CustomerInfo
     */
    phoneNumber?: string | null;
}

/**
 * Check if a given object implements the CustomerInfo interface.
 */
export function instanceOfCustomerInfo(value: object): value is CustomerInfo {
    return true;
}

export function CustomerInfoFromJSON(json: any): CustomerInfo {
    return CustomerInfoFromJSONTyped(json, false);
}

export function CustomerInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomerInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'fullName': json['fullName'] == null ? undefined : json['fullName'],
        'phoneNumber': json['phoneNumber'] == null ? undefined : json['phoneNumber'],
    };
}

export function CustomerInfoToJSON(json: any): CustomerInfo {
    return CustomerInfoToJSONTyped(json, false);
}

export function CustomerInfoToJSONTyped(value?: CustomerInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'fullName': value['fullName'],
        'phoneNumber': value['phoneNumber'],
    };
}

