/* tslint:disable */
/* eslint-disable */
/**
 * Badminton Court Management System API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeleteMembershipRequest
 */
export interface DeleteMembershipRequest {
    /**
     * 
     * @type {number}
     * @memberof DeleteMembershipRequest
     */
    id: number;
}

/**
 * Check if a given object implements the DeleteMembershipRequest interface.
 */
export function instanceOfDeleteMembershipRequest(value: object): value is DeleteMembershipRequest {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function DeleteMembershipRequestFromJSON(json: any): DeleteMembershipRequest {
    return DeleteMembershipRequestFromJSONTyped(json, false);
}

export function DeleteMembershipRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteMembershipRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function DeleteMembershipRequestToJSON(json: any): DeleteMembershipRequest {
    return DeleteMembershipRequestToJSONTyped(json, false);
}

export function DeleteMembershipRequestToJSONTyped(value?: DeleteMembershipRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
    };
}

