/* tslint:disable */
/* eslint-disable */
/**
 * Badminton Court Management System API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DepartmentRequest
 */
export interface DepartmentRequest {
    /**
     * 
     * @type {string}
     * @memberof DepartmentRequest
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DepartmentRequest
     */
    description?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof DepartmentRequest
     */
    isActive?: boolean;
}

/**
 * Check if a given object implements the DepartmentRequest interface.
 */
export function instanceOfDepartmentRequest(value: object): value is DepartmentRequest {
    return true;
}

export function DepartmentRequestFromJSON(json: any): DepartmentRequest {
    return DepartmentRequestFromJSONTyped(json, false);
}

export function DepartmentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DepartmentRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'isActive': json['isActive'] == null ? undefined : json['isActive'],
    };
}

export function DepartmentRequestToJSON(json: any): DepartmentRequest {
    return DepartmentRequestToJSONTyped(json, false);
}

export function DepartmentRequestToJSONTyped(value?: DepartmentRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'isActive': value['isActive'],
    };
}

