/* tslint:disable */
/* eslint-disable */
/**
 * Badminton Court Management System API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CourtPricingRuleDto } from './CourtPricingRuleDto';
import {
    CourtPricingRuleDtoFromJSON,
    CourtPricingRuleDtoFromJSONTyped,
    CourtPricingRuleDtoToJSON,
    CourtPricingRuleDtoToJSONTyped,
} from './CourtPricingRuleDto';

/**
 * 
 * @export
 * @interface DetailCourtResponse
 */
export interface DetailCourtResponse {
    /**
     * 
     * @type {string}
     * @memberof DetailCourtResponse
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof DetailCourtResponse
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DetailCourtResponse
     */
    imageUrl?: string | null;
    /**
     * 
     * @type {number}
     * @memberof DetailCourtResponse
     */
    courtAreaId?: number;
    /**
     * 
     * @type {string}
     * @memberof DetailCourtResponse
     */
    courtAreaName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DetailCourtResponse
     */
    note?: string | null;
    /**
     * 
     * @type {Array<CourtPricingRuleDto>}
     * @memberof DetailCourtResponse
     */
    courtPricingRules?: Array<CourtPricingRuleDto> | null;
    /**
     * 
     * @type {string}
     * @memberof DetailCourtResponse
     */
    status?: string | null;
}

/**
 * Check if a given object implements the DetailCourtResponse interface.
 */
export function instanceOfDetailCourtResponse(value: object): value is DetailCourtResponse {
    return true;
}

export function DetailCourtResponseFromJSON(json: any): DetailCourtResponse {
    return DetailCourtResponseFromJSONTyped(json, false);
}

export function DetailCourtResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DetailCourtResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'imageUrl': json['imageUrl'] == null ? undefined : json['imageUrl'],
        'courtAreaId': json['courtAreaId'] == null ? undefined : json['courtAreaId'],
        'courtAreaName': json['courtAreaName'] == null ? undefined : json['courtAreaName'],
        'note': json['note'] == null ? undefined : json['note'],
        'courtPricingRules': json['courtPricingRules'] == null ? undefined : ((json['courtPricingRules'] as Array<any>).map(CourtPricingRuleDtoFromJSON)),
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function DetailCourtResponseToJSON(json: any): DetailCourtResponse {
    return DetailCourtResponseToJSONTyped(json, false);
}

export function DetailCourtResponseToJSONTyped(value?: DetailCourtResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'imageUrl': value['imageUrl'],
        'courtAreaId': value['courtAreaId'],
        'courtAreaName': value['courtAreaName'],
        'note': value['note'],
        'courtPricingRules': value['courtPricingRules'] == null ? undefined : ((value['courtPricingRules'] as Array<any>).map(CourtPricingRuleDtoToJSON)),
        'status': value['status'],
    };
}

