/* tslint:disable */
/* eslint-disable */
/**
 * Badminton Court Management System API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DetailAdministratorRequest
 */
export interface DetailAdministratorRequest {
    /**
     * 
     * @type {string}
     * @memberof DetailAdministratorRequest
     */
    userId: string;
}

/**
 * Check if a given object implements the DetailAdministratorRequest interface.
 */
export function instanceOfDetailAdministratorRequest(value: object): value is DetailAdministratorRequest {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    return true;
}

export function DetailAdministratorRequestFromJSON(json: any): DetailAdministratorRequest {
    return DetailAdministratorRequestFromJSONTyped(json, false);
}

export function DetailAdministratorRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DetailAdministratorRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'],
    };
}

export function DetailAdministratorRequestToJSON(json: any): DetailAdministratorRequest {
    return DetailAdministratorRequestToJSONTyped(json, false);
}

export function DetailAdministratorRequestToJSONTyped(value?: DetailAdministratorRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userId': value['userId'],
    };
}

