/* tslint:disable */
/* eslint-disable */
/**
 * Badminton Court Management System API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DetailBlogResponse
 */
export interface DetailBlogResponse {
    /**
     * 
     * @type {Date}
     * @memberof DetailBlogResponse
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof DetailBlogResponse
     */
    updatedAt?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof DetailBlogResponse
     */
    createdBy?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DetailBlogResponse
     */
    updatedBy?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DetailBlogResponse
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof DetailBlogResponse
     */
    title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DetailBlogResponse
     */
    content?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DetailBlogResponse
     */
    imageUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DetailBlogResponse
     */
    status?: string | null;
}

/**
 * Check if a given object implements the DetailBlogResponse interface.
 */
export function instanceOfDetailBlogResponse(value: object): value is DetailBlogResponse {
    return true;
}

export function DetailBlogResponseFromJSON(json: any): DetailBlogResponse {
    return DetailBlogResponseFromJSONTyped(json, false);
}

export function DetailBlogResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DetailBlogResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
        'createdBy': json['createdBy'] == null ? undefined : json['createdBy'],
        'updatedBy': json['updatedBy'] == null ? undefined : json['updatedBy'],
        'id': json['id'] == null ? undefined : json['id'],
        'title': json['title'] == null ? undefined : json['title'],
        'content': json['content'] == null ? undefined : json['content'],
        'imageUrl': json['imageUrl'] == null ? undefined : json['imageUrl'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function DetailBlogResponseToJSON(json: any): DetailBlogResponse {
    return DetailBlogResponseToJSONTyped(json, false);
}

export function DetailBlogResponseToJSONTyped(value?: DetailBlogResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'updatedAt': value['updatedAt'] === null ? null : ((value['updatedAt'] as any)?.toISOString()),
        'createdBy': value['createdBy'],
        'updatedBy': value['updatedBy'],
        'id': value['id'],
        'title': value['title'],
        'content': value['content'],
        'imageUrl': value['imageUrl'],
        'status': value['status'],
    };
}

