/* tslint:disable */
/* eslint-disable */
/**
 * Badminton Court Management System API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BookingServiceDto } from './BookingServiceDto';
import {
    BookingServiceDtoFromJSON,
    BookingServiceDtoFromJSONTyped,
    BookingServiceDtoToJSON,
    BookingServiceDtoToJSONTyped,
} from './BookingServiceDto';
import type { CustomerDto } from './CustomerDto';
import {
    CustomerDtoFromJSON,
    CustomerDtoFromJSONTyped,
    CustomerDtoToJSON,
    CustomerDtoToJSONTyped,
} from './CustomerDto';
import type { PaymentDto } from './PaymentDto';
import {
    PaymentDtoFromJSON,
    PaymentDtoFromJSONTyped,
    PaymentDtoToJSON,
    PaymentDtoToJSONTyped,
} from './PaymentDto';

/**
 * 
 * @export
 * @interface DetailBookingCourtResponse
 */
export interface DetailBookingCourtResponse {
    /**
     * 
     * @type {string}
     * @memberof DetailBookingCourtResponse
     */
    id?: string;
    /**
     * 
     * @type {number}
     * @memberof DetailBookingCourtResponse
     */
    customerId?: number;
    /**
     * 
     * @type {string}
     * @memberof DetailBookingCourtResponse
     */
    courtId?: string;
    /**
     * 
     * @type {string}
     * @memberof DetailBookingCourtResponse
     */
    courtName?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof DetailBookingCourtResponse
     */
    startDate?: Date;
    /**
     * 
     * @type {Date}
     * @memberof DetailBookingCourtResponse
     */
    endDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof DetailBookingCourtResponse
     */
    startTime?: string;
    /**
     * 
     * @type {string}
     * @memberof DetailBookingCourtResponse
     */
    endTime?: string;
    /**
     * 
     * @type {Array<number>}
     * @memberof DetailBookingCourtResponse
     */
    daysOfWeek?: Array<number> | null;
    /**
     * 
     * @type {string}
     * @memberof DetailBookingCourtResponse
     */
    status?: string | null;
    /**
     * 
     * @type {number}
     * @memberof DetailBookingCourtResponse
     */
    totalHours?: number;
    /**
     * 
     * @type {CustomerDto}
     * @memberof DetailBookingCourtResponse
     */
    customer?: CustomerDto;
    /**
     * 
     * @type {Array<PaymentDto>}
     * @memberof DetailBookingCourtResponse
     */
    payments?: Array<PaymentDto> | null;
    /**
     * 
     * @type {Array<BookingServiceDto>}
     * @memberof DetailBookingCourtResponse
     */
    bookingServices?: Array<BookingServiceDto> | null;
    /**
     * 
     * @type {number}
     * @memberof DetailBookingCourtResponse
     */
    totalAmount?: number;
    /**
     * 
     * @type {number}
     * @memberof DetailBookingCourtResponse
     */
    paidAmount?: number;
    /**
     * 
     * @type {number}
     * @memberof DetailBookingCourtResponse
     */
    remainingAmount?: number;
    /**
     * 
     * @type {string}
     * @memberof DetailBookingCourtResponse
     */
    paymentType?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DetailBookingCourtResponse
     */
    paymentId?: string | null;
    /**
     * 
     * @type {number}
     * @memberof DetailBookingCourtResponse
     */
    paymentAmount?: number | null;
    /**
     * 
     * @type {string}
     * @memberof DetailBookingCourtResponse
     */
    qrUrl?: string | null;
    /**
     * 
     * @type {number}
     * @memberof DetailBookingCourtResponse
     */
    holdMinutes?: number | null;
    /**
     * 
     * @type {Date}
     * @memberof DetailBookingCourtResponse
     */
    expiresAtUtc?: Date | null;
}

/**
 * Check if a given object implements the DetailBookingCourtResponse interface.
 */
export function instanceOfDetailBookingCourtResponse(value: object): value is DetailBookingCourtResponse {
    return true;
}

export function DetailBookingCourtResponseFromJSON(json: any): DetailBookingCourtResponse {
    return DetailBookingCourtResponseFromJSONTyped(json, false);
}

export function DetailBookingCourtResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DetailBookingCourtResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'customerId': json['customerId'] == null ? undefined : json['customerId'],
        'courtId': json['courtId'] == null ? undefined : json['courtId'],
        'courtName': json['courtName'] == null ? undefined : json['courtName'],
        'startDate': json['startDate'] == null ? undefined : (new Date(json['startDate'])),
        'endDate': json['endDate'] == null ? undefined : (new Date(json['endDate'])),
        'startTime': json['startTime'] == null ? undefined : json['startTime'],
        'endTime': json['endTime'] == null ? undefined : json['endTime'],
        'daysOfWeek': json['daysOfWeek'] == null ? undefined : json['daysOfWeek'],
        'status': json['status'] == null ? undefined : json['status'],
        'totalHours': json['totalHours'] == null ? undefined : json['totalHours'],
        'customer': json['customer'] == null ? undefined : CustomerDtoFromJSON(json['customer']),
        'payments': json['payments'] == null ? undefined : ((json['payments'] as Array<any>).map(PaymentDtoFromJSON)),
        'bookingServices': json['bookingServices'] == null ? undefined : ((json['bookingServices'] as Array<any>).map(BookingServiceDtoFromJSON)),
        'totalAmount': json['totalAmount'] == null ? undefined : json['totalAmount'],
        'paidAmount': json['paidAmount'] == null ? undefined : json['paidAmount'],
        'remainingAmount': json['remainingAmount'] == null ? undefined : json['remainingAmount'],
        'paymentType': json['paymentType'] == null ? undefined : json['paymentType'],
        'paymentId': json['paymentId'] == null ? undefined : json['paymentId'],
        'paymentAmount': json['paymentAmount'] == null ? undefined : json['paymentAmount'],
        'qrUrl': json['qrUrl'] == null ? undefined : json['qrUrl'],
        'holdMinutes': json['holdMinutes'] == null ? undefined : json['holdMinutes'],
        'expiresAtUtc': json['expiresAtUtc'] == null ? undefined : (new Date(json['expiresAtUtc'])),
    };
}

export function DetailBookingCourtResponseToJSON(json: any): DetailBookingCourtResponse {
    return DetailBookingCourtResponseToJSONTyped(json, false);
}

export function DetailBookingCourtResponseToJSONTyped(value?: DetailBookingCourtResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'customerId': value['customerId'],
        'courtId': value['courtId'],
        'courtName': value['courtName'],
        'startDate': value['startDate'] == null ? undefined : ((value['startDate']).toISOString().substring(0,10)),
        'endDate': value['endDate'] == null ? undefined : ((value['endDate']).toISOString().substring(0,10)),
        'startTime': value['startTime'],
        'endTime': value['endTime'],
        'daysOfWeek': value['daysOfWeek'],
        'status': value['status'],
        'totalHours': value['totalHours'],
        'customer': CustomerDtoToJSON(value['customer']),
        'payments': value['payments'] == null ? undefined : ((value['payments'] as Array<any>).map(PaymentDtoToJSON)),
        'bookingServices': value['bookingServices'] == null ? undefined : ((value['bookingServices'] as Array<any>).map(BookingServiceDtoToJSON)),
        'totalAmount': value['totalAmount'],
        'paidAmount': value['paidAmount'],
        'remainingAmount': value['remainingAmount'],
        'paymentType': value['paymentType'],
        'paymentId': value['paymentId'],
        'paymentAmount': value['paymentAmount'],
        'qrUrl': value['qrUrl'],
        'holdMinutes': value['holdMinutes'],
        'expiresAtUtc': value['expiresAtUtc'] === null ? null : ((value['expiresAtUtc'] as any)?.toISOString()),
    };
}

