/* tslint:disable */
/* eslint-disable */
/**
 * Badminton Court Management System API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CourtDto } from './CourtDto';
import {
    CourtDtoFromJSON,
    CourtDtoFromJSONTyped,
    CourtDtoToJSON,
    CourtDtoToJSONTyped,
} from './CourtDto';
import type { BookingServiceDto } from './BookingServiceDto';
import {
    BookingServiceDtoFromJSON,
    BookingServiceDtoFromJSONTyped,
    BookingServiceDtoToJSON,
    BookingServiceDtoToJSONTyped,
} from './BookingServiceDto';
import type { CustomerDto } from './CustomerDto';
import {
    CustomerDtoFromJSON,
    CustomerDtoFromJSONTyped,
    CustomerDtoToJSON,
    CustomerDtoToJSONTyped,
} from './CustomerDto';
import type { BookingOrderItemResponse } from './BookingOrderItemResponse';
import {
    BookingOrderItemResponseFromJSON,
    BookingOrderItemResponseFromJSONTyped,
    BookingOrderItemResponseToJSON,
    BookingOrderItemResponseToJSONTyped,
} from './BookingOrderItemResponse';
import type { PaymentDto } from './PaymentDto';
import {
    PaymentDtoFromJSON,
    PaymentDtoFromJSONTyped,
    PaymentDtoToJSON,
    PaymentDtoToJSONTyped,
} from './PaymentDto';

/**
 * 
 * @export
 * @interface DetailBookingCourtOccurrenceResponse
 */
export interface DetailBookingCourtOccurrenceResponse {
    /**
     * 
     * @type {string}
     * @memberof DetailBookingCourtOccurrenceResponse
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof DetailBookingCourtOccurrenceResponse
     */
    bookingCourtId?: string;
    /**
     * 
     * @type {Date}
     * @memberof DetailBookingCourtOccurrenceResponse
     */
    date?: Date;
    /**
     * 
     * @type {string}
     * @memberof DetailBookingCourtOccurrenceResponse
     */
    startTime?: string;
    /**
     * 
     * @type {string}
     * @memberof DetailBookingCourtOccurrenceResponse
     */
    endTime?: string;
    /**
     * 
     * @type {string}
     * @memberof DetailBookingCourtOccurrenceResponse
     */
    status?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DetailBookingCourtOccurrenceResponse
     */
    note?: string | null;
    /**
     * 
     * @type {number}
     * @memberof DetailBookingCourtOccurrenceResponse
     */
    totalHours?: number;
    /**
     * 
     * @type {CustomerDto}
     * @memberof DetailBookingCourtOccurrenceResponse
     */
    customer?: CustomerDto;
    /**
     * 
     * @type {CourtDto}
     * @memberof DetailBookingCourtOccurrenceResponse
     */
    court?: CourtDto;
    /**
     * 
     * @type {Array<PaymentDto>}
     * @memberof DetailBookingCourtOccurrenceResponse
     */
    payments?: Array<PaymentDto> | null;
    /**
     * 
     * @type {Array<BookingServiceDto>}
     * @memberof DetailBookingCourtOccurrenceResponse
     */
    bookingServices?: Array<BookingServiceDto> | null;
    /**
     * 
     * @type {Array<BookingOrderItemResponse>}
     * @memberof DetailBookingCourtOccurrenceResponse
     */
    bookingOrderItems?: Array<BookingOrderItemResponse> | null;
    /**
     * 
     * @type {number}
     * @memberof DetailBookingCourtOccurrenceResponse
     */
    totalAmount?: number;
    /**
     * 
     * @type {number}
     * @memberof DetailBookingCourtOccurrenceResponse
     */
    paidAmount?: number;
    /**
     * 
     * @type {number}
     * @memberof DetailBookingCourtOccurrenceResponse
     */
    remainingAmount?: number;
    /**
     * 
     * @type {string}
     * @memberof DetailBookingCourtOccurrenceResponse
     */
    paymentType?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DetailBookingCourtOccurrenceResponse
     */
    paymentId?: string | null;
    /**
     * 
     * @type {number}
     * @memberof DetailBookingCourtOccurrenceResponse
     */
    paymentAmount?: number | null;
    /**
     * 
     * @type {string}
     * @memberof DetailBookingCourtOccurrenceResponse
     */
    qrUrl?: string | null;
    /**
     * 
     * @type {number}
     * @memberof DetailBookingCourtOccurrenceResponse
     */
    holdMinutes?: number | null;
    /**
     * 
     * @type {Date}
     * @memberof DetailBookingCourtOccurrenceResponse
     */
    expiresAtUtc?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof DetailBookingCourtOccurrenceResponse
     */
    overdueMinutes?: number;
    /**
     * 
     * @type {number}
     * @memberof DetailBookingCourtOccurrenceResponse
     */
    overdueHours?: number;
    /**
     * 
     * @type {number}
     * @memberof DetailBookingCourtOccurrenceResponse
     */
    surchargeAmount?: number;
    /**
     * 
     * @type {number}
     * @memberof DetailBookingCourtOccurrenceResponse
     */
    lateFeePercentage?: number;
}

/**
 * Check if a given object implements the DetailBookingCourtOccurrenceResponse interface.
 */
export function instanceOfDetailBookingCourtOccurrenceResponse(value: object): value is DetailBookingCourtOccurrenceResponse {
    return true;
}

export function DetailBookingCourtOccurrenceResponseFromJSON(json: any): DetailBookingCourtOccurrenceResponse {
    return DetailBookingCourtOccurrenceResponseFromJSONTyped(json, false);
}

export function DetailBookingCourtOccurrenceResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DetailBookingCourtOccurrenceResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'bookingCourtId': json['bookingCourtId'] == null ? undefined : json['bookingCourtId'],
        'date': json['date'] == null ? undefined : (new Date(json['date'])),
        'startTime': json['startTime'] == null ? undefined : json['startTime'],
        'endTime': json['endTime'] == null ? undefined : json['endTime'],
        'status': json['status'] == null ? undefined : json['status'],
        'note': json['note'] == null ? undefined : json['note'],
        'totalHours': json['totalHours'] == null ? undefined : json['totalHours'],
        'customer': json['customer'] == null ? undefined : CustomerDtoFromJSON(json['customer']),
        'court': json['court'] == null ? undefined : CourtDtoFromJSON(json['court']),
        'payments': json['payments'] == null ? undefined : ((json['payments'] as Array<any>).map(PaymentDtoFromJSON)),
        'bookingServices': json['bookingServices'] == null ? undefined : ((json['bookingServices'] as Array<any>).map(BookingServiceDtoFromJSON)),
        'bookingOrderItems': json['bookingOrderItems'] == null ? undefined : ((json['bookingOrderItems'] as Array<any>).map(BookingOrderItemResponseFromJSON)),
        'totalAmount': json['totalAmount'] == null ? undefined : json['totalAmount'],
        'paidAmount': json['paidAmount'] == null ? undefined : json['paidAmount'],
        'remainingAmount': json['remainingAmount'] == null ? undefined : json['remainingAmount'],
        'paymentType': json['paymentType'] == null ? undefined : json['paymentType'],
        'paymentId': json['paymentId'] == null ? undefined : json['paymentId'],
        'paymentAmount': json['paymentAmount'] == null ? undefined : json['paymentAmount'],
        'qrUrl': json['qrUrl'] == null ? undefined : json['qrUrl'],
        'holdMinutes': json['holdMinutes'] == null ? undefined : json['holdMinutes'],
        'expiresAtUtc': json['expiresAtUtc'] == null ? undefined : (new Date(json['expiresAtUtc'])),
        'overdueMinutes': json['overdueMinutes'] == null ? undefined : json['overdueMinutes'],
        'overdueHours': json['overdueHours'] == null ? undefined : json['overdueHours'],
        'surchargeAmount': json['surchargeAmount'] == null ? undefined : json['surchargeAmount'],
        'lateFeePercentage': json['lateFeePercentage'] == null ? undefined : json['lateFeePercentage'],
    };
}

export function DetailBookingCourtOccurrenceResponseToJSON(json: any): DetailBookingCourtOccurrenceResponse {
    return DetailBookingCourtOccurrenceResponseToJSONTyped(json, false);
}

export function DetailBookingCourtOccurrenceResponseToJSONTyped(value?: DetailBookingCourtOccurrenceResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'bookingCourtId': value['bookingCourtId'],
        'date': value['date'] == null ? undefined : ((value['date']).toISOString().substring(0,10)),
        'startTime': value['startTime'],
        'endTime': value['endTime'],
        'status': value['status'],
        'note': value['note'],
        'totalHours': value['totalHours'],
        'customer': CustomerDtoToJSON(value['customer']),
        'court': CourtDtoToJSON(value['court']),
        'payments': value['payments'] == null ? undefined : ((value['payments'] as Array<any>).map(PaymentDtoToJSON)),
        'bookingServices': value['bookingServices'] == null ? undefined : ((value['bookingServices'] as Array<any>).map(BookingServiceDtoToJSON)),
        'bookingOrderItems': value['bookingOrderItems'] == null ? undefined : ((value['bookingOrderItems'] as Array<any>).map(BookingOrderItemResponseToJSON)),
        'totalAmount': value['totalAmount'],
        'paidAmount': value['paidAmount'],
        'remainingAmount': value['remainingAmount'],
        'paymentType': value['paymentType'],
        'paymentId': value['paymentId'],
        'paymentAmount': value['paymentAmount'],
        'qrUrl': value['qrUrl'],
        'holdMinutes': value['holdMinutes'],
        'expiresAtUtc': value['expiresAtUtc'] === null ? null : ((value['expiresAtUtc'] as any)?.toISOString()),
        'overdueMinutes': value['overdueMinutes'],
        'overdueHours': value['overdueHours'],
        'surchargeAmount': value['surchargeAmount'],
        'lateFeePercentage': value['lateFeePercentage'],
    };
}

