/* tslint:disable */
/* eslint-disable */
/**
 * Badminton Court Management System API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DetailInvoiceResponse } from './DetailInvoiceResponse';
import {
    DetailInvoiceResponseFromJSON,
    DetailInvoiceResponseFromJSONTyped,
    DetailInvoiceResponseToJSON,
    DetailInvoiceResponseToJSONTyped,
} from './DetailInvoiceResponse';

/**
 * 
 * @export
 * @interface DetailInvoiceResponseApiResponse
 */
export interface DetailInvoiceResponseApiResponse {
    /**
     * 
     * @type {boolean}
     * @memberof DetailInvoiceResponseApiResponse
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof DetailInvoiceResponseApiResponse
     */
    message?: string | null;
    /**
     * 
     * @type {DetailInvoiceResponse}
     * @memberof DetailInvoiceResponseApiResponse
     */
    data?: DetailInvoiceResponse;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof DetailInvoiceResponseApiResponse
     */
    errors?: { [key: string]: string; } | null;
}

/**
 * Check if a given object implements the DetailInvoiceResponseApiResponse interface.
 */
export function instanceOfDetailInvoiceResponseApiResponse(value: object): value is DetailInvoiceResponseApiResponse {
    return true;
}

export function DetailInvoiceResponseApiResponseFromJSON(json: any): DetailInvoiceResponseApiResponse {
    return DetailInvoiceResponseApiResponseFromJSONTyped(json, false);
}

export function DetailInvoiceResponseApiResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DetailInvoiceResponseApiResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : DetailInvoiceResponseFromJSON(json['data']),
        'errors': json['errors'] == null ? undefined : json['errors'],
    };
}

export function DetailInvoiceResponseApiResponseToJSON(json: any): DetailInvoiceResponseApiResponse {
    return DetailInvoiceResponseApiResponseToJSONTyped(json, false);
}

export function DetailInvoiceResponseApiResponseToJSONTyped(value?: DetailInvoiceResponseApiResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'message': value['message'],
        'data': DetailInvoiceResponseToJSON(value['data']),
        'errors': value['errors'],
    };
}

