/* tslint:disable */
/* eslint-disable */
/**
 * Badminton Court Management System API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DetailProductResponse } from './DetailProductResponse';
import {
    DetailProductResponseFromJSON,
    DetailProductResponseFromJSONTyped,
    DetailProductResponseToJSON,
    DetailProductResponseToJSONTyped,
} from './DetailProductResponse';

/**
 * 
 * @export
 * @interface DetailProductResponseApiResponse
 */
export interface DetailProductResponseApiResponse {
    /**
     * 
     * @type {boolean}
     * @memberof DetailProductResponseApiResponse
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof DetailProductResponseApiResponse
     */
    message?: string | null;
    /**
     * 
     * @type {DetailProductResponse}
     * @memberof DetailProductResponseApiResponse
     */
    data?: DetailProductResponse;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof DetailProductResponseApiResponse
     */
    errors?: { [key: string]: string; } | null;
}

/**
 * Check if a given object implements the DetailProductResponseApiResponse interface.
 */
export function instanceOfDetailProductResponseApiResponse(value: object): value is DetailProductResponseApiResponse {
    return true;
}

export function DetailProductResponseApiResponseFromJSON(json: any): DetailProductResponseApiResponse {
    return DetailProductResponseApiResponseFromJSONTyped(json, false);
}

export function DetailProductResponseApiResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DetailProductResponseApiResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : DetailProductResponseFromJSON(json['data']),
        'errors': json['errors'] == null ? undefined : json['errors'],
    };
}

export function DetailProductResponseApiResponseToJSON(json: any): DetailProductResponseApiResponse {
    return DetailProductResponseApiResponseToJSONTyped(json, false);
}

export function DetailProductResponseApiResponseToJSONTyped(value?: DetailProductResponseApiResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'message': value['message'],
        'data': DetailProductResponseToJSON(value['data']),
        'errors': value['errors'],
    };
}

