/* tslint:disable */
/* eslint-disable */
/**
 * Badminton Court Management System API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DetailCustomerResponse } from './DetailCustomerResponse';
import {
    DetailCustomerResponseFromJSON,
    DetailCustomerResponseFromJSONTyped,
    DetailCustomerResponseToJSON,
    DetailCustomerResponseToJSONTyped,
} from './DetailCustomerResponse';

/**
 * 
 * @export
 * @interface DetailCustomerResponseApiResponse
 */
export interface DetailCustomerResponseApiResponse {
    /**
     * 
     * @type {boolean}
     * @memberof DetailCustomerResponseApiResponse
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof DetailCustomerResponseApiResponse
     */
    message?: string | null;
    /**
     * 
     * @type {DetailCustomerResponse}
     * @memberof DetailCustomerResponseApiResponse
     */
    data?: DetailCustomerResponse;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof DetailCustomerResponseApiResponse
     */
    errors?: { [key: string]: string; } | null;
}

/**
 * Check if a given object implements the DetailCustomerResponseApiResponse interface.
 */
export function instanceOfDetailCustomerResponseApiResponse(value: object): value is DetailCustomerResponseApiResponse {
    return true;
}

export function DetailCustomerResponseApiResponseFromJSON(json: any): DetailCustomerResponseApiResponse {
    return DetailCustomerResponseApiResponseFromJSONTyped(json, false);
}

export function DetailCustomerResponseApiResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DetailCustomerResponseApiResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : DetailCustomerResponseFromJSON(json['data']),
        'errors': json['errors'] == null ? undefined : json['errors'],
    };
}

export function DetailCustomerResponseApiResponseToJSON(json: any): DetailCustomerResponseApiResponse {
    return DetailCustomerResponseApiResponseToJSONTyped(json, false);
}

export function DetailCustomerResponseApiResponseToJSONTyped(value?: DetailCustomerResponseApiResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'message': value['message'],
        'data': DetailCustomerResponseToJSON(value['data']),
        'errors': value['errors'],
    };
}

