/* tslint:disable */
/* eslint-disable */
/**
 * Badminton Court Management System API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DetailMembershipRequest
 */
export interface DetailMembershipRequest {
    /**
     * 
     * @type {number}
     * @memberof DetailMembershipRequest
     */
    id: number;
}

/**
 * Check if a given object implements the DetailMembershipRequest interface.
 */
export function instanceOfDetailMembershipRequest(value: object): value is DetailMembershipRequest {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function DetailMembershipRequestFromJSON(json: any): DetailMembershipRequest {
    return DetailMembershipRequestFromJSONTyped(json, false);
}

export function DetailMembershipRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DetailMembershipRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function DetailMembershipRequestToJSON(json: any): DetailMembershipRequest {
    return DetailMembershipRequestToJSONTyped(json, false);
}

export function DetailMembershipRequestToJSONTyped(value?: DetailMembershipRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
    };
}

