/* tslint:disable */
/* eslint-disable */
/**
 * Badminton Court Management System API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DetailSupplierResponse
 */
export interface DetailSupplierResponse {
    /**
     * 
     * @type {Date}
     * @memberof DetailSupplierResponse
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof DetailSupplierResponse
     */
    updatedAt?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof DetailSupplierResponse
     */
    createdBy?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DetailSupplierResponse
     */
    updatedBy?: string | null;
    /**
     * 
     * @type {number}
     * @memberof DetailSupplierResponse
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof DetailSupplierResponse
     */
    name: string | null;
    /**
     * 
     * @type {string}
     * @memberof DetailSupplierResponse
     */
    phone: string | null;
    /**
     * 
     * @type {string}
     * @memberof DetailSupplierResponse
     */
    email: string | null;
    /**
     * 
     * @type {string}
     * @memberof DetailSupplierResponse
     */
    address?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DetailSupplierResponse
     */
    city?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DetailSupplierResponse
     */
    district?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DetailSupplierResponse
     */
    ward?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DetailSupplierResponse
     */
    notes?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DetailSupplierResponse
     */
    status: string | null;
}

/**
 * Check if a given object implements the DetailSupplierResponse interface.
 */
export function instanceOfDetailSupplierResponse(value: object): value is DetailSupplierResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('phone' in value) || value['phone'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function DetailSupplierResponseFromJSON(json: any): DetailSupplierResponse {
    return DetailSupplierResponseFromJSONTyped(json, false);
}

export function DetailSupplierResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DetailSupplierResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
        'createdBy': json['createdBy'] == null ? undefined : json['createdBy'],
        'updatedBy': json['updatedBy'] == null ? undefined : json['updatedBy'],
        'id': json['id'],
        'name': json['name'],
        'phone': json['phone'],
        'email': json['email'],
        'address': json['address'] == null ? undefined : json['address'],
        'city': json['city'] == null ? undefined : json['city'],
        'district': json['district'] == null ? undefined : json['district'],
        'ward': json['ward'] == null ? undefined : json['ward'],
        'notes': json['notes'] == null ? undefined : json['notes'],
        'status': json['status'],
    };
}

export function DetailSupplierResponseToJSON(json: any): DetailSupplierResponse {
    return DetailSupplierResponseToJSONTyped(json, false);
}

export function DetailSupplierResponseToJSONTyped(value?: DetailSupplierResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'updatedAt': value['updatedAt'] === null ? null : ((value['updatedAt'] as any)?.toISOString()),
        'createdBy': value['createdBy'],
        'updatedBy': value['updatedBy'],
        'id': value['id'],
        'name': value['name'],
        'phone': value['phone'],
        'email': value['email'],
        'address': value['address'],
        'city': value['city'],
        'district': value['district'],
        'ward': value['ward'],
        'notes': value['notes'],
        'status': value['status'],
    };
}

