/* tslint:disable */
/* eslint-disable */
/**
 * Badminton Court Management System API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DetailProductResponse
 */
export interface DetailProductResponse {
    /**
     * 
     * @type {number}
     * @memberof DetailProductResponse
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof DetailProductResponse
     */
    code?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DetailProductResponse
     */
    name: string | null;
    /**
     * 
     * @type {string}
     * @memberof DetailProductResponse
     */
    menuType?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DetailProductResponse
     */
    category?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DetailProductResponse
     */
    position?: string | null;
    /**
     * 
     * @type {number}
     * @memberof DetailProductResponse
     */
    costPrice?: number;
    /**
     * 
     * @type {number}
     * @memberof DetailProductResponse
     */
    salePrice?: number;
    /**
     * 
     * @type {boolean}
     * @memberof DetailProductResponse
     */
    isDirectSale?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof DetailProductResponse
     */
    isExtraTopping?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof DetailProductResponse
     */
    manageInventory?: boolean;
    /**
     * 
     * @type {number}
     * @memberof DetailProductResponse
     */
    stock?: number;
    /**
     * 
     * @type {number}
     * @memberof DetailProductResponse
     */
    minStock?: number;
    /**
     * 
     * @type {number}
     * @memberof DetailProductResponse
     */
    maxStock?: number;
    /**
     * 
     * @type {string}
     * @memberof DetailProductResponse
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DetailProductResponse
     */
    noteTemplate?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof DetailProductResponse
     */
    images?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof DetailProductResponse
     */
    unit?: string | null;
}

/**
 * Check if a given object implements the DetailProductResponse interface.
 */
export function instanceOfDetailProductResponse(value: object): value is DetailProductResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function DetailProductResponseFromJSON(json: any): DetailProductResponse {
    return DetailProductResponseFromJSONTyped(json, false);
}

export function DetailProductResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DetailProductResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'code': json['code'] == null ? undefined : json['code'],
        'name': json['name'],
        'menuType': json['menuType'] == null ? undefined : json['menuType'],
        'category': json['category'] == null ? undefined : json['category'],
        'position': json['position'] == null ? undefined : json['position'],
        'costPrice': json['costPrice'] == null ? undefined : json['costPrice'],
        'salePrice': json['salePrice'] == null ? undefined : json['salePrice'],
        'isDirectSale': json['isDirectSale'] == null ? undefined : json['isDirectSale'],
        'isExtraTopping': json['isExtraTopping'] == null ? undefined : json['isExtraTopping'],
        'manageInventory': json['manageInventory'] == null ? undefined : json['manageInventory'],
        'stock': json['stock'] == null ? undefined : json['stock'],
        'minStock': json['minStock'] == null ? undefined : json['minStock'],
        'maxStock': json['maxStock'] == null ? undefined : json['maxStock'],
        'description': json['description'] == null ? undefined : json['description'],
        'noteTemplate': json['noteTemplate'] == null ? undefined : json['noteTemplate'],
        'images': json['images'] == null ? undefined : json['images'],
        'unit': json['unit'] == null ? undefined : json['unit'],
    };
}

export function DetailProductResponseToJSON(json: any): DetailProductResponse {
    return DetailProductResponseToJSONTyped(json, false);
}

export function DetailProductResponseToJSONTyped(value?: DetailProductResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'code': value['code'],
        'name': value['name'],
        'menuType': value['menuType'],
        'category': value['category'],
        'position': value['position'],
        'costPrice': value['costPrice'],
        'salePrice': value['salePrice'],
        'isDirectSale': value['isDirectSale'],
        'isExtraTopping': value['isExtraTopping'],
        'manageInventory': value['manageInventory'],
        'stock': value['stock'],
        'minStock': value['minStock'],
        'maxStock': value['maxStock'],
        'description': value['description'],
        'noteTemplate': value['noteTemplate'],
        'images': value['images'],
        'unit': value['unit'],
    };
}

