/* tslint:disable */
/* eslint-disable */
/**
 * Badminton Court Management System API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DetailReturnGoodsResponse } from './DetailReturnGoodsResponse';
import {
    DetailReturnGoodsResponseFromJSON,
    DetailReturnGoodsResponseFromJSONTyped,
    DetailReturnGoodsResponseToJSON,
    DetailReturnGoodsResponseToJSONTyped,
} from './DetailReturnGoodsResponse';

/**
 * 
 * @export
 * @interface DetailReturnGoodsResponseApiResponse
 */
export interface DetailReturnGoodsResponseApiResponse {
    /**
     * 
     * @type {boolean}
     * @memberof DetailReturnGoodsResponseApiResponse
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof DetailReturnGoodsResponseApiResponse
     */
    message?: string | null;
    /**
     * 
     * @type {DetailReturnGoodsResponse}
     * @memberof DetailReturnGoodsResponseApiResponse
     */
    data?: DetailReturnGoodsResponse;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof DetailReturnGoodsResponseApiResponse
     */
    errors?: { [key: string]: string; } | null;
}

/**
 * Check if a given object implements the DetailReturnGoodsResponseApiResponse interface.
 */
export function instanceOfDetailReturnGoodsResponseApiResponse(value: object): value is DetailReturnGoodsResponseApiResponse {
    return true;
}

export function DetailReturnGoodsResponseApiResponseFromJSON(json: any): DetailReturnGoodsResponseApiResponse {
    return DetailReturnGoodsResponseApiResponseFromJSONTyped(json, false);
}

export function DetailReturnGoodsResponseApiResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DetailReturnGoodsResponseApiResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : DetailReturnGoodsResponseFromJSON(json['data']),
        'errors': json['errors'] == null ? undefined : json['errors'],
    };
}

export function DetailReturnGoodsResponseApiResponseToJSON(json: any): DetailReturnGoodsResponseApiResponse {
    return DetailReturnGoodsResponseApiResponseToJSONTyped(json, false);
}

export function DetailReturnGoodsResponseApiResponseToJSONTyped(value?: DetailReturnGoodsResponseApiResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'message': value['message'],
        'data': DetailReturnGoodsResponseToJSON(value['data']),
        'errors': value['errors'],
    };
}

