/* tslint:disable */
/* eslint-disable */
/**
 * Badminton Court Management System API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DetailCashflowRequest
 */
export interface DetailCashflowRequest {
    /**
     * 
     * @type {string}
     * @memberof DetailCashflowRequest
     */
    referenceNumber?: string | null;
}

/**
 * Check if a given object implements the DetailCashflowRequest interface.
 */
export function instanceOfDetailCashflowRequest(value: object): value is DetailCashflowRequest {
    return true;
}

export function DetailCashflowRequestFromJSON(json: any): DetailCashflowRequest {
    return DetailCashflowRequestFromJSONTyped(json, false);
}

export function DetailCashflowRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DetailCashflowRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'referenceNumber': json['referenceNumber'] == null ? undefined : json['referenceNumber'],
    };
}

export function DetailCashflowRequestToJSON(json: any): DetailCashflowRequest {
    return DetailCashflowRequestToJSONTyped(json, false);
}

export function DetailCashflowRequestToJSONTyped(value?: DetailCashflowRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'referenceNumber': value['referenceNumber'],
    };
}

