/* tslint:disable */
/* eslint-disable */
/**
 * Badminton Court Management System API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DetailReturnGoodsItem } from './DetailReturnGoodsItem';
import {
    DetailReturnGoodsItemFromJSON,
    DetailReturnGoodsItemFromJSONTyped,
    DetailReturnGoodsItemToJSON,
    DetailReturnGoodsItemToJSONTyped,
} from './DetailReturnGoodsItem';

/**
 * 
 * @export
 * @interface DetailReturnGoodsResponse
 */
export interface DetailReturnGoodsResponse {
    /**
     * 
     * @type {number}
     * @memberof DetailReturnGoodsResponse
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof DetailReturnGoodsResponse
     */
    code?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof DetailReturnGoodsResponse
     */
    returnTime?: Date;
    /**
     * 
     * @type {number}
     * @memberof DetailReturnGoodsResponse
     */
    supplierId?: number;
    /**
     * 
     * @type {string}
     * @memberof DetailReturnGoodsResponse
     */
    supplierName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DetailReturnGoodsResponse
     */
    returnBy?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DetailReturnGoodsResponse
     */
    createdBy?: string | null;
    /**
     * 
     * @type {number}
     * @memberof DetailReturnGoodsResponse
     */
    totalValue?: number;
    /**
     * 
     * @type {number}
     * @memberof DetailReturnGoodsResponse
     */
    discount?: number;
    /**
     * 
     * @type {number}
     * @memberof DetailReturnGoodsResponse
     */
    supplierNeedToPay?: number;
    /**
     * 
     * @type {number}
     * @memberof DetailReturnGoodsResponse
     */
    supplierPaid?: number;
    /**
     * 
     * @type {number}
     * @memberof DetailReturnGoodsResponse
     */
    paymentMethod?: number;
    /**
     * 
     * @type {number}
     * @memberof DetailReturnGoodsResponse
     */
    storeBankAccountId?: number | null;
    /**
     * 
     * @type {string}
     * @memberof DetailReturnGoodsResponse
     */
    note?: string | null;
    /**
     * 
     * @type {number}
     * @memberof DetailReturnGoodsResponse
     */
    status?: number;
    /**
     * 
     * @type {Array<DetailReturnGoodsItem>}
     * @memberof DetailReturnGoodsResponse
     */
    items?: Array<DetailReturnGoodsItem> | null;
}

/**
 * Check if a given object implements the DetailReturnGoodsResponse interface.
 */
export function instanceOfDetailReturnGoodsResponse(value: object): value is DetailReturnGoodsResponse {
    return true;
}

export function DetailReturnGoodsResponseFromJSON(json: any): DetailReturnGoodsResponse {
    return DetailReturnGoodsResponseFromJSONTyped(json, false);
}

export function DetailReturnGoodsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DetailReturnGoodsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'code': json['code'] == null ? undefined : json['code'],
        'returnTime': json['returnTime'] == null ? undefined : (new Date(json['returnTime'])),
        'supplierId': json['supplierId'] == null ? undefined : json['supplierId'],
        'supplierName': json['supplierName'] == null ? undefined : json['supplierName'],
        'returnBy': json['returnBy'] == null ? undefined : json['returnBy'],
        'createdBy': json['createdBy'] == null ? undefined : json['createdBy'],
        'totalValue': json['totalValue'] == null ? undefined : json['totalValue'],
        'discount': json['discount'] == null ? undefined : json['discount'],
        'supplierNeedToPay': json['supplierNeedToPay'] == null ? undefined : json['supplierNeedToPay'],
        'supplierPaid': json['supplierPaid'] == null ? undefined : json['supplierPaid'],
        'paymentMethod': json['paymentMethod'] == null ? undefined : json['paymentMethod'],
        'storeBankAccountId': json['storeBankAccountId'] == null ? undefined : json['storeBankAccountId'],
        'note': json['note'] == null ? undefined : json['note'],
        'status': json['status'] == null ? undefined : json['status'],
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(DetailReturnGoodsItemFromJSON)),
    };
}

export function DetailReturnGoodsResponseToJSON(json: any): DetailReturnGoodsResponse {
    return DetailReturnGoodsResponseToJSONTyped(json, false);
}

export function DetailReturnGoodsResponseToJSONTyped(value?: DetailReturnGoodsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'code': value['code'],
        'returnTime': value['returnTime'] == null ? undefined : ((value['returnTime']).toISOString()),
        'supplierId': value['supplierId'],
        'supplierName': value['supplierName'],
        'returnBy': value['returnBy'],
        'createdBy': value['createdBy'],
        'totalValue': value['totalValue'],
        'discount': value['discount'],
        'supplierNeedToPay': value['supplierNeedToPay'],
        'supplierPaid': value['supplierPaid'],
        'paymentMethod': value['paymentMethod'],
        'storeBankAccountId': value['storeBankAccountId'],
        'note': value['note'],
        'status': value['status'],
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(DetailReturnGoodsItemToJSON)),
    };
}

