/* tslint:disable */
/* eslint-disable */
/**
 * Badminton Court Management System API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DetailBookingCourtOccurrenceResponse } from './DetailBookingCourtOccurrenceResponse';
import {
    DetailBookingCourtOccurrenceResponseFromJSON,
    DetailBookingCourtOccurrenceResponseFromJSONTyped,
    DetailBookingCourtOccurrenceResponseToJSON,
    DetailBookingCourtOccurrenceResponseToJSONTyped,
} from './DetailBookingCourtOccurrenceResponse';

/**
 * 
 * @export
 * @interface DetailBookingCourtOccurrenceResponseApiResponse
 */
export interface DetailBookingCourtOccurrenceResponseApiResponse {
    /**
     * 
     * @type {boolean}
     * @memberof DetailBookingCourtOccurrenceResponseApiResponse
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof DetailBookingCourtOccurrenceResponseApiResponse
     */
    message?: string | null;
    /**
     * 
     * @type {DetailBookingCourtOccurrenceResponse}
     * @memberof DetailBookingCourtOccurrenceResponseApiResponse
     */
    data?: DetailBookingCourtOccurrenceResponse;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof DetailBookingCourtOccurrenceResponseApiResponse
     */
    errors?: { [key: string]: string; } | null;
}

/**
 * Check if a given object implements the DetailBookingCourtOccurrenceResponseApiResponse interface.
 */
export function instanceOfDetailBookingCourtOccurrenceResponseApiResponse(value: object): value is DetailBookingCourtOccurrenceResponseApiResponse {
    return true;
}

export function DetailBookingCourtOccurrenceResponseApiResponseFromJSON(json: any): DetailBookingCourtOccurrenceResponseApiResponse {
    return DetailBookingCourtOccurrenceResponseApiResponseFromJSONTyped(json, false);
}

export function DetailBookingCourtOccurrenceResponseApiResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DetailBookingCourtOccurrenceResponseApiResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : DetailBookingCourtOccurrenceResponseFromJSON(json['data']),
        'errors': json['errors'] == null ? undefined : json['errors'],
    };
}

export function DetailBookingCourtOccurrenceResponseApiResponseToJSON(json: any): DetailBookingCourtOccurrenceResponseApiResponse {
    return DetailBookingCourtOccurrenceResponseApiResponseToJSONTyped(json, false);
}

export function DetailBookingCourtOccurrenceResponseApiResponseToJSONTyped(value?: DetailBookingCourtOccurrenceResponseApiResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'message': value['message'],
        'data': DetailBookingCourtOccurrenceResponseToJSON(value['data']),
        'errors': value['errors'],
    };
}

