/* tslint:disable */
/* eslint-disable */
/**
 * Badminton Court Management System API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EmailTemplateType } from './EmailTemplateType';
import {
    EmailTemplateTypeFromJSON,
    EmailTemplateTypeFromJSONTyped,
    EmailTemplateTypeToJSON,
    EmailTemplateTypeToJSONTyped,
} from './EmailTemplateType';

/**
 * 
 * @export
 * @interface EmailTemplateRequest
 */
export interface EmailTemplateRequest {
    /**
     * 
     * @type {string}
     * @memberof EmailTemplateRequest
     */
    to?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EmailTemplateRequest
     */
    toName?: string | null;
    /**
     * 
     * @type {EmailTemplateType}
     * @memberof EmailTemplateRequest
     */
    templateType?: EmailTemplateType;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof EmailTemplateRequest
     */
    templateData?: { [key: string]: string; } | null;
    /**
     * 
     * @type {string}
     * @memberof EmailTemplateRequest
     */
    subject?: string | null;
}



/**
 * Check if a given object implements the EmailTemplateRequest interface.
 */
export function instanceOfEmailTemplateRequest(value: object): value is EmailTemplateRequest {
    return true;
}

export function EmailTemplateRequestFromJSON(json: any): EmailTemplateRequest {
    return EmailTemplateRequestFromJSONTyped(json, false);
}

export function EmailTemplateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailTemplateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'to': json['to'] == null ? undefined : json['to'],
        'toName': json['toName'] == null ? undefined : json['toName'],
        'templateType': json['templateType'] == null ? undefined : EmailTemplateTypeFromJSON(json['templateType']),
        'templateData': json['templateData'] == null ? undefined : json['templateData'],
        'subject': json['subject'] == null ? undefined : json['subject'],
    };
}

export function EmailTemplateRequestToJSON(json: any): EmailTemplateRequest {
    return EmailTemplateRequestToJSONTyped(json, false);
}

export function EmailTemplateRequestToJSONTyped(value?: EmailTemplateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'to': value['to'],
        'toName': value['toName'],
        'templateType': EmailTemplateTypeToJSON(value['templateType']),
        'templateData': value['templateData'],
        'subject': value['subject'],
    };
}

