/* tslint:disable */
/* eslint-disable */
/**
 * Badminton Court Management System API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const EmailTemplateType = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3,
    NUMBER_4: 4,
    NUMBER_5: 5
} as const;
export type EmailTemplateType = typeof EmailTemplateType[keyof typeof EmailTemplateType];


export function instanceOfEmailTemplateType(value: any): boolean {
    for (const key in EmailTemplateType) {
        if (Object.prototype.hasOwnProperty.call(EmailTemplateType, key)) {
            if (EmailTemplateType[key as keyof typeof EmailTemplateType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function EmailTemplateTypeFromJSON(json: any): EmailTemplateType {
    return EmailTemplateTypeFromJSONTyped(json, false);
}

export function EmailTemplateTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailTemplateType {
    return json as EmailTemplateType;
}

export function EmailTemplateTypeToJSON(value?: EmailTemplateType | null): any {
    return value as any;
}

export function EmailTemplateTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): EmailTemplateType {
    return value as EmailTemplateType;
}

