/* tslint:disable */
/* eslint-disable */
/**
 * Badminton Court Management System API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExtendVoucherRequest
 */
export interface ExtendVoucherRequest {
    /**
     * 
     * @type {Date}
     * @memberof ExtendVoucherRequest
     */
    endAt?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof ExtendVoucherRequest
     */
    usageLimitTotal?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ExtendVoucherRequest
     */
    usageLimitPerUser?: number | null;
}

/**
 * Check if a given object implements the ExtendVoucherRequest interface.
 */
export function instanceOfExtendVoucherRequest(value: object): value is ExtendVoucherRequest {
    return true;
}

export function ExtendVoucherRequestFromJSON(json: any): ExtendVoucherRequest {
    return ExtendVoucherRequestFromJSONTyped(json, false);
}

export function ExtendVoucherRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExtendVoucherRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'endAt': json['endAt'] == null ? undefined : (new Date(json['endAt'])),
        'usageLimitTotal': json['usageLimitTotal'] == null ? undefined : json['usageLimitTotal'],
        'usageLimitPerUser': json['usageLimitPerUser'] == null ? undefined : json['usageLimitPerUser'],
    };
}

export function ExtendVoucherRequestToJSON(json: any): ExtendVoucherRequest {
    return ExtendVoucherRequestToJSONTyped(json, false);
}

export function ExtendVoucherRequestToJSONTyped(value?: ExtendVoucherRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'endAt': value['endAt'] === null ? null : ((value['endAt'] as any)?.toISOString()),
        'usageLimitTotal': value['usageLimitTotal'],
        'usageLimitPerUser': value['usageLimitPerUser'],
    };
}

