/* tslint:disable */
/* eslint-disable */
/**
 * Badminton Court Management System API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Customer } from './Customer';
import {
    CustomerFromJSON,
    CustomerFromJSONTyped,
    CustomerToJSON,
    CustomerToJSONTyped,
} from './Customer';
import type { BookingCourtOccurrence } from './BookingCourtOccurrence';
import {
    BookingCourtOccurrenceFromJSON,
    BookingCourtOccurrenceFromJSONTyped,
    BookingCourtOccurrenceToJSON,
    BookingCourtOccurrenceToJSONTyped,
} from './BookingCourtOccurrence';

/**
 * 
 * @export
 * @interface Feedback
 */
export interface Feedback {
    /**
     * 
     * @type {Date}
     * @memberof Feedback
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Feedback
     */
    updatedAt?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof Feedback
     */
    createdBy?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Feedback
     */
    updatedBy?: string | null;
    /**
     * 
     * @type {number}
     * @memberof Feedback
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof Feedback
     */
    customerId: number;
    /**
     * 
     * @type {Customer}
     * @memberof Feedback
     */
    customer?: Customer;
    /**
     * 
     * @type {string}
     * @memberof Feedback
     */
    bookingCourtOccurrenceId: string;
    /**
     * 
     * @type {BookingCourtOccurrence}
     * @memberof Feedback
     */
    bookingCourtOccurrence?: BookingCourtOccurrence;
    /**
     * 
     * @type {number}
     * @memberof Feedback
     */
    rating?: number;
    /**
     * 
     * @type {string}
     * @memberof Feedback
     */
    comment?: string | null;
    /**
     * 
     * @type {number}
     * @memberof Feedback
     */
    courtQuality?: number;
    /**
     * 
     * @type {number}
     * @memberof Feedback
     */
    staffService?: number;
    /**
     * 
     * @type {number}
     * @memberof Feedback
     */
    cleanliness?: number;
    /**
     * 
     * @type {number}
     * @memberof Feedback
     */
    lighting?: number;
    /**
     * 
     * @type {number}
     * @memberof Feedback
     */
    valueForMoney?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof Feedback
     */
    mediaUrl?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof Feedback
     */
    adminReply?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof Feedback
     */
    adminReplyAt?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof Feedback
     */
    status?: string | null;
}

/**
 * Check if a given object implements the Feedback interface.
 */
export function instanceOfFeedback(value: object): value is Feedback {
    if (!('customerId' in value) || value['customerId'] === undefined) return false;
    if (!('bookingCourtOccurrenceId' in value) || value['bookingCourtOccurrenceId'] === undefined) return false;
    return true;
}

export function FeedbackFromJSON(json: any): Feedback {
    return FeedbackFromJSONTyped(json, false);
}

export function FeedbackFromJSONTyped(json: any, ignoreDiscriminator: boolean): Feedback {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
        'createdBy': json['createdBy'] == null ? undefined : json['createdBy'],
        'updatedBy': json['updatedBy'] == null ? undefined : json['updatedBy'],
        'id': json['id'] == null ? undefined : json['id'],
        'customerId': json['customerId'],
        'customer': json['customer'] == null ? undefined : CustomerFromJSON(json['customer']),
        'bookingCourtOccurrenceId': json['bookingCourtOccurrenceId'],
        'bookingCourtOccurrence': json['bookingCourtOccurrence'] == null ? undefined : BookingCourtOccurrenceFromJSON(json['bookingCourtOccurrence']),
        'rating': json['rating'] == null ? undefined : json['rating'],
        'comment': json['comment'] == null ? undefined : json['comment'],
        'courtQuality': json['courtQuality'] == null ? undefined : json['courtQuality'],
        'staffService': json['staffService'] == null ? undefined : json['staffService'],
        'cleanliness': json['cleanliness'] == null ? undefined : json['cleanliness'],
        'lighting': json['lighting'] == null ? undefined : json['lighting'],
        'valueForMoney': json['valueForMoney'] == null ? undefined : json['valueForMoney'],
        'mediaUrl': json['mediaUrl'] == null ? undefined : json['mediaUrl'],
        'adminReply': json['adminReply'] == null ? undefined : json['adminReply'],
        'adminReplyAt': json['adminReplyAt'] == null ? undefined : (new Date(json['adminReplyAt'])),
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function FeedbackToJSON(json: any): Feedback {
    return FeedbackToJSONTyped(json, false);
}

export function FeedbackToJSONTyped(value?: Feedback | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'updatedAt': value['updatedAt'] === null ? null : ((value['updatedAt'] as any)?.toISOString()),
        'createdBy': value['createdBy'],
        'updatedBy': value['updatedBy'],
        'id': value['id'],
        'customerId': value['customerId'],
        'customer': CustomerToJSON(value['customer']),
        'bookingCourtOccurrenceId': value['bookingCourtOccurrenceId'],
        'bookingCourtOccurrence': BookingCourtOccurrenceToJSON(value['bookingCourtOccurrence']),
        'rating': value['rating'],
        'comment': value['comment'],
        'courtQuality': value['courtQuality'],
        'staffService': value['staffService'],
        'cleanliness': value['cleanliness'],
        'lighting': value['lighting'],
        'valueForMoney': value['valueForMoney'],
        'mediaUrl': value['mediaUrl'],
        'adminReply': value['adminReply'],
        'adminReplyAt': value['adminReplyAt'] === null ? null : ((value['adminReplyAt'] as any)?.toISOString()),
        'status': value['status'],
    };
}

