/* tslint:disable */
/* eslint-disable */
/**
 * Badminton Court Management System API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListProductsByPriceTableRequest
 */
export interface ListProductsByPriceTableRequest {
    /**
     * 
     * @type {number}
     * @memberof ListProductsByPriceTableRequest
     */
    priceTableId: number;
    /**
     * 
     * @type {string}
     * @memberof ListProductsByPriceTableRequest
     */
    search?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ListProductsByPriceTableRequest
     */
    categoryId?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof ListProductsByPriceTableRequest
     */
    isActive?: boolean | null;
}

/**
 * Check if a given object implements the ListProductsByPriceTableRequest interface.
 */
export function instanceOfListProductsByPriceTableRequest(value: object): value is ListProductsByPriceTableRequest {
    if (!('priceTableId' in value) || value['priceTableId'] === undefined) return false;
    return true;
}

export function ListProductsByPriceTableRequestFromJSON(json: any): ListProductsByPriceTableRequest {
    return ListProductsByPriceTableRequestFromJSONTyped(json, false);
}

export function ListProductsByPriceTableRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListProductsByPriceTableRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'priceTableId': json['priceTableId'],
        'search': json['search'] == null ? undefined : json['search'],
        'categoryId': json['categoryId'] == null ? undefined : json['categoryId'],
        'isActive': json['isActive'] == null ? undefined : json['isActive'],
    };
}

export function ListProductsByPriceTableRequestToJSON(json: any): ListProductsByPriceTableRequest {
    return ListProductsByPriceTableRequestToJSONTyped(json, false);
}

export function ListProductsByPriceTableRequestToJSONTyped(value?: ListProductsByPriceTableRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'priceTableId': value['priceTableId'],
        'search': value['search'],
        'categoryId': value['categoryId'],
        'isActive': value['isActive'],
    };
}

