/* tslint:disable */
/* eslint-disable */
/**
 * Badminton Court Management System API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ListProductsByPriceTableResponse } from './ListProductsByPriceTableResponse';
import {
    ListProductsByPriceTableResponseFromJSON,
    ListProductsByPriceTableResponseFromJSONTyped,
    ListProductsByPriceTableResponseToJSON,
    ListProductsByPriceTableResponseToJSONTyped,
} from './ListProductsByPriceTableResponse';

/**
 * 
 * @export
 * @interface ListProductsByPriceTableResponseListApiResponse
 */
export interface ListProductsByPriceTableResponseListApiResponse {
    /**
     * 
     * @type {boolean}
     * @memberof ListProductsByPriceTableResponseListApiResponse
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ListProductsByPriceTableResponseListApiResponse
     */
    message?: string | null;
    /**
     * 
     * @type {Array<ListProductsByPriceTableResponse>}
     * @memberof ListProductsByPriceTableResponseListApiResponse
     */
    data?: Array<ListProductsByPriceTableResponse> | null;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof ListProductsByPriceTableResponseListApiResponse
     */
    errors?: { [key: string]: string; } | null;
}

/**
 * Check if a given object implements the ListProductsByPriceTableResponseListApiResponse interface.
 */
export function instanceOfListProductsByPriceTableResponseListApiResponse(value: object): value is ListProductsByPriceTableResponseListApiResponse {
    return true;
}

export function ListProductsByPriceTableResponseListApiResponseFromJSON(json: any): ListProductsByPriceTableResponseListApiResponse {
    return ListProductsByPriceTableResponseListApiResponseFromJSONTyped(json, false);
}

export function ListProductsByPriceTableResponseListApiResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListProductsByPriceTableResponseListApiResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(ListProductsByPriceTableResponseFromJSON)),
        'errors': json['errors'] == null ? undefined : json['errors'],
    };
}

export function ListProductsByPriceTableResponseListApiResponseToJSON(json: any): ListProductsByPriceTableResponseListApiResponse {
    return ListProductsByPriceTableResponseListApiResponseToJSONTyped(json, false);
}

export function ListProductsByPriceTableResponseListApiResponseToJSONTyped(value?: ListProductsByPriceTableResponseListApiResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'message': value['message'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(ListProductsByPriceTableResponseToJSON)),
        'errors': value['errors'],
    };
}

