/* tslint:disable */
/* eslint-disable */
/**
 * Badminton Court Management System API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListCashflowRequest
 */
export interface ListCashflowRequest {
    /**
     * 
     * @type {boolean}
     * @memberof ListCashflowRequest
     */
    isPayment?: boolean | null;
    /**
     * 
     * @type {Date}
     * @memberof ListCashflowRequest
     */
    from?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof ListCashflowRequest
     */
    to?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof ListCashflowRequest
     */
    cashflowTypeId?: number | null;
    /**
     * 
     * @type {string}
     * @memberof ListCashflowRequest
     */
    status?: string | null;
}

/**
 * Check if a given object implements the ListCashflowRequest interface.
 */
export function instanceOfListCashflowRequest(value: object): value is ListCashflowRequest {
    return true;
}

export function ListCashflowRequestFromJSON(json: any): ListCashflowRequest {
    return ListCashflowRequestFromJSONTyped(json, false);
}

export function ListCashflowRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListCashflowRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'isPayment': json['isPayment'] == null ? undefined : json['isPayment'],
        'from': json['from'] == null ? undefined : (new Date(json['from'])),
        'to': json['to'] == null ? undefined : (new Date(json['to'])),
        'cashflowTypeId': json['cashflowTypeId'] == null ? undefined : json['cashflowTypeId'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function ListCashflowRequestToJSON(json: any): ListCashflowRequest {
    return ListCashflowRequestToJSONTyped(json, false);
}

export function ListCashflowRequestToJSONTyped(value?: ListCashflowRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'isPayment': value['isPayment'],
        'from': value['from'] === null ? null : ((value['from'] as any)?.toISOString()),
        'to': value['to'] === null ? null : ((value['to'] as any)?.toISOString()),
        'cashflowTypeId': value['cashflowTypeId'],
        'status': value['status'],
    };
}

