/* tslint:disable */
/* eslint-disable */
/**
 * Badminton Court Management System API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListReturnGoodsRequest
 */
export interface ListReturnGoodsRequest {
    /**
     * 
     * @type {Date}
     * @memberof ListReturnGoodsRequest
     */
    from?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof ListReturnGoodsRequest
     */
    to?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof ListReturnGoodsRequest
     */
    status?: number | null;
}

/**
 * Check if a given object implements the ListReturnGoodsRequest interface.
 */
export function instanceOfListReturnGoodsRequest(value: object): value is ListReturnGoodsRequest {
    return true;
}

export function ListReturnGoodsRequestFromJSON(json: any): ListReturnGoodsRequest {
    return ListReturnGoodsRequestFromJSONTyped(json, false);
}

export function ListReturnGoodsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListReturnGoodsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'from': json['from'] == null ? undefined : (new Date(json['from'])),
        'to': json['to'] == null ? undefined : (new Date(json['to'])),
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function ListReturnGoodsRequestToJSON(json: any): ListReturnGoodsRequest {
    return ListReturnGoodsRequestToJSONTyped(json, false);
}

export function ListReturnGoodsRequestToJSONTyped(value?: ListReturnGoodsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'from': value['from'] === null ? null : ((value['from'] as any)?.toISOString()),
        'to': value['to'] === null ? null : ((value['to'] as any)?.toISOString()),
        'status': value['status'],
    };
}

