/* tslint:disable */
/* eslint-disable */
/**
 * Badminton Court Management System API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListCourtPricingRulesResponse
 */
export interface ListCourtPricingRulesResponse {
    /**
     * 
     * @type {string}
     * @memberof ListCourtPricingRulesResponse
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ListCourtPricingRulesResponse
     */
    courtId?: string;
    /**
     * 
     * @type {Array<number>}
     * @memberof ListCourtPricingRulesResponse
     */
    daysOfWeek?: Array<number> | null;
    /**
     * 
     * @type {Date}
     * @memberof ListCourtPricingRulesResponse
     */
    startTime?: Date;
    /**
     * 
     * @type {Date}
     * @memberof ListCourtPricingRulesResponse
     */
    endTime?: Date;
    /**
     * 
     * @type {number}
     * @memberof ListCourtPricingRulesResponse
     */
    pricePerHour?: number;
}

/**
 * Check if a given object implements the ListCourtPricingRulesResponse interface.
 */
export function instanceOfListCourtPricingRulesResponse(value: object): value is ListCourtPricingRulesResponse {
    return true;
}

export function ListCourtPricingRulesResponseFromJSON(json: any): ListCourtPricingRulesResponse {
    return ListCourtPricingRulesResponseFromJSONTyped(json, false);
}

export function ListCourtPricingRulesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListCourtPricingRulesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'courtId': json['courtId'] == null ? undefined : json['courtId'],
        'daysOfWeek': json['daysOfWeek'] == null ? undefined : json['daysOfWeek'],
        'startTime': json['startTime'] == null ? undefined : (new Date(json['startTime'])),
        'endTime': json['endTime'] == null ? undefined : (new Date(json['endTime'])),
        'pricePerHour': json['pricePerHour'] == null ? undefined : json['pricePerHour'],
    };
}

export function ListCourtPricingRulesResponseToJSON(json: any): ListCourtPricingRulesResponse {
    return ListCourtPricingRulesResponseToJSONTyped(json, false);
}

export function ListCourtPricingRulesResponseToJSONTyped(value?: ListCourtPricingRulesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'courtId': value['courtId'],
        'daysOfWeek': value['daysOfWeek'],
        'startTime': value['startTime'] == null ? undefined : ((value['startTime']).toISOString()),
        'endTime': value['endTime'] == null ? undefined : ((value['endTime']).toISOString()),
        'pricePerHour': value['pricePerHour'],
    };
}

