/* tslint:disable */
/* eslint-disable */
/**
 * Badminton Court Management System API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ListReceiptResponse } from './ListReceiptResponse';
import {
    ListReceiptResponseFromJSON,
    ListReceiptResponseFromJSONTyped,
    ListReceiptResponseToJSON,
    ListReceiptResponseToJSONTyped,
} from './ListReceiptResponse';

/**
 * 
 * @export
 * @interface ListReceiptResponseListApiResponse
 */
export interface ListReceiptResponseListApiResponse {
    /**
     * 
     * @type {boolean}
     * @memberof ListReceiptResponseListApiResponse
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ListReceiptResponseListApiResponse
     */
    message?: string | null;
    /**
     * 
     * @type {Array<ListReceiptResponse>}
     * @memberof ListReceiptResponseListApiResponse
     */
    data?: Array<ListReceiptResponse> | null;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof ListReceiptResponseListApiResponse
     */
    errors?: { [key: string]: string; } | null;
}

/**
 * Check if a given object implements the ListReceiptResponseListApiResponse interface.
 */
export function instanceOfListReceiptResponseListApiResponse(value: object): value is ListReceiptResponseListApiResponse {
    return true;
}

export function ListReceiptResponseListApiResponseFromJSON(json: any): ListReceiptResponseListApiResponse {
    return ListReceiptResponseListApiResponseFromJSONTyped(json, false);
}

export function ListReceiptResponseListApiResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListReceiptResponseListApiResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(ListReceiptResponseFromJSON)),
        'errors': json['errors'] == null ? undefined : json['errors'],
    };
}

export function ListReceiptResponseListApiResponseToJSON(json: any): ListReceiptResponseListApiResponse {
    return ListReceiptResponseListApiResponseToJSONTyped(json, false);
}

export function ListReceiptResponseListApiResponseToJSONTyped(value?: ListReceiptResponseListApiResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'message': value['message'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(ListReceiptResponseToJSON)),
        'errors': value['errors'],
    };
}

