/* tslint:disable */
/* eslint-disable */
/**
 * Badminton Court Management System API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ListSliderResponse } from './ListSliderResponse';
import {
    ListSliderResponseFromJSON,
    ListSliderResponseFromJSONTyped,
    ListSliderResponseToJSON,
    ListSliderResponseToJSONTyped,
} from './ListSliderResponse';

/**
 * 
 * @export
 * @interface ListSliderResponseListApiResponse
 */
export interface ListSliderResponseListApiResponse {
    /**
     * 
     * @type {boolean}
     * @memberof ListSliderResponseListApiResponse
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ListSliderResponseListApiResponse
     */
    message?: string | null;
    /**
     * 
     * @type {Array<ListSliderResponse>}
     * @memberof ListSliderResponseListApiResponse
     */
    data?: Array<ListSliderResponse> | null;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof ListSliderResponseListApiResponse
     */
    errors?: { [key: string]: string; } | null;
}

/**
 * Check if a given object implements the ListSliderResponseListApiResponse interface.
 */
export function instanceOfListSliderResponseListApiResponse(value: object): value is ListSliderResponseListApiResponse {
    return true;
}

export function ListSliderResponseListApiResponseFromJSON(json: any): ListSliderResponseListApiResponse {
    return ListSliderResponseListApiResponseFromJSONTyped(json, false);
}

export function ListSliderResponseListApiResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListSliderResponseListApiResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(ListSliderResponseFromJSON)),
        'errors': json['errors'] == null ? undefined : json['errors'],
    };
}

export function ListSliderResponseListApiResponseToJSON(json: any): ListSliderResponseListApiResponse {
    return ListSliderResponseListApiResponseToJSONTyped(json, false);
}

export function ListSliderResponseListApiResponseToJSONTyped(value?: ListSliderResponseListApiResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'message': value['message'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(ListSliderResponseToJSON)),
        'errors': value['errors'],
    };
}

