/* tslint:disable */
/* eslint-disable */
/**
 * Badminton Court Management System API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ListUserBookingHistoryResponse } from './ListUserBookingHistoryResponse';
import {
    ListUserBookingHistoryResponseFromJSON,
    ListUserBookingHistoryResponseFromJSONTyped,
    ListUserBookingHistoryResponseToJSON,
    ListUserBookingHistoryResponseToJSONTyped,
} from './ListUserBookingHistoryResponse';

/**
 * 
 * @export
 * @interface ListUserBookingHistoryResponseListApiResponse
 */
export interface ListUserBookingHistoryResponseListApiResponse {
    /**
     * 
     * @type {boolean}
     * @memberof ListUserBookingHistoryResponseListApiResponse
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ListUserBookingHistoryResponseListApiResponse
     */
    message?: string | null;
    /**
     * 
     * @type {Array<ListUserBookingHistoryResponse>}
     * @memberof ListUserBookingHistoryResponseListApiResponse
     */
    data?: Array<ListUserBookingHistoryResponse> | null;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof ListUserBookingHistoryResponseListApiResponse
     */
    errors?: { [key: string]: string; } | null;
}

/**
 * Check if a given object implements the ListUserBookingHistoryResponseListApiResponse interface.
 */
export function instanceOfListUserBookingHistoryResponseListApiResponse(value: object): value is ListUserBookingHistoryResponseListApiResponse {
    return true;
}

export function ListUserBookingHistoryResponseListApiResponseFromJSON(json: any): ListUserBookingHistoryResponseListApiResponse {
    return ListUserBookingHistoryResponseListApiResponseFromJSONTyped(json, false);
}

export function ListUserBookingHistoryResponseListApiResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListUserBookingHistoryResponseListApiResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(ListUserBookingHistoryResponseFromJSON)),
        'errors': json['errors'] == null ? undefined : json['errors'],
    };
}

export function ListUserBookingHistoryResponseListApiResponseToJSON(json: any): ListUserBookingHistoryResponseListApiResponse {
    return ListUserBookingHistoryResponseListApiResponseToJSONTyped(json, false);
}

export function ListUserBookingHistoryResponseListApiResponseToJSONTyped(value?: ListUserBookingHistoryResponseListApiResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'message': value['message'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(ListUserBookingHistoryResponseToJSON)),
        'errors': value['errors'],
    };
}

