/* tslint:disable */
/* eslint-disable */
/**
 * Badminton Court Management System API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListProductsByPriceTableResponse
 */
export interface ListProductsByPriceTableResponse {
    /**
     * 
     * @type {number}
     * @memberof ListProductsByPriceTableResponse
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof ListProductsByPriceTableResponse
     */
    code?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ListProductsByPriceTableResponse
     */
    name: string | null;
    /**
     * 
     * @type {string}
     * @memberof ListProductsByPriceTableResponse
     */
    category?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ListProductsByPriceTableResponse
     */
    salePrice?: number;
    /**
     * 
     * @type {number}
     * @memberof ListProductsByPriceTableResponse
     */
    overrideSalePrice?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ListProductsByPriceTableResponse
     */
    finalPrice?: number;
    /**
     * 
     * @type {boolean}
     * @memberof ListProductsByPriceTableResponse
     */
    isActive?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof ListProductsByPriceTableResponse
     */
    images?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof ListProductsByPriceTableResponse
     */
    unit?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ListProductsByPriceTableResponse
     */
    stock?: number;
    /**
     * 
     * @type {boolean}
     * @memberof ListProductsByPriceTableResponse
     */
    isPriceOverridden?: boolean;
}

/**
 * Check if a given object implements the ListProductsByPriceTableResponse interface.
 */
export function instanceOfListProductsByPriceTableResponse(value: object): value is ListProductsByPriceTableResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function ListProductsByPriceTableResponseFromJSON(json: any): ListProductsByPriceTableResponse {
    return ListProductsByPriceTableResponseFromJSONTyped(json, false);
}

export function ListProductsByPriceTableResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListProductsByPriceTableResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'code': json['code'] == null ? undefined : json['code'],
        'name': json['name'],
        'category': json['category'] == null ? undefined : json['category'],
        'salePrice': json['salePrice'] == null ? undefined : json['salePrice'],
        'overrideSalePrice': json['overrideSalePrice'] == null ? undefined : json['overrideSalePrice'],
        'finalPrice': json['finalPrice'] == null ? undefined : json['finalPrice'],
        'isActive': json['isActive'] == null ? undefined : json['isActive'],
        'images': json['images'] == null ? undefined : json['images'],
        'unit': json['unit'] == null ? undefined : json['unit'],
        'stock': json['stock'] == null ? undefined : json['stock'],
        'isPriceOverridden': json['isPriceOverridden'] == null ? undefined : json['isPriceOverridden'],
    };
}

export function ListProductsByPriceTableResponseToJSON(json: any): ListProductsByPriceTableResponse {
    return ListProductsByPriceTableResponseToJSONTyped(json, false);
}

export function ListProductsByPriceTableResponseToJSONTyped(value?: ListProductsByPriceTableResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'code': value['code'],
        'name': value['name'],
        'category': value['category'],
        'salePrice': value['salePrice'],
        'overrideSalePrice': value['overrideSalePrice'],
        'finalPrice': value['finalPrice'],
        'isActive': value['isActive'],
        'images': value['images'],
        'unit': value['unit'],
        'stock': value['stock'],
        'isPriceOverridden': value['isPriceOverridden'],
    };
}

