/* tslint:disable */
/* eslint-disable */
/**
 * Badminton Court Management System API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListMembershipResponse
 */
export interface ListMembershipResponse {
    /**
     * 
     * @type {Date}
     * @memberof ListMembershipResponse
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof ListMembershipResponse
     */
    updatedAt?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof ListMembershipResponse
     */
    createdBy?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ListMembershipResponse
     */
    updatedBy?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ListMembershipResponse
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ListMembershipResponse
     */
    name?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ListMembershipResponse
     */
    price?: number;
    /**
     * 
     * @type {number}
     * @memberof ListMembershipResponse
     */
    discountPercent?: number;
    /**
     * 
     * @type {number}
     * @memberof ListMembershipResponse
     */
    durationDays?: number;
    /**
     * 
     * @type {string}
     * @memberof ListMembershipResponse
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ListMembershipResponse
     */
    status?: string | null;
}

/**
 * Check if a given object implements the ListMembershipResponse interface.
 */
export function instanceOfListMembershipResponse(value: object): value is ListMembershipResponse {
    return true;
}

export function ListMembershipResponseFromJSON(json: any): ListMembershipResponse {
    return ListMembershipResponseFromJSONTyped(json, false);
}

export function ListMembershipResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListMembershipResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
        'createdBy': json['createdBy'] == null ? undefined : json['createdBy'],
        'updatedBy': json['updatedBy'] == null ? undefined : json['updatedBy'],
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'price': json['price'] == null ? undefined : json['price'],
        'discountPercent': json['discountPercent'] == null ? undefined : json['discountPercent'],
        'durationDays': json['durationDays'] == null ? undefined : json['durationDays'],
        'description': json['description'] == null ? undefined : json['description'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function ListMembershipResponseToJSON(json: any): ListMembershipResponse {
    return ListMembershipResponseToJSONTyped(json, false);
}

export function ListMembershipResponseToJSONTyped(value?: ListMembershipResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'updatedAt': value['updatedAt'] === null ? null : ((value['updatedAt'] as any)?.toISOString()),
        'createdBy': value['createdBy'],
        'updatedBy': value['updatedBy'],
        'id': value['id'],
        'name': value['name'],
        'price': value['price'],
        'discountPercent': value['discountPercent'],
        'durationDays': value['durationDays'],
        'description': value['description'],
        'status': value['status'],
    };
}

