/* tslint:disable */
/* eslint-disable */
/**
 * Badminton Court Management System API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListBookingCourtResponse
 */
export interface ListBookingCourtResponse {
    /**
     * 
     * @type {string}
     * @memberof ListBookingCourtResponse
     */
    id?: string;
    /**
     * 
     * @type {number}
     * @memberof ListBookingCourtResponse
     */
    customerId?: number;
    /**
     * 
     * @type {string}
     * @memberof ListBookingCourtResponse
     */
    courtId?: string;
    /**
     * 
     * @type {Date}
     * @memberof ListBookingCourtResponse
     */
    startDate?: Date;
    /**
     * 
     * @type {Date}
     * @memberof ListBookingCourtResponse
     */
    endDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof ListBookingCourtResponse
     */
    startTime?: string;
    /**
     * 
     * @type {string}
     * @memberof ListBookingCourtResponse
     */
    endTime?: string;
    /**
     * 
     * @type {Array<number>}
     * @memberof ListBookingCourtResponse
     */
    daysOfWeek?: Array<number> | null;
    /**
     * 
     * @type {string}
     * @memberof ListBookingCourtResponse
     */
    status?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ListBookingCourtResponse
     */
    totalHours?: number;
}

/**
 * Check if a given object implements the ListBookingCourtResponse interface.
 */
export function instanceOfListBookingCourtResponse(value: object): value is ListBookingCourtResponse {
    return true;
}

export function ListBookingCourtResponseFromJSON(json: any): ListBookingCourtResponse {
    return ListBookingCourtResponseFromJSONTyped(json, false);
}

export function ListBookingCourtResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListBookingCourtResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'customerId': json['customerId'] == null ? undefined : json['customerId'],
        'courtId': json['courtId'] == null ? undefined : json['courtId'],
        'startDate': json['startDate'] == null ? undefined : (new Date(json['startDate'])),
        'endDate': json['endDate'] == null ? undefined : (new Date(json['endDate'])),
        'startTime': json['startTime'] == null ? undefined : json['startTime'],
        'endTime': json['endTime'] == null ? undefined : json['endTime'],
        'daysOfWeek': json['daysOfWeek'] == null ? undefined : json['daysOfWeek'],
        'status': json['status'] == null ? undefined : json['status'],
        'totalHours': json['totalHours'] == null ? undefined : json['totalHours'],
    };
}

export function ListBookingCourtResponseToJSON(json: any): ListBookingCourtResponse {
    return ListBookingCourtResponseToJSONTyped(json, false);
}

export function ListBookingCourtResponseToJSONTyped(value?: ListBookingCourtResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'customerId': value['customerId'],
        'courtId': value['courtId'],
        'startDate': value['startDate'] == null ? undefined : ((value['startDate']).toISOString().substring(0,10)),
        'endDate': value['endDate'] == null ? undefined : ((value['endDate']).toISOString().substring(0,10)),
        'startTime': value['startTime'],
        'endTime': value['endTime'],
        'daysOfWeek': value['daysOfWeek'],
        'status': value['status'],
        'totalHours': value['totalHours'],
    };
}

