/* tslint:disable */
/* eslint-disable */
/**
 * Badminton Court Management System API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListReturnGoodsResponse
 */
export interface ListReturnGoodsResponse {
    /**
     * 
     * @type {number}
     * @memberof ListReturnGoodsResponse
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ListReturnGoodsResponse
     */
    code?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof ListReturnGoodsResponse
     */
    returnTime?: Date;
    /**
     * 
     * @type {number}
     * @memberof ListReturnGoodsResponse
     */
    supplierId?: number;
    /**
     * 
     * @type {string}
     * @memberof ListReturnGoodsResponse
     */
    supplierName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ListReturnGoodsResponse
     */
    returnBy?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ListReturnGoodsResponse
     */
    totalValue?: number;
    /**
     * 
     * @type {number}
     * @memberof ListReturnGoodsResponse
     */
    discount?: number;
    /**
     * 
     * @type {number}
     * @memberof ListReturnGoodsResponse
     */
    supplierNeedToPay?: number;
    /**
     * 
     * @type {number}
     * @memberof ListReturnGoodsResponse
     */
    supplierPaid?: number;
    /**
     * 
     * @type {string}
     * @memberof ListReturnGoodsResponse
     */
    note?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ListReturnGoodsResponse
     */
    status?: number;
}

/**
 * Check if a given object implements the ListReturnGoodsResponse interface.
 */
export function instanceOfListReturnGoodsResponse(value: object): value is ListReturnGoodsResponse {
    return true;
}

export function ListReturnGoodsResponseFromJSON(json: any): ListReturnGoodsResponse {
    return ListReturnGoodsResponseFromJSONTyped(json, false);
}

export function ListReturnGoodsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListReturnGoodsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'code': json['code'] == null ? undefined : json['code'],
        'returnTime': json['returnTime'] == null ? undefined : (new Date(json['returnTime'])),
        'supplierId': json['supplierId'] == null ? undefined : json['supplierId'],
        'supplierName': json['supplierName'] == null ? undefined : json['supplierName'],
        'returnBy': json['returnBy'] == null ? undefined : json['returnBy'],
        'totalValue': json['totalValue'] == null ? undefined : json['totalValue'],
        'discount': json['discount'] == null ? undefined : json['discount'],
        'supplierNeedToPay': json['supplierNeedToPay'] == null ? undefined : json['supplierNeedToPay'],
        'supplierPaid': json['supplierPaid'] == null ? undefined : json['supplierPaid'],
        'note': json['note'] == null ? undefined : json['note'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function ListReturnGoodsResponseToJSON(json: any): ListReturnGoodsResponse {
    return ListReturnGoodsResponseToJSONTyped(json, false);
}

export function ListReturnGoodsResponseToJSONTyped(value?: ListReturnGoodsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'code': value['code'],
        'returnTime': value['returnTime'] == null ? undefined : ((value['returnTime']).toISOString()),
        'supplierId': value['supplierId'],
        'supplierName': value['supplierName'],
        'returnBy': value['returnBy'],
        'totalValue': value['totalValue'],
        'discount': value['discount'],
        'supplierNeedToPay': value['supplierNeedToPay'],
        'supplierPaid': value['supplierPaid'],
        'note': value['note'],
        'status': value['status'],
    };
}

