/* tslint:disable */
/* eslint-disable */
/**
 * Badminton Court Management System API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListUserMembershipRequest
 */
export interface ListUserMembershipRequest {
    /**
     * 
     * @type {number}
     * @memberof ListUserMembershipRequest
     */
    customerId?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ListUserMembershipRequest
     */
    membershipId?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof ListUserMembershipRequest
     */
    isActive?: boolean | null;
}

/**
 * Check if a given object implements the ListUserMembershipRequest interface.
 */
export function instanceOfListUserMembershipRequest(value: object): value is ListUserMembershipRequest {
    return true;
}

export function ListUserMembershipRequestFromJSON(json: any): ListUserMembershipRequest {
    return ListUserMembershipRequestFromJSONTyped(json, false);
}

export function ListUserMembershipRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListUserMembershipRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'customerId': json['customerId'] == null ? undefined : json['customerId'],
        'membershipId': json['membershipId'] == null ? undefined : json['membershipId'],
        'isActive': json['isActive'] == null ? undefined : json['isActive'],
    };
}

export function ListUserMembershipRequestToJSON(json: any): ListUserMembershipRequest {
    return ListUserMembershipRequestToJSONTyped(json, false);
}

export function ListUserMembershipRequestToJSONTyped(value?: ListUserMembershipRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'customerId': value['customerId'],
        'membershipId': value['membershipId'],
        'isActive': value['isActive'],
    };
}

