/* tslint:disable */
/* eslint-disable */
/**
 * Badminton Court Management System API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListPayrollRequest
 */
export interface ListPayrollRequest {
    /**
     * 
     * @type {string}
     * @memberof ListPayrollRequest
     */
    keyword?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ListPayrollRequest
     */
    status?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ListPayrollRequest
     */
    startDateOperator?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof ListPayrollRequest
     */
    startDate?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof ListPayrollRequest
     */
    endDateOperator?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof ListPayrollRequest
     */
    endDate?: Date | null;
}

/**
 * Check if a given object implements the ListPayrollRequest interface.
 */
export function instanceOfListPayrollRequest(value: object): value is ListPayrollRequest {
    return true;
}

export function ListPayrollRequestFromJSON(json: any): ListPayrollRequest {
    return ListPayrollRequestFromJSONTyped(json, false);
}

export function ListPayrollRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListPayrollRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'keyword': json['keyword'] == null ? undefined : json['keyword'],
        'status': json['status'] == null ? undefined : json['status'],
        'startDateOperator': json['startDateOperator'] == null ? undefined : json['startDateOperator'],
        'startDate': json['startDate'] == null ? undefined : (new Date(json['startDate'])),
        'endDateOperator': json['endDateOperator'] == null ? undefined : json['endDateOperator'],
        'endDate': json['endDate'] == null ? undefined : (new Date(json['endDate'])),
    };
}

export function ListPayrollRequestToJSON(json: any): ListPayrollRequest {
    return ListPayrollRequestToJSONTyped(json, false);
}

export function ListPayrollRequestToJSONTyped(value?: ListPayrollRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'keyword': value['keyword'],
        'status': value['status'],
        'startDateOperator': value['startDateOperator'],
        'startDate': value['startDate'] === null ? null : ((value['startDate'] as any)?.toISOString()),
        'endDateOperator': value['endDateOperator'],
        'endDate': value['endDate'] === null ? null : ((value['endDate'] as any)?.toISOString()),
    };
}

