/* tslint:disable */
/* eslint-disable */
/**
 * Badminton Court Management System API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListCourtPricingRuleByCourtIdResponse
 */
export interface ListCourtPricingRuleByCourtIdResponse {
    /**
     * 
     * @type {Date}
     * @memberof ListCourtPricingRuleByCourtIdResponse
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof ListCourtPricingRuleByCourtIdResponse
     */
    updatedAt?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof ListCourtPricingRuleByCourtIdResponse
     */
    createdBy?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ListCourtPricingRuleByCourtIdResponse
     */
    updatedBy?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ListCourtPricingRuleByCourtIdResponse
     */
    courtId: string;
    /**
     * 
     * @type {Array<number>}
     * @memberof ListCourtPricingRuleByCourtIdResponse
     */
    daysOfWeek: Array<number> | null;
    /**
     * 
     * @type {string}
     * @memberof ListCourtPricingRuleByCourtIdResponse
     */
    startTime: string;
    /**
     * 
     * @type {string}
     * @memberof ListCourtPricingRuleByCourtIdResponse
     */
    endTime: string;
    /**
     * 
     * @type {number}
     * @memberof ListCourtPricingRuleByCourtIdResponse
     */
    pricePerHour: number;
    /**
     * 
     * @type {number}
     * @memberof ListCourtPricingRuleByCourtIdResponse
     */
    order: number;
}

/**
 * Check if a given object implements the ListCourtPricingRuleByCourtIdResponse interface.
 */
export function instanceOfListCourtPricingRuleByCourtIdResponse(value: object): value is ListCourtPricingRuleByCourtIdResponse {
    if (!('courtId' in value) || value['courtId'] === undefined) return false;
    if (!('daysOfWeek' in value) || value['daysOfWeek'] === undefined) return false;
    if (!('startTime' in value) || value['startTime'] === undefined) return false;
    if (!('endTime' in value) || value['endTime'] === undefined) return false;
    if (!('pricePerHour' in value) || value['pricePerHour'] === undefined) return false;
    if (!('order' in value) || value['order'] === undefined) return false;
    return true;
}

export function ListCourtPricingRuleByCourtIdResponseFromJSON(json: any): ListCourtPricingRuleByCourtIdResponse {
    return ListCourtPricingRuleByCourtIdResponseFromJSONTyped(json, false);
}

export function ListCourtPricingRuleByCourtIdResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListCourtPricingRuleByCourtIdResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
        'createdBy': json['createdBy'] == null ? undefined : json['createdBy'],
        'updatedBy': json['updatedBy'] == null ? undefined : json['updatedBy'],
        'courtId': json['courtId'],
        'daysOfWeek': json['daysOfWeek'] == null ? null : json['daysOfWeek'],
        'startTime': json['startTime'],
        'endTime': json['endTime'],
        'pricePerHour': json['pricePerHour'],
        'order': json['order'],
    };
}

export function ListCourtPricingRuleByCourtIdResponseToJSON(json: any): ListCourtPricingRuleByCourtIdResponse {
    return ListCourtPricingRuleByCourtIdResponseToJSONTyped(json, false);
}

export function ListCourtPricingRuleByCourtIdResponseToJSONTyped(value?: ListCourtPricingRuleByCourtIdResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'updatedAt': value['updatedAt'] === null ? null : ((value['updatedAt'] as any)?.toISOString()),
        'createdBy': value['createdBy'],
        'updatedBy': value['updatedBy'],
        'courtId': value['courtId'],
        'daysOfWeek': value['daysOfWeek'],
        'startTime': value['startTime'],
        'endTime': value['endTime'],
        'pricePerHour': value['pricePerHour'],
        'order': value['order'],
    };
}

