/* tslint:disable */
/* eslint-disable */
/**
 * Badminton Court Management System API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MergeInventoryChecksRequest
 */
export interface MergeInventoryChecksRequest {
    /**
     * 
     * @type {Array<number>}
     * @memberof MergeInventoryChecksRequest
     */
    inventoryCheckIds: Array<number>;
}

/**
 * Check if a given object implements the MergeInventoryChecksRequest interface.
 */
export function instanceOfMergeInventoryChecksRequest(value: object): value is MergeInventoryChecksRequest {
    if (!('inventoryCheckIds' in value) || value['inventoryCheckIds'] === undefined) return false;
    return true;
}

export function MergeInventoryChecksRequestFromJSON(json: any): MergeInventoryChecksRequest {
    return MergeInventoryChecksRequestFromJSONTyped(json, false);
}

export function MergeInventoryChecksRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MergeInventoryChecksRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'inventoryCheckIds': json['inventoryCheckIds'],
    };
}

export function MergeInventoryChecksRequestToJSON(json: any): MergeInventoryChecksRequest {
    return MergeInventoryChecksRequestToJSONTyped(json, false);
}

export function MergeInventoryChecksRequestToJSONTyped(value?: MergeInventoryChecksRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'inventoryCheckIds': value['inventoryCheckIds'],
    };
}

