/* tslint:disable */
/* eslint-disable */
/**
 * Badminton Court Management System API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NotificationType } from './NotificationType';
import {
    NotificationTypeFromJSON,
    NotificationTypeFromJSONTyped,
    NotificationTypeToJSON,
    NotificationTypeToJSONTyped,
} from './NotificationType';
import type { NotificationCategory } from './NotificationCategory';
import {
    NotificationCategoryFromJSON,
    NotificationCategoryFromJSONTyped,
    NotificationCategoryToJSON,
    NotificationCategoryToJSONTyped,
} from './NotificationCategory';

/**
 * 
 * @export
 * @interface Notification
 */
export interface Notification {
    /**
     * 
     * @type {Date}
     * @memberof Notification
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Notification
     */
    updatedAt?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof Notification
     */
    createdBy?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Notification
     */
    updatedBy?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Notification
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof Notification
     */
    title: string | null;
    /**
     * 
     * @type {string}
     * @memberof Notification
     */
    message?: string | null;
    /**
     * 
     * @type {NotificationCategory}
     * @memberof Notification
     */
    notificationByType?: NotificationCategory;
    /**
     * 
     * @type {NotificationType}
     * @memberof Notification
     */
    type?: NotificationType;
    /**
     * 
     * @type {Array<string>}
     * @memberof Notification
     */
    userIds: Array<string> | null;
}



/**
 * Check if a given object implements the Notification interface.
 */
export function instanceOfNotification(value: object): value is Notification {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('userIds' in value) || value['userIds'] === undefined) return false;
    return true;
}

export function NotificationFromJSON(json: any): Notification {
    return NotificationFromJSONTyped(json, false);
}

export function NotificationFromJSONTyped(json: any, ignoreDiscriminator: boolean): Notification {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
        'createdBy': json['createdBy'] == null ? undefined : json['createdBy'],
        'updatedBy': json['updatedBy'] == null ? undefined : json['updatedBy'],
        'id': json['id'] == null ? undefined : json['id'],
        'title': json['title'],
        'message': json['message'] == null ? undefined : json['message'],
        'notificationByType': json['notificationByType'] == null ? undefined : NotificationCategoryFromJSON(json['notificationByType']),
        'type': json['type'] == null ? undefined : NotificationTypeFromJSON(json['type']),
        'userIds': json['userIds'] == null ? null : json['userIds'],
    };
}

export function NotificationToJSON(json: any): Notification {
    return NotificationToJSONTyped(json, false);
}

export function NotificationToJSONTyped(value?: Notification | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'updatedAt': value['updatedAt'] === null ? null : ((value['updatedAt'] as any)?.toISOString()),
        'createdBy': value['createdBy'],
        'updatedBy': value['updatedBy'],
        'id': value['id'],
        'title': value['title'],
        'message': value['message'],
        'notificationByType': NotificationCategoryToJSON(value['notificationByType']),
        'type': NotificationTypeToJSON(value['type']),
        'userIds': value['userIds'],
    };
}

