/* tslint:disable */
/* eslint-disable */
/**
 * Badminton Court Management System API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PaginationRequest
 */
export interface PaginationRequest {
    /**
     * 
     * @type {number}
     * @memberof PaginationRequest
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof PaginationRequest
     */
    pageSize?: number;
}

/**
 * Check if a given object implements the PaginationRequest interface.
 */
export function instanceOfPaginationRequest(value: object): value is PaginationRequest {
    return true;
}

export function PaginationRequestFromJSON(json: any): PaginationRequest {
    return PaginationRequestFromJSONTyped(json, false);
}

export function PaginationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'] == null ? undefined : json['page'],
        'pageSize': json['pageSize'] == null ? undefined : json['pageSize'],
    };
}

export function PaginationRequestToJSON(json: any): PaginationRequest {
    return PaginationRequestToJSONTyped(json, false);
}

export function PaginationRequestToJSONTyped(value?: PaginationRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'page': value['page'],
        'pageSize': value['pageSize'],
    };
}

