/* tslint:disable */
/* eslint-disable */
/**
 * Badminton Court Management System API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PriceTable } from './PriceTable';
import {
    PriceTableFromJSON,
    PriceTableFromJSONTyped,
    PriceTableToJSON,
    PriceTableToJSONTyped,
} from './PriceTable';

/**
 * 
 * @export
 * @interface PriceTimeRange
 */
export interface PriceTimeRange {
    /**
     * 
     * @type {number}
     * @memberof PriceTimeRange
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof PriceTimeRange
     */
    priceTableId?: number;
    /**
     * 
     * @type {PriceTable}
     * @memberof PriceTimeRange
     */
    priceTable?: PriceTable;
    /**
     * 
     * @type {string}
     * @memberof PriceTimeRange
     */
    startTime?: string;
    /**
     * 
     * @type {string}
     * @memberof PriceTimeRange
     */
    endTime?: string;
}

/**
 * Check if a given object implements the PriceTimeRange interface.
 */
export function instanceOfPriceTimeRange(value: object): value is PriceTimeRange {
    return true;
}

export function PriceTimeRangeFromJSON(json: any): PriceTimeRange {
    return PriceTimeRangeFromJSONTyped(json, false);
}

export function PriceTimeRangeFromJSONTyped(json: any, ignoreDiscriminator: boolean): PriceTimeRange {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'priceTableId': json['priceTableId'] == null ? undefined : json['priceTableId'],
        'priceTable': json['priceTable'] == null ? undefined : PriceTableFromJSON(json['priceTable']),
        'startTime': json['startTime'] == null ? undefined : json['startTime'],
        'endTime': json['endTime'] == null ? undefined : json['endTime'],
    };
}

export function PriceTimeRangeToJSON(json: any): PriceTimeRange {
    return PriceTimeRangeToJSONTyped(json, false);
}

export function PriceTimeRangeToJSONTyped(value?: PriceTimeRange | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'priceTableId': value['priceTableId'],
        'priceTable': PriceTableToJSON(value['priceTable']),
        'startTime': value['startTime'],
        'endTime': value['endTime'],
    };
}

