/* tslint:disable */
/* eslint-disable */
/**
 * Badminton Court Management System API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Court } from './Court';
import {
    CourtFromJSON,
    CourtFromJSONTyped,
    CourtToJSON,
    CourtToJSONTyped,
} from './Court';

/**
 * 
 * @export
 * @interface PriceUnit
 */
export interface PriceUnit {
    /**
     * 
     * @type {Date}
     * @memberof PriceUnit
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof PriceUnit
     */
    updatedAt?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof PriceUnit
     */
    createdBy?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PriceUnit
     */
    updatedBy?: string | null;
    /**
     * 
     * @type {number}
     * @memberof PriceUnit
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof PriceUnit
     */
    name: string | null;
    /**
     * 
     * @type {Array<Court>}
     * @memberof PriceUnit
     */
    courts?: Array<Court> | null;
}

/**
 * Check if a given object implements the PriceUnit interface.
 */
export function instanceOfPriceUnit(value: object): value is PriceUnit {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function PriceUnitFromJSON(json: any): PriceUnit {
    return PriceUnitFromJSONTyped(json, false);
}

export function PriceUnitFromJSONTyped(json: any, ignoreDiscriminator: boolean): PriceUnit {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
        'createdBy': json['createdBy'] == null ? undefined : json['createdBy'],
        'updatedBy': json['updatedBy'] == null ? undefined : json['updatedBy'],
        'id': json['id'],
        'name': json['name'],
        'courts': json['courts'] == null ? undefined : ((json['courts'] as Array<any>).map(CourtFromJSON)),
    };
}

export function PriceUnitToJSON(json: any): PriceUnit {
    return PriceUnitToJSONTyped(json, false);
}

export function PriceUnitToJSONTyped(value?: PriceUnit | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'updatedAt': value['updatedAt'] === null ? null : ((value['updatedAt'] as any)?.toISOString()),
        'createdBy': value['createdBy'],
        'updatedBy': value['updatedBy'],
        'id': value['id'],
        'name': value['name'],
        'courts': value['courts'] == null ? undefined : ((value['courts'] as Array<any>).map(CourtToJSON)),
    };
}

