/* tslint:disable */
/* eslint-disable */
/**
 * Badminton Court Management System API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { QrPaymentResponse } from './QrPaymentResponse';
import {
    QrPaymentResponseFromJSON,
    QrPaymentResponseFromJSONTyped,
    QrPaymentResponseToJSON,
    QrPaymentResponseToJSONTyped,
} from './QrPaymentResponse';

/**
 * 
 * @export
 * @interface QrPaymentResponseApiResponse
 */
export interface QrPaymentResponseApiResponse {
    /**
     * 
     * @type {boolean}
     * @memberof QrPaymentResponseApiResponse
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof QrPaymentResponseApiResponse
     */
    message?: string | null;
    /**
     * 
     * @type {QrPaymentResponse}
     * @memberof QrPaymentResponseApiResponse
     */
    data?: QrPaymentResponse;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof QrPaymentResponseApiResponse
     */
    errors?: { [key: string]: string; } | null;
}

/**
 * Check if a given object implements the QrPaymentResponseApiResponse interface.
 */
export function instanceOfQrPaymentResponseApiResponse(value: object): value is QrPaymentResponseApiResponse {
    return true;
}

export function QrPaymentResponseApiResponseFromJSON(json: any): QrPaymentResponseApiResponse {
    return QrPaymentResponseApiResponseFromJSONTyped(json, false);
}

export function QrPaymentResponseApiResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): QrPaymentResponseApiResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : QrPaymentResponseFromJSON(json['data']),
        'errors': json['errors'] == null ? undefined : json['errors'],
    };
}

export function QrPaymentResponseApiResponseToJSON(json: any): QrPaymentResponseApiResponse {
    return QrPaymentResponseApiResponseToJSONTyped(json, false);
}

export function QrPaymentResponseApiResponseToJSONTyped(value?: QrPaymentResponseApiResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'message': value['message'],
        'data': QrPaymentResponseToJSON(value['data']),
        'errors': value['errors'],
    };
}

