/* tslint:disable */
/* eslint-disable */
/**
 * Badminton Court Management System API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RelatedPerson
 */
export interface RelatedPerson {
    /**
     * 
     * @type {Date}
     * @memberof RelatedPerson
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof RelatedPerson
     */
    updatedAt?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof RelatedPerson
     */
    createdBy?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RelatedPerson
     */
    updatedBy?: string | null;
    /**
     * 
     * @type {number}
     * @memberof RelatedPerson
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof RelatedPerson
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof RelatedPerson
     */
    phone?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RelatedPerson
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RelatedPerson
     */
    address?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RelatedPerson
     */
    company?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RelatedPerson
     */
    note?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof RelatedPerson
     */
    isActive?: boolean;
}

/**
 * Check if a given object implements the RelatedPerson interface.
 */
export function instanceOfRelatedPerson(value: object): value is RelatedPerson {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function RelatedPersonFromJSON(json: any): RelatedPerson {
    return RelatedPersonFromJSONTyped(json, false);
}

export function RelatedPersonFromJSONTyped(json: any, ignoreDiscriminator: boolean): RelatedPerson {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
        'createdBy': json['createdBy'] == null ? undefined : json['createdBy'],
        'updatedBy': json['updatedBy'] == null ? undefined : json['updatedBy'],
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'email': json['email'] == null ? undefined : json['email'],
        'address': json['address'] == null ? undefined : json['address'],
        'company': json['company'] == null ? undefined : json['company'],
        'note': json['note'] == null ? undefined : json['note'],
        'isActive': json['isActive'] == null ? undefined : json['isActive'],
    };
}

export function RelatedPersonToJSON(json: any): RelatedPerson {
    return RelatedPersonToJSONTyped(json, false);
}

export function RelatedPersonToJSONTyped(value?: RelatedPerson | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'updatedAt': value['updatedAt'] === null ? null : ((value['updatedAt'] as any)?.toISOString()),
        'createdBy': value['createdBy'],
        'updatedBy': value['updatedBy'],
        'id': value['id'],
        'name': value['name'],
        'phone': value['phone'],
        'email': value['email'],
        'address': value['address'],
        'company': value['company'],
        'note': value['note'],
        'isActive': value['isActive'],
    };
}

