/* tslint:disable */
/* eslint-disable */
/**
 * Badminton Court Management System API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RemoveBookingServiceRequest
 */
export interface RemoveBookingServiceRequest {
    /**
     * 
     * @type {string}
     * @memberof RemoveBookingServiceRequest
     */
    bookingCourtOccurrenceId: string;
}

/**
 * Check if a given object implements the RemoveBookingServiceRequest interface.
 */
export function instanceOfRemoveBookingServiceRequest(value: object): value is RemoveBookingServiceRequest {
    if (!('bookingCourtOccurrenceId' in value) || value['bookingCourtOccurrenceId'] === undefined) return false;
    return true;
}

export function RemoveBookingServiceRequestFromJSON(json: any): RemoveBookingServiceRequest {
    return RemoveBookingServiceRequestFromJSONTyped(json, false);
}

export function RemoveBookingServiceRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RemoveBookingServiceRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'bookingCourtOccurrenceId': json['bookingCourtOccurrenceId'],
    };
}

export function RemoveBookingServiceRequestToJSON(json: any): RemoveBookingServiceRequest {
    return RemoveBookingServiceRequestToJSONTyped(json, false);
}

export function RemoveBookingServiceRequestToJSONTyped(value?: RemoveBookingServiceRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bookingCourtOccurrenceId': value['bookingCourtOccurrenceId'],
    };
}

