/* tslint:disable */
/* eslint-disable */
/**
 * Badminton Court Management System API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResendVerifyEmailRequest
 */
export interface ResendVerifyEmailRequest {
    /**
     * 
     * @type {string}
     * @memberof ResendVerifyEmailRequest
     */
    email: string | null;
}

/**
 * Check if a given object implements the ResendVerifyEmailRequest interface.
 */
export function instanceOfResendVerifyEmailRequest(value: object): value is ResendVerifyEmailRequest {
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function ResendVerifyEmailRequestFromJSON(json: any): ResendVerifyEmailRequest {
    return ResendVerifyEmailRequestFromJSONTyped(json, false);
}

export function ResendVerifyEmailRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResendVerifyEmailRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
    };
}

export function ResendVerifyEmailRequestToJSON(json: any): ResendVerifyEmailRequest {
    return ResendVerifyEmailRequestToJSONTyped(json, false);
}

export function ResendVerifyEmailRequestToJSONTyped(value?: ResendVerifyEmailRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
    };
}

