/* tslint:disable */
/* eslint-disable */
/**
 * Badminton Court Management System API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SePayWebhookRequest
 */
export interface SePayWebhookRequest {
    /**
     * 
     * @type {number}
     * @memberof SePayWebhookRequest
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof SePayWebhookRequest
     */
    gateway?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SePayWebhookRequest
     */
    transactionDate?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SePayWebhookRequest
     */
    accountNumber?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SePayWebhookRequest
     */
    code?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SePayWebhookRequest
     */
    content?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SePayWebhookRequest
     */
    transferType?: string | null;
    /**
     * 
     * @type {number}
     * @memberof SePayWebhookRequest
     */
    transferAmount?: number;
    /**
     * 
     * @type {number}
     * @memberof SePayWebhookRequest
     */
    accumulated?: number;
    /**
     * 
     * @type {string}
     * @memberof SePayWebhookRequest
     */
    subAccount?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SePayWebhookRequest
     */
    referenceCode?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SePayWebhookRequest
     */
    description?: string | null;
}

/**
 * Check if a given object implements the SePayWebhookRequest interface.
 */
export function instanceOfSePayWebhookRequest(value: object): value is SePayWebhookRequest {
    return true;
}

export function SePayWebhookRequestFromJSON(json: any): SePayWebhookRequest {
    return SePayWebhookRequestFromJSONTyped(json, false);
}

export function SePayWebhookRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SePayWebhookRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'gateway': json['gateway'] == null ? undefined : json['gateway'],
        'transactionDate': json['transactionDate'] == null ? undefined : json['transactionDate'],
        'accountNumber': json['accountNumber'] == null ? undefined : json['accountNumber'],
        'code': json['code'] == null ? undefined : json['code'],
        'content': json['content'] == null ? undefined : json['content'],
        'transferType': json['transferType'] == null ? undefined : json['transferType'],
        'transferAmount': json['transferAmount'] == null ? undefined : json['transferAmount'],
        'accumulated': json['accumulated'] == null ? undefined : json['accumulated'],
        'subAccount': json['subAccount'] == null ? undefined : json['subAccount'],
        'referenceCode': json['referenceCode'] == null ? undefined : json['referenceCode'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function SePayWebhookRequestToJSON(json: any): SePayWebhookRequest {
    return SePayWebhookRequestToJSONTyped(json, false);
}

export function SePayWebhookRequestToJSONTyped(value?: SePayWebhookRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'gateway': value['gateway'],
        'transactionDate': value['transactionDate'],
        'accountNumber': value['accountNumber'],
        'code': value['code'],
        'content': value['content'],
        'transferType': value['transferType'],
        'transferAmount': value['transferAmount'],
        'accumulated': value['accumulated'],
        'subAccount': value['subAccount'],
        'referenceCode': value['referenceCode'],
        'description': value['description'],
    };
}

