/* tslint:disable */
/* eslint-disable */
/**
 * Badminton Court Management System API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ShiftResponse } from './ShiftResponse';
import {
    ShiftResponseFromJSON,
    ShiftResponseFromJSONTyped,
    ShiftResponseToJSON,
    ShiftResponseToJSONTyped,
} from './ShiftResponse';

/**
 * 
 * @export
 * @interface ShiftResponseApiResponse
 */
export interface ShiftResponseApiResponse {
    /**
     * 
     * @type {boolean}
     * @memberof ShiftResponseApiResponse
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ShiftResponseApiResponse
     */
    message?: string | null;
    /**
     * 
     * @type {ShiftResponse}
     * @memberof ShiftResponseApiResponse
     */
    data?: ShiftResponse;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof ShiftResponseApiResponse
     */
    errors?: { [key: string]: string; } | null;
}

/**
 * Check if a given object implements the ShiftResponseApiResponse interface.
 */
export function instanceOfShiftResponseApiResponse(value: object): value is ShiftResponseApiResponse {
    return true;
}

export function ShiftResponseApiResponseFromJSON(json: any): ShiftResponseApiResponse {
    return ShiftResponseApiResponseFromJSONTyped(json, false);
}

export function ShiftResponseApiResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShiftResponseApiResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : ShiftResponseFromJSON(json['data']),
        'errors': json['errors'] == null ? undefined : json['errors'],
    };
}

export function ShiftResponseApiResponseToJSON(json: any): ShiftResponseApiResponse {
    return ShiftResponseApiResponseToJSONTyped(json, false);
}

export function ShiftResponseApiResponseToJSONTyped(value?: ShiftResponseApiResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'message': value['message'],
        'data': ShiftResponseToJSON(value['data']),
        'errors': value['errors'],
    };
}

