/* tslint:disable */
/* eslint-disable */
/**
 * Badminton Court Management System API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StaffRequest
 */
export interface StaffRequest {
    /**
     * 
     * @type {string}
     * @memberof StaffRequest
     */
    fullName: string;
    /**
     * 
     * @type {string}
     * @memberof StaffRequest
     */
    identificationNumber?: string | null;
    /**
     * 
     * @type {number}
     * @memberof StaffRequest
     */
    departmentId?: number | null;
    /**
     * 
     * @type {number}
     * @memberof StaffRequest
     */
    branchId?: number | null;
    /**
     * 
     * @type {Date}
     * @memberof StaffRequest
     */
    dateOfBirth?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof StaffRequest
     */
    dateOfJoining?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof StaffRequest
     */
    address?: string | null;
    /**
     * 
     * @type {string}
     * @memberof StaffRequest
     */
    phoneNumber?: string | null;
    /**
     * 
     * @type {string}
     * @memberof StaffRequest
     */
    avatarUrl?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof StaffRequest
     */
    isActive?: boolean;
    /**
     * 
     * @type {string}
     * @memberof StaffRequest
     */
    salarySettings: string;
    /**
     * 
     * @type {string}
     * @memberof StaffRequest
     */
    accountId?: string | null;
}

/**
 * Check if a given object implements the StaffRequest interface.
 */
export function instanceOfStaffRequest(value: object): value is StaffRequest {
    if (!('fullName' in value) || value['fullName'] === undefined) return false;
    if (!('salarySettings' in value) || value['salarySettings'] === undefined) return false;
    return true;
}

export function StaffRequestFromJSON(json: any): StaffRequest {
    return StaffRequestFromJSONTyped(json, false);
}

export function StaffRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): StaffRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'fullName': json['fullName'],
        'identificationNumber': json['identificationNumber'] == null ? undefined : json['identificationNumber'],
        'departmentId': json['departmentId'] == null ? undefined : json['departmentId'],
        'branchId': json['branchId'] == null ? undefined : json['branchId'],
        'dateOfBirth': json['dateOfBirth'] == null ? undefined : (new Date(json['dateOfBirth'])),
        'dateOfJoining': json['dateOfJoining'] == null ? undefined : (new Date(json['dateOfJoining'])),
        'address': json['address'] == null ? undefined : json['address'],
        'phoneNumber': json['phoneNumber'] == null ? undefined : json['phoneNumber'],
        'avatarUrl': json['avatarUrl'] == null ? undefined : json['avatarUrl'],
        'isActive': json['isActive'] == null ? undefined : json['isActive'],
        'salarySettings': json['salarySettings'],
        'accountId': json['accountId'] == null ? undefined : json['accountId'],
    };
}

export function StaffRequestToJSON(json: any): StaffRequest {
    return StaffRequestToJSONTyped(json, false);
}

export function StaffRequestToJSONTyped(value?: StaffRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'fullName': value['fullName'],
        'identificationNumber': value['identificationNumber'],
        'departmentId': value['departmentId'],
        'branchId': value['branchId'],
        'dateOfBirth': value['dateOfBirth'] === null ? null : ((value['dateOfBirth'] as any)?.toISOString()),
        'dateOfJoining': value['dateOfJoining'] === null ? null : ((value['dateOfJoining'] as any)?.toISOString()),
        'address': value['address'],
        'phoneNumber': value['phoneNumber'],
        'avatarUrl': value['avatarUrl'],
        'isActive': value['isActive'],
        'salarySettings': value['salarySettings'],
        'accountId': value['accountId'],
    };
}

