/* tslint:disable */
/* eslint-disable */
/**
 * Badminton Court Management System API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Product } from './Product';
import {
    ProductFromJSON,
    ProductFromJSONTyped,
    ProductToJSON,
    ProductToJSONTyped,
} from './Product';
import type { StockOut } from './StockOut';
import {
    StockOutFromJSON,
    StockOutFromJSONTyped,
    StockOutToJSON,
    StockOutToJSONTyped,
} from './StockOut';

/**
 * 
 * @export
 * @interface StockOutItem
 */
export interface StockOutItem {
    /**
     * 
     * @type {number}
     * @memberof StockOutItem
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof StockOutItem
     */
    stockOutId?: number;
    /**
     * 
     * @type {number}
     * @memberof StockOutItem
     */
    productId?: number;
    /**
     * 
     * @type {number}
     * @memberof StockOutItem
     */
    quantity?: number;
    /**
     * 
     * @type {number}
     * @memberof StockOutItem
     */
    costPrice?: number;
    /**
     * 
     * @type {string}
     * @memberof StockOutItem
     */
    note?: string | null;
    /**
     * 
     * @type {StockOut}
     * @memberof StockOutItem
     */
    stockOut?: StockOut;
    /**
     * 
     * @type {Product}
     * @memberof StockOutItem
     */
    product?: Product;
}

/**
 * Check if a given object implements the StockOutItem interface.
 */
export function instanceOfStockOutItem(value: object): value is StockOutItem {
    return true;
}

export function StockOutItemFromJSON(json: any): StockOutItem {
    return StockOutItemFromJSONTyped(json, false);
}

export function StockOutItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): StockOutItem {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'stockOutId': json['stockOutId'] == null ? undefined : json['stockOutId'],
        'productId': json['productId'] == null ? undefined : json['productId'],
        'quantity': json['quantity'] == null ? undefined : json['quantity'],
        'costPrice': json['costPrice'] == null ? undefined : json['costPrice'],
        'note': json['note'] == null ? undefined : json['note'],
        'stockOut': json['stockOut'] == null ? undefined : StockOutFromJSON(json['stockOut']),
        'product': json['product'] == null ? undefined : ProductFromJSON(json['product']),
    };
}

export function StockOutItemToJSON(json: any): StockOutItem {
    return StockOutItemToJSONTyped(json, false);
}

export function StockOutItemToJSONTyped(value?: StockOutItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'stockOutId': value['stockOutId'],
        'productId': value['productId'],
        'quantity': value['quantity'],
        'costPrice': value['costPrice'],
        'note': value['note'],
        'stockOut': StockOutToJSON(value['stockOut']),
        'product': ProductToJSON(value['product']),
    };
}

