/* tslint:disable */
/* eslint-disable */
/**
 * Badminton Court Management System API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StockOutItem } from './StockOutItem';
import {
    StockOutItemFromJSON,
    StockOutItemFromJSONTyped,
    StockOutItemToJSON,
    StockOutItemToJSONTyped,
} from './StockOutItem';
import type { StockOutStatus } from './StockOutStatus';
import {
    StockOutStatusFromJSON,
    StockOutStatusFromJSONTyped,
    StockOutStatusToJSON,
    StockOutStatusToJSONTyped,
} from './StockOutStatus';
import type { Supplier } from './Supplier';
import {
    SupplierFromJSON,
    SupplierFromJSONTyped,
    SupplierToJSON,
    SupplierToJSONTyped,
} from './Supplier';

/**
 * 
 * @export
 * @interface StockOut
 */
export interface StockOut {
    /**
     * 
     * @type {number}
     * @memberof StockOut
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof StockOut
     */
    code: string;
    /**
     * 
     * @type {Date}
     * @memberof StockOut
     */
    outTime?: Date;
    /**
     * 
     * @type {number}
     * @memberof StockOut
     */
    supplierId?: number;
    /**
     * 
     * @type {Supplier}
     * @memberof StockOut
     */
    supplier?: Supplier;
    /**
     * 
     * @type {string}
     * @memberof StockOut
     */
    outBy?: string | null;
    /**
     * 
     * @type {string}
     * @memberof StockOut
     */
    createdBy?: string | null;
    /**
     * 
     * @type {string}
     * @memberof StockOut
     */
    note?: string | null;
    /**
     * 
     * @type {number}
     * @memberof StockOut
     */
    totalValue?: number;
    /**
     * 
     * @type {StockOutStatus}
     * @memberof StockOut
     */
    status?: StockOutStatus;
    /**
     * 
     * @type {Date}
     * @memberof StockOut
     */
    createdAt?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof StockOut
     */
    updatedAt?: Date | null;
    /**
     * 
     * @type {Array<StockOutItem>}
     * @memberof StockOut
     */
    items?: Array<StockOutItem> | null;
}



/**
 * Check if a given object implements the StockOut interface.
 */
export function instanceOfStockOut(value: object): value is StockOut {
    if (!('code' in value) || value['code'] === undefined) return false;
    return true;
}

export function StockOutFromJSON(json: any): StockOut {
    return StockOutFromJSONTyped(json, false);
}

export function StockOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): StockOut {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'code': json['code'],
        'outTime': json['outTime'] == null ? undefined : (new Date(json['outTime'])),
        'supplierId': json['supplierId'] == null ? undefined : json['supplierId'],
        'supplier': json['supplier'] == null ? undefined : SupplierFromJSON(json['supplier']),
        'outBy': json['outBy'] == null ? undefined : json['outBy'],
        'createdBy': json['createdBy'] == null ? undefined : json['createdBy'],
        'note': json['note'] == null ? undefined : json['note'],
        'totalValue': json['totalValue'] == null ? undefined : json['totalValue'],
        'status': json['status'] == null ? undefined : StockOutStatusFromJSON(json['status']),
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(StockOutItemFromJSON)),
    };
}

export function StockOutToJSON(json: any): StockOut {
    return StockOutToJSONTyped(json, false);
}

export function StockOutToJSONTyped(value?: StockOut | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'code': value['code'],
        'outTime': value['outTime'] == null ? undefined : ((value['outTime']).toISOString()),
        'supplierId': value['supplierId'],
        'supplier': SupplierToJSON(value['supplier']),
        'outBy': value['outBy'],
        'createdBy': value['createdBy'],
        'note': value['note'],
        'totalValue': value['totalValue'],
        'status': StockOutStatusToJSON(value['status']),
        'createdAt': value['createdAt'] === null ? null : ((value['createdAt'] as any)?.toISOString()),
        'updatedAt': value['updatedAt'] === null ? null : ((value['updatedAt'] as any)?.toISOString()),
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(StockOutItemToJSON)),
    };
}

