/* tslint:disable */
/* eslint-disable */
/**
 * Badminton Court Management System API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SystemConfigResponse } from './SystemConfigResponse';
import {
    SystemConfigResponseFromJSON,
    SystemConfigResponseFromJSONTyped,
    SystemConfigResponseToJSON,
    SystemConfigResponseToJSONTyped,
} from './SystemConfigResponse';

/**
 * 
 * @export
 * @interface SystemConfigResponseListApiResponse
 */
export interface SystemConfigResponseListApiResponse {
    /**
     * 
     * @type {boolean}
     * @memberof SystemConfigResponseListApiResponse
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof SystemConfigResponseListApiResponse
     */
    message?: string | null;
    /**
     * 
     * @type {Array<SystemConfigResponse>}
     * @memberof SystemConfigResponseListApiResponse
     */
    data?: Array<SystemConfigResponse> | null;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof SystemConfigResponseListApiResponse
     */
    errors?: { [key: string]: string; } | null;
}

/**
 * Check if a given object implements the SystemConfigResponseListApiResponse interface.
 */
export function instanceOfSystemConfigResponseListApiResponse(value: object): value is SystemConfigResponseListApiResponse {
    return true;
}

export function SystemConfigResponseListApiResponseFromJSON(json: any): SystemConfigResponseListApiResponse {
    return SystemConfigResponseListApiResponseFromJSONTyped(json, false);
}

export function SystemConfigResponseListApiResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SystemConfigResponseListApiResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(SystemConfigResponseFromJSON)),
        'errors': json['errors'] == null ? undefined : json['errors'],
    };
}

export function SystemConfigResponseListApiResponseToJSON(json: any): SystemConfigResponseListApiResponse {
    return SystemConfigResponseListApiResponseToJSONTyped(json, false);
}

export function SystemConfigResponseListApiResponseToJSONTyped(value?: SystemConfigResponseListApiResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'message': value['message'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(SystemConfigResponseToJSON)),
        'errors': value['errors'],
    };
}

