/* tslint:disable */
/* eslint-disable */
/**
 * Badminton Court Management System API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SystemConfigResponse } from './SystemConfigResponse';
import {
    SystemConfigResponseFromJSON,
    SystemConfigResponseFromJSONTyped,
    SystemConfigResponseToJSON,
    SystemConfigResponseToJSONTyped,
} from './SystemConfigResponse';

/**
 * 
 * @export
 * @interface SystemConfigResponseApiResponse
 */
export interface SystemConfigResponseApiResponse {
    /**
     * 
     * @type {boolean}
     * @memberof SystemConfigResponseApiResponse
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof SystemConfigResponseApiResponse
     */
    message?: string | null;
    /**
     * 
     * @type {SystemConfigResponse}
     * @memberof SystemConfigResponseApiResponse
     */
    data?: SystemConfigResponse;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof SystemConfigResponseApiResponse
     */
    errors?: { [key: string]: string; } | null;
}

/**
 * Check if a given object implements the SystemConfigResponseApiResponse interface.
 */
export function instanceOfSystemConfigResponseApiResponse(value: object): value is SystemConfigResponseApiResponse {
    return true;
}

export function SystemConfigResponseApiResponseFromJSON(json: any): SystemConfigResponseApiResponse {
    return SystemConfigResponseApiResponseFromJSONTyped(json, false);
}

export function SystemConfigResponseApiResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SystemConfigResponseApiResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : SystemConfigResponseFromJSON(json['data']),
        'errors': json['errors'] == null ? undefined : json['errors'],
    };
}

export function SystemConfigResponseApiResponseToJSON(json: any): SystemConfigResponseApiResponse {
    return SystemConfigResponseApiResponseToJSONTyped(json, false);
}

export function SystemConfigResponseApiResponseToJSONTyped(value?: SystemConfigResponseApiResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'message': value['message'],
        'data': SystemConfigResponseToJSON(value['data']),
        'errors': value['errors'],
    };
}

