/* tslint:disable */
/* eslint-disable */
/**
 * Badminton Court Management System API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateServicePricingRuleRequest
 */
export interface UpdateServicePricingRuleRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateServicePricingRuleRequest
     */
    serviceId: string;
    /**
     * 
     * @type {number}
     * @memberof UpdateServicePricingRuleRequest
     */
    pricePerHour: number;
}

/**
 * Check if a given object implements the UpdateServicePricingRuleRequest interface.
 */
export function instanceOfUpdateServicePricingRuleRequest(value: object): value is UpdateServicePricingRuleRequest {
    if (!('serviceId' in value) || value['serviceId'] === undefined) return false;
    if (!('pricePerHour' in value) || value['pricePerHour'] === undefined) return false;
    return true;
}

export function UpdateServicePricingRuleRequestFromJSON(json: any): UpdateServicePricingRuleRequest {
    return UpdateServicePricingRuleRequestFromJSONTyped(json, false);
}

export function UpdateServicePricingRuleRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateServicePricingRuleRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'serviceId': json['serviceId'],
        'pricePerHour': json['pricePerHour'],
    };
}

export function UpdateServicePricingRuleRequestToJSON(json: any): UpdateServicePricingRuleRequest {
    return UpdateServicePricingRuleRequestToJSONTyped(json, false);
}

export function UpdateServicePricingRuleRequestToJSONTyped(value?: UpdateServicePricingRuleRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'serviceId': value['serviceId'],
        'pricePerHour': value['pricePerHour'],
    };
}

