/* tslint:disable */
/* eslint-disable */
/**
 * Badminton Court Management System API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdatePriceTableProductRequest
 */
export interface UpdatePriceTableProductRequest {
    /**
     * 
     * @type {number}
     * @memberof UpdatePriceTableProductRequest
     */
    priceTableId: number;
    /**
     * 
     * @type {number}
     * @memberof UpdatePriceTableProductRequest
     */
    productId: number;
    /**
     * 
     * @type {number}
     * @memberof UpdatePriceTableProductRequest
     */
    overrideSalePrice?: number | null;
}

/**
 * Check if a given object implements the UpdatePriceTableProductRequest interface.
 */
export function instanceOfUpdatePriceTableProductRequest(value: object): value is UpdatePriceTableProductRequest {
    if (!('priceTableId' in value) || value['priceTableId'] === undefined) return false;
    if (!('productId' in value) || value['productId'] === undefined) return false;
    return true;
}

export function UpdatePriceTableProductRequestFromJSON(json: any): UpdatePriceTableProductRequest {
    return UpdatePriceTableProductRequestFromJSONTyped(json, false);
}

export function UpdatePriceTableProductRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdatePriceTableProductRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'priceTableId': json['priceTableId'],
        'productId': json['productId'],
        'overrideSalePrice': json['overrideSalePrice'] == null ? undefined : json['overrideSalePrice'],
    };
}

export function UpdatePriceTableProductRequestToJSON(json: any): UpdatePriceTableProductRequest {
    return UpdatePriceTableProductRequestToJSONTyped(json, false);
}

export function UpdatePriceTableProductRequestToJSONTyped(value?: UpdatePriceTableProductRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'priceTableId': value['priceTableId'],
        'productId': value['productId'],
        'overrideSalePrice': value['overrideSalePrice'],
    };
}

