/* tslint:disable */
/* eslint-disable */
/**
 * Badminton Court Management System API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PriceTimeRangeDto } from './PriceTimeRangeDto';
import {
    PriceTimeRangeDtoFromJSON,
    PriceTimeRangeDtoFromJSONTyped,
    PriceTimeRangeDtoToJSON,
    PriceTimeRangeDtoToJSONTyped,
} from './PriceTimeRangeDto';

/**
 * 
 * @export
 * @interface UpdatePriceTableRequest
 */
export interface UpdatePriceTableRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdatePriceTableRequest
     */
    name: string;
    /**
     * 
     * @type {Date}
     * @memberof UpdatePriceTableRequest
     */
    effectiveFrom?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof UpdatePriceTableRequest
     */
    effectiveTo?: Date | null;
    /**
     * 
     * @type {Array<number>}
     * @memberof UpdatePriceTableRequest
     */
    months?: Array<number> | null;
    /**
     * 
     * @type {Array<number>}
     * @memberof UpdatePriceTableRequest
     */
    daysOfMonth?: Array<number> | null;
    /**
     * 
     * @type {Array<number>}
     * @memberof UpdatePriceTableRequest
     */
    weekdays?: Array<number> | null;
    /**
     * 
     * @type {boolean}
     * @memberof UpdatePriceTableRequest
     */
    isActive?: boolean;
    /**
     * 
     * @type {Array<PriceTimeRangeDto>}
     * @memberof UpdatePriceTableRequest
     */
    timeRanges?: Array<PriceTimeRangeDto> | null;
    /**
     * 
     * @type {number}
     * @memberof UpdatePriceTableRequest
     */
    id: number;
}

/**
 * Check if a given object implements the UpdatePriceTableRequest interface.
 */
export function instanceOfUpdatePriceTableRequest(value: object): value is UpdatePriceTableRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function UpdatePriceTableRequestFromJSON(json: any): UpdatePriceTableRequest {
    return UpdatePriceTableRequestFromJSONTyped(json, false);
}

export function UpdatePriceTableRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdatePriceTableRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'effectiveFrom': json['effectiveFrom'] == null ? undefined : (new Date(json['effectiveFrom'])),
        'effectiveTo': json['effectiveTo'] == null ? undefined : (new Date(json['effectiveTo'])),
        'months': json['months'] == null ? undefined : json['months'],
        'daysOfMonth': json['daysOfMonth'] == null ? undefined : json['daysOfMonth'],
        'weekdays': json['weekdays'] == null ? undefined : json['weekdays'],
        'isActive': json['isActive'] == null ? undefined : json['isActive'],
        'timeRanges': json['timeRanges'] == null ? undefined : ((json['timeRanges'] as Array<any>).map(PriceTimeRangeDtoFromJSON)),
        'id': json['id'],
    };
}

export function UpdatePriceTableRequestToJSON(json: any): UpdatePriceTableRequest {
    return UpdatePriceTableRequestToJSONTyped(json, false);
}

export function UpdatePriceTableRequestToJSONTyped(value?: UpdatePriceTableRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'effectiveFrom': value['effectiveFrom'] === null ? null : ((value['effectiveFrom'] as any)?.toISOString()),
        'effectiveTo': value['effectiveTo'] === null ? null : ((value['effectiveTo'] as any)?.toISOString()),
        'months': value['months'],
        'daysOfMonth': value['daysOfMonth'],
        'weekdays': value['weekdays'],
        'isActive': value['isActive'],
        'timeRanges': value['timeRanges'] == null ? undefined : ((value['timeRanges'] as Array<any>).map(PriceTimeRangeDtoToJSON)),
        'id': value['id'],
    };
}

