/* tslint:disable */
/* eslint-disable */
/**
 * Badminton Court Management System API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateFeedbackRequest
 */
export interface UpdateFeedbackRequest {
    /**
     * 
     * @type {number}
     * @memberof UpdateFeedbackRequest
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof UpdateFeedbackRequest
     */
    rating?: number | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateFeedbackRequest
     */
    comment?: string | null;
    /**
     * 
     * @type {number}
     * @memberof UpdateFeedbackRequest
     */
    courtQuality?: number | null;
    /**
     * 
     * @type {number}
     * @memberof UpdateFeedbackRequest
     */
    staffService?: number | null;
    /**
     * 
     * @type {number}
     * @memberof UpdateFeedbackRequest
     */
    cleanliness?: number | null;
    /**
     * 
     * @type {number}
     * @memberof UpdateFeedbackRequest
     */
    lighting?: number | null;
    /**
     * 
     * @type {number}
     * @memberof UpdateFeedbackRequest
     */
    valueForMoney?: number | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof UpdateFeedbackRequest
     */
    mediaUrl?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateFeedbackRequest
     */
    adminReply?: string | null;
}

/**
 * Check if a given object implements the UpdateFeedbackRequest interface.
 */
export function instanceOfUpdateFeedbackRequest(value: object): value is UpdateFeedbackRequest {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function UpdateFeedbackRequestFromJSON(json: any): UpdateFeedbackRequest {
    return UpdateFeedbackRequestFromJSONTyped(json, false);
}

export function UpdateFeedbackRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateFeedbackRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'rating': json['rating'] == null ? undefined : json['rating'],
        'comment': json['comment'] == null ? undefined : json['comment'],
        'courtQuality': json['courtQuality'] == null ? undefined : json['courtQuality'],
        'staffService': json['staffService'] == null ? undefined : json['staffService'],
        'cleanliness': json['cleanliness'] == null ? undefined : json['cleanliness'],
        'lighting': json['lighting'] == null ? undefined : json['lighting'],
        'valueForMoney': json['valueForMoney'] == null ? undefined : json['valueForMoney'],
        'mediaUrl': json['mediaUrl'] == null ? undefined : json['mediaUrl'],
        'adminReply': json['adminReply'] == null ? undefined : json['adminReply'],
    };
}

export function UpdateFeedbackRequestToJSON(json: any): UpdateFeedbackRequest {
    return UpdateFeedbackRequestToJSONTyped(json, false);
}

export function UpdateFeedbackRequestToJSONTyped(value?: UpdateFeedbackRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'rating': value['rating'],
        'comment': value['comment'],
        'courtQuality': value['courtQuality'],
        'staffService': value['staffService'],
        'cleanliness': value['cleanliness'],
        'lighting': value['lighting'],
        'valueForMoney': value['valueForMoney'],
        'mediaUrl': value['mediaUrl'],
        'adminReply': value['adminReply'],
    };
}

