/* tslint:disable */
/* eslint-disable */
/**
 * Badminton Court Management System API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UploadFileResponse
 */
export interface UploadFileResponse {
    /**
     * 
     * @type {string}
     * @memberof UploadFileResponse
     */
    publicUrl: string | null;
    /**
     * 
     * @type {string}
     * @memberof UploadFileResponse
     */
    fileName: string | null;
}

/**
 * Check if a given object implements the UploadFileResponse interface.
 */
export function instanceOfUploadFileResponse(value: object): value is UploadFileResponse {
    if (!('publicUrl' in value) || value['publicUrl'] === undefined) return false;
    if (!('fileName' in value) || value['fileName'] === undefined) return false;
    return true;
}

export function UploadFileResponseFromJSON(json: any): UploadFileResponse {
    return UploadFileResponseFromJSONTyped(json, false);
}

export function UploadFileResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UploadFileResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'publicUrl': json['publicUrl'],
        'fileName': json['fileName'],
    };
}

export function UploadFileResponseToJSON(json: any): UploadFileResponse {
    return UploadFileResponseToJSONTyped(json, false);
}

export function UploadFileResponseToJSONTyped(value?: UploadFileResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'publicUrl': value['publicUrl'],
        'fileName': value['fileName'],
    };
}

