/* tslint:disable */
/* eslint-disable */
/**
 * Badminton Court Management System API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UploadFileResponse } from './UploadFileResponse';
import {
    UploadFileResponseFromJSON,
    UploadFileResponseFromJSONTyped,
    UploadFileResponseToJSON,
    UploadFileResponseToJSONTyped,
} from './UploadFileResponse';

/**
 * 
 * @export
 * @interface UploadFileResponseApiResponse
 */
export interface UploadFileResponseApiResponse {
    /**
     * 
     * @type {boolean}
     * @memberof UploadFileResponseApiResponse
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof UploadFileResponseApiResponse
     */
    message?: string | null;
    /**
     * 
     * @type {UploadFileResponse}
     * @memberof UploadFileResponseApiResponse
     */
    data?: UploadFileResponse;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof UploadFileResponseApiResponse
     */
    errors?: { [key: string]: string; } | null;
}

/**
 * Check if a given object implements the UploadFileResponseApiResponse interface.
 */
export function instanceOfUploadFileResponseApiResponse(value: object): value is UploadFileResponseApiResponse {
    return true;
}

export function UploadFileResponseApiResponseFromJSON(json: any): UploadFileResponseApiResponse {
    return UploadFileResponseApiResponseFromJSONTyped(json, false);
}

export function UploadFileResponseApiResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UploadFileResponseApiResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : UploadFileResponseFromJSON(json['data']),
        'errors': json['errors'] == null ? undefined : json['errors'],
    };
}

export function UploadFileResponseApiResponseToJSON(json: any): UploadFileResponseApiResponse {
    return UploadFileResponseApiResponseToJSONTyped(json, false);
}

export function UploadFileResponseApiResponseToJSONTyped(value?: UploadFileResponseApiResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'message': value['message'],
        'data': UploadFileResponseToJSON(value['data']),
        'errors': value['errors'],
    };
}

