/* tslint:disable */
/* eslint-disable */
/**
 * Badminton Court Management System API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { VoucherResponse } from './VoucherResponse';
import {
    VoucherResponseFromJSON,
    VoucherResponseFromJSONTyped,
    VoucherResponseToJSON,
    VoucherResponseToJSONTyped,
} from './VoucherResponse';

/**
 * 
 * @export
 * @interface ValidateVoucherResponse
 */
export interface ValidateVoucherResponse {
    /**
     * 
     * @type {boolean}
     * @memberof ValidateVoucherResponse
     */
    isValid?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ValidateVoucherResponse
     */
    errorMessage?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ValidateVoucherResponse
     */
    discountAmount?: number;
    /**
     * 
     * @type {number}
     * @memberof ValidateVoucherResponse
     */
    finalAmount?: number;
    /**
     * 
     * @type {VoucherResponse}
     * @memberof ValidateVoucherResponse
     */
    voucher?: VoucherResponse;
}

/**
 * Check if a given object implements the ValidateVoucherResponse interface.
 */
export function instanceOfValidateVoucherResponse(value: object): value is ValidateVoucherResponse {
    return true;
}

export function ValidateVoucherResponseFromJSON(json: any): ValidateVoucherResponse {
    return ValidateVoucherResponseFromJSONTyped(json, false);
}

export function ValidateVoucherResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ValidateVoucherResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'isValid': json['isValid'] == null ? undefined : json['isValid'],
        'errorMessage': json['errorMessage'] == null ? undefined : json['errorMessage'],
        'discountAmount': json['discountAmount'] == null ? undefined : json['discountAmount'],
        'finalAmount': json['finalAmount'] == null ? undefined : json['finalAmount'],
        'voucher': json['voucher'] == null ? undefined : VoucherResponseFromJSON(json['voucher']),
    };
}

export function ValidateVoucherResponseToJSON(json: any): ValidateVoucherResponse {
    return ValidateVoucherResponseToJSONTyped(json, false);
}

export function ValidateVoucherResponseToJSONTyped(value?: ValidateVoucherResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'isValid': value['isValid'],
        'errorMessage': value['errorMessage'],
        'discountAmount': value['discountAmount'],
        'finalAmount': value['finalAmount'],
        'voucher': VoucherResponseToJSON(value['voucher']),
    };
}

