/* tslint:disable */
/* eslint-disable */
/**
 * Badminton Court Management System API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { VoucherUserRuleDto } from './VoucherUserRuleDto';
import {
    VoucherUserRuleDtoFromJSON,
    VoucherUserRuleDtoFromJSONTyped,
    VoucherUserRuleDtoToJSON,
    VoucherUserRuleDtoToJSONTyped,
} from './VoucherUserRuleDto';
import type { VoucherTimeRuleDto } from './VoucherTimeRuleDto';
import {
    VoucherTimeRuleDtoFromJSON,
    VoucherTimeRuleDtoFromJSONTyped,
    VoucherTimeRuleDtoToJSON,
    VoucherTimeRuleDtoToJSONTyped,
} from './VoucherTimeRuleDto';

/**
 * 
 * @export
 * @interface VoucherResponse
 */
export interface VoucherResponse {
    /**
     * 
     * @type {number}
     * @memberof VoucherResponse
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof VoucherResponse
     */
    code?: string | null;
    /**
     * 
     * @type {string}
     * @memberof VoucherResponse
     */
    title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof VoucherResponse
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof VoucherResponse
     */
    discountType?: string | null;
    /**
     * 
     * @type {number}
     * @memberof VoucherResponse
     */
    discountValue?: number;
    /**
     * 
     * @type {number}
     * @memberof VoucherResponse
     */
    discountPercentage?: number | null;
    /**
     * 
     * @type {number}
     * @memberof VoucherResponse
     */
    maxDiscountValue?: number | null;
    /**
     * 
     * @type {number}
     * @memberof VoucherResponse
     */
    minOrderValue?: number | null;
    /**
     * 
     * @type {Date}
     * @memberof VoucherResponse
     */
    startAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof VoucherResponse
     */
    endAt?: Date;
    /**
     * 
     * @type {number}
     * @memberof VoucherResponse
     */
    usageLimitTotal?: number;
    /**
     * 
     * @type {number}
     * @memberof VoucherResponse
     */
    usageLimitPerUser?: number;
    /**
     * 
     * @type {number}
     * @memberof VoucherResponse
     */
    usedCount?: number;
    /**
     * 
     * @type {boolean}
     * @memberof VoucherResponse
     */
    isActive?: boolean;
    /**
     * 
     * @type {Array<VoucherTimeRuleDto>}
     * @memberof VoucherResponse
     */
    timeRules?: Array<VoucherTimeRuleDto> | null;
    /**
     * 
     * @type {Array<VoucherUserRuleDto>}
     * @memberof VoucherResponse
     */
    userRules?: Array<VoucherUserRuleDto> | null;
}

/**
 * Check if a given object implements the VoucherResponse interface.
 */
export function instanceOfVoucherResponse(value: object): value is VoucherResponse {
    return true;
}

export function VoucherResponseFromJSON(json: any): VoucherResponse {
    return VoucherResponseFromJSONTyped(json, false);
}

export function VoucherResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): VoucherResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'code': json['code'] == null ? undefined : json['code'],
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'discountType': json['discountType'] == null ? undefined : json['discountType'],
        'discountValue': json['discountValue'] == null ? undefined : json['discountValue'],
        'discountPercentage': json['discountPercentage'] == null ? undefined : json['discountPercentage'],
        'maxDiscountValue': json['maxDiscountValue'] == null ? undefined : json['maxDiscountValue'],
        'minOrderValue': json['minOrderValue'] == null ? undefined : json['minOrderValue'],
        'startAt': json['startAt'] == null ? undefined : (new Date(json['startAt'])),
        'endAt': json['endAt'] == null ? undefined : (new Date(json['endAt'])),
        'usageLimitTotal': json['usageLimitTotal'] == null ? undefined : json['usageLimitTotal'],
        'usageLimitPerUser': json['usageLimitPerUser'] == null ? undefined : json['usageLimitPerUser'],
        'usedCount': json['usedCount'] == null ? undefined : json['usedCount'],
        'isActive': json['isActive'] == null ? undefined : json['isActive'],
        'timeRules': json['timeRules'] == null ? undefined : ((json['timeRules'] as Array<any>).map(VoucherTimeRuleDtoFromJSON)),
        'userRules': json['userRules'] == null ? undefined : ((json['userRules'] as Array<any>).map(VoucherUserRuleDtoFromJSON)),
    };
}

export function VoucherResponseToJSON(json: any): VoucherResponse {
    return VoucherResponseToJSONTyped(json, false);
}

export function VoucherResponseToJSONTyped(value?: VoucherResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'code': value['code'],
        'title': value['title'],
        'description': value['description'],
        'discountType': value['discountType'],
        'discountValue': value['discountValue'],
        'discountPercentage': value['discountPercentage'],
        'maxDiscountValue': value['maxDiscountValue'],
        'minOrderValue': value['minOrderValue'],
        'startAt': value['startAt'] == null ? undefined : ((value['startAt']).toISOString()),
        'endAt': value['endAt'] == null ? undefined : ((value['endAt']).toISOString()),
        'usageLimitTotal': value['usageLimitTotal'],
        'usageLimitPerUser': value['usageLimitPerUser'],
        'usedCount': value['usedCount'],
        'isActive': value['isActive'],
        'timeRules': value['timeRules'] == null ? undefined : ((value['timeRules'] as Array<any>).map(VoucherTimeRuleDtoToJSON)),
        'userRules': value['userRules'] == null ? undefined : ((value['userRules'] as Array<any>).map(VoucherUserRuleDtoToJSON)),
    };
}

