/* tslint:disable */
/* eslint-disable */
/**
 * Badminton Court Management System API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CurrentUserResponseApiResponse,
  ForgotPasswordRequest,
  LoginRequest,
  MyProfileResponseApiResponse,
  ObjectApiResponse,
  RegisterRequest,
  ResendVerifyEmailRequest,
  UpdateMyProfileRequest,
  UpdatePasswordRequest,
  ValidateForgotPasswordRequest,
  VerifyEmailRequest,
} from '../models/index';
import {
    CurrentUserResponseApiResponseFromJSON,
    CurrentUserResponseApiResponseToJSON,
    ForgotPasswordRequestFromJSON,
    ForgotPasswordRequestToJSON,
    LoginRequestFromJSON,
    LoginRequestToJSON,
    MyProfileResponseApiResponseFromJSON,
    MyProfileResponseApiResponseToJSON,
    ObjectApiResponseFromJSON,
    ObjectApiResponseToJSON,
    RegisterRequestFromJSON,
    RegisterRequestToJSON,
    ResendVerifyEmailRequestFromJSON,
    ResendVerifyEmailRequestToJSON,
    UpdateMyProfileRequestFromJSON,
    UpdateMyProfileRequestToJSON,
    UpdatePasswordRequestFromJSON,
    UpdatePasswordRequestToJSON,
    ValidateForgotPasswordRequestFromJSON,
    ValidateForgotPasswordRequestToJSON,
    VerifyEmailRequestFromJSON,
    VerifyEmailRequestToJSON,
} from '../models/index';

export interface ApiAuthForgotPasswordPostRequest {
    forgotPasswordRequest?: ForgotPasswordRequest;
}

export interface ApiAuthLoginPostRequest {
    loginRequest?: LoginRequest;
}

export interface ApiAuthResendVerifyEmailPostRequest {
    resendVerifyEmailRequest?: ResendVerifyEmailRequest;
}

export interface ApiAuthSignUpPostRequest {
    registerRequest?: RegisterRequest;
}

export interface ApiAuthUpdateMyProfilePutRequest {
    updateMyProfileRequest?: UpdateMyProfileRequest;
}

export interface ApiAuthUpdatePasswordPutRequest {
    updatePasswordRequest?: UpdatePasswordRequest;
}

export interface ApiAuthValidateForgotPasswordPostRequest {
    validateForgotPasswordRequest?: ValidateForgotPasswordRequest;
}

export interface ApiAuthVerifyEmailPostRequest {
    verifyEmailRequest?: VerifyEmailRequest;
}

/**
 * AuthApi - interface
 * 
 * @export
 * @interface AuthApiInterface
 */
export interface AuthApiInterface {
    /**
     * 
     * @param {ForgotPasswordRequest} [forgotPasswordRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApiInterface
     */
    apiAuthForgotPasswordPostRaw(requestParameters: ApiAuthForgotPasswordPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ObjectApiResponse>>;

    /**
     */
    apiAuthForgotPasswordPost(requestParameters: ApiAuthForgotPasswordPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ObjectApiResponse>;

    /**
     * 
     * @param {LoginRequest} [loginRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApiInterface
     */
    apiAuthLoginPostRaw(requestParameters: ApiAuthLoginPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CurrentUserResponseApiResponse>>;

    /**
     */
    apiAuthLoginPost(requestParameters: ApiAuthLoginPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CurrentUserResponseApiResponse>;

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApiInterface
     */
    apiAuthLogoutGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ObjectApiResponse>>;

    /**
     */
    apiAuthLogoutGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ObjectApiResponse>;

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApiInterface
     */
    apiAuthMeGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CurrentUserResponseApiResponse>>;

    /**
     */
    apiAuthMeGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CurrentUserResponseApiResponse>;

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApiInterface
     */
    apiAuthMyProfileGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MyProfileResponseApiResponse>>;

    /**
     */
    apiAuthMyProfileGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MyProfileResponseApiResponse>;

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApiInterface
     */
    apiAuthRefreshTokenPostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ObjectApiResponse>>;

    /**
     */
    apiAuthRefreshTokenPost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ObjectApiResponse>;

    /**
     * 
     * @param {ResendVerifyEmailRequest} [resendVerifyEmailRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApiInterface
     */
    apiAuthResendVerifyEmailPostRaw(requestParameters: ApiAuthResendVerifyEmailPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ObjectApiResponse>>;

    /**
     */
    apiAuthResendVerifyEmailPost(requestParameters: ApiAuthResendVerifyEmailPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ObjectApiResponse>;

    /**
     * 
     * @param {RegisterRequest} [registerRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApiInterface
     */
    apiAuthSignUpPostRaw(requestParameters: ApiAuthSignUpPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CurrentUserResponseApiResponse>>;

    /**
     */
    apiAuthSignUpPost(requestParameters: ApiAuthSignUpPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CurrentUserResponseApiResponse>;

    /**
     * 
     * @param {UpdateMyProfileRequest} [updateMyProfileRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApiInterface
     */
    apiAuthUpdateMyProfilePutRaw(requestParameters: ApiAuthUpdateMyProfilePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ObjectApiResponse>>;

    /**
     */
    apiAuthUpdateMyProfilePut(requestParameters: ApiAuthUpdateMyProfilePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ObjectApiResponse>;

    /**
     * 
     * @param {UpdatePasswordRequest} [updatePasswordRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApiInterface
     */
    apiAuthUpdatePasswordPutRaw(requestParameters: ApiAuthUpdatePasswordPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ObjectApiResponse>>;

    /**
     */
    apiAuthUpdatePasswordPut(requestParameters: ApiAuthUpdatePasswordPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ObjectApiResponse>;

    /**
     * 
     * @param {ValidateForgotPasswordRequest} [validateForgotPasswordRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApiInterface
     */
    apiAuthValidateForgotPasswordPostRaw(requestParameters: ApiAuthValidateForgotPasswordPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ObjectApiResponse>>;

    /**
     */
    apiAuthValidateForgotPasswordPost(requestParameters: ApiAuthValidateForgotPasswordPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ObjectApiResponse>;

    /**
     * 
     * @param {VerifyEmailRequest} [verifyEmailRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApiInterface
     */
    apiAuthVerifyEmailPostRaw(requestParameters: ApiAuthVerifyEmailPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ObjectApiResponse>>;

    /**
     */
    apiAuthVerifyEmailPost(requestParameters: ApiAuthVerifyEmailPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ObjectApiResponse>;

}

/**
 * 
 */
export class AuthApi extends runtime.BaseAPI implements AuthApiInterface {

    /**
     */
    async apiAuthForgotPasswordPostRaw(requestParameters: ApiAuthForgotPasswordPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ObjectApiResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/Auth/forgot-password`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ForgotPasswordRequestToJSON(requestParameters['forgotPasswordRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ObjectApiResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiAuthForgotPasswordPost(requestParameters: ApiAuthForgotPasswordPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ObjectApiResponse> {
        const response = await this.apiAuthForgotPasswordPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiAuthLoginPostRaw(requestParameters: ApiAuthLoginPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CurrentUserResponseApiResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/Auth/login`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LoginRequestToJSON(requestParameters['loginRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CurrentUserResponseApiResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiAuthLoginPost(requestParameters: ApiAuthLoginPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CurrentUserResponseApiResponse> {
        const response = await this.apiAuthLoginPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiAuthLogoutGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ObjectApiResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/Auth/logout`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ObjectApiResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiAuthLogoutGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ObjectApiResponse> {
        const response = await this.apiAuthLogoutGetRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async apiAuthMeGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CurrentUserResponseApiResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/Auth/me`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CurrentUserResponseApiResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiAuthMeGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CurrentUserResponseApiResponse> {
        const response = await this.apiAuthMeGetRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async apiAuthMyProfileGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MyProfileResponseApiResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/Auth/my-profile`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MyProfileResponseApiResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiAuthMyProfileGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MyProfileResponseApiResponse> {
        const response = await this.apiAuthMyProfileGetRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async apiAuthRefreshTokenPostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ObjectApiResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/Auth/refresh-token`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ObjectApiResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiAuthRefreshTokenPost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ObjectApiResponse> {
        const response = await this.apiAuthRefreshTokenPostRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async apiAuthResendVerifyEmailPostRaw(requestParameters: ApiAuthResendVerifyEmailPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ObjectApiResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/Auth/resend-verify-email`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ResendVerifyEmailRequestToJSON(requestParameters['resendVerifyEmailRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ObjectApiResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiAuthResendVerifyEmailPost(requestParameters: ApiAuthResendVerifyEmailPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ObjectApiResponse> {
        const response = await this.apiAuthResendVerifyEmailPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiAuthSignUpPostRaw(requestParameters: ApiAuthSignUpPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CurrentUserResponseApiResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/Auth/sign-up`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RegisterRequestToJSON(requestParameters['registerRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CurrentUserResponseApiResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiAuthSignUpPost(requestParameters: ApiAuthSignUpPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CurrentUserResponseApiResponse> {
        const response = await this.apiAuthSignUpPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiAuthUpdateMyProfilePutRaw(requestParameters: ApiAuthUpdateMyProfilePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ObjectApiResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/Auth/update-my-profile`;

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateMyProfileRequestToJSON(requestParameters['updateMyProfileRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ObjectApiResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiAuthUpdateMyProfilePut(requestParameters: ApiAuthUpdateMyProfilePutRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ObjectApiResponse> {
        const response = await this.apiAuthUpdateMyProfilePutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiAuthUpdatePasswordPutRaw(requestParameters: ApiAuthUpdatePasswordPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ObjectApiResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/Auth/update-password`;

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdatePasswordRequestToJSON(requestParameters['updatePasswordRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ObjectApiResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiAuthUpdatePasswordPut(requestParameters: ApiAuthUpdatePasswordPutRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ObjectApiResponse> {
        const response = await this.apiAuthUpdatePasswordPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiAuthValidateForgotPasswordPostRaw(requestParameters: ApiAuthValidateForgotPasswordPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ObjectApiResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/Auth/validate-forgot-password`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ValidateForgotPasswordRequestToJSON(requestParameters['validateForgotPasswordRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ObjectApiResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiAuthValidateForgotPasswordPost(requestParameters: ApiAuthValidateForgotPasswordPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ObjectApiResponse> {
        const response = await this.apiAuthValidateForgotPasswordPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiAuthVerifyEmailPostRaw(requestParameters: ApiAuthVerifyEmailPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ObjectApiResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/Auth/verify-email`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: VerifyEmailRequestToJSON(requestParameters['verifyEmailRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ObjectApiResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiAuthVerifyEmailPost(requestParameters: ApiAuthVerifyEmailPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ObjectApiResponse> {
        const response = await this.apiAuthVerifyEmailPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
