/* tslint:disable */
/* eslint-disable */
/**
 * Badminton Court Management System API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BooleanApiResponse,
  ChangeCustomerStatusRequest,
  CreateCustomerRequest,
  DeleteCustomerRequest,
  DetailCustomerResponseApiResponse,
  ListCustomerResponseListApiResponse,
  ListCustomerResponsePagedResponseApiResponse,
  UpdateCustomerRequest,
} from '../models/index';
import {
    BooleanApiResponseFromJSON,
    BooleanApiResponseToJSON,
    ChangeCustomerStatusRequestFromJSON,
    ChangeCustomerStatusRequestToJSON,
    CreateCustomerRequestFromJSON,
    CreateCustomerRequestToJSON,
    DeleteCustomerRequestFromJSON,
    DeleteCustomerRequestToJSON,
    DetailCustomerResponseApiResponseFromJSON,
    DetailCustomerResponseApiResponseToJSON,
    ListCustomerResponseListApiResponseFromJSON,
    ListCustomerResponseListApiResponseToJSON,
    ListCustomerResponsePagedResponseApiResponseFromJSON,
    ListCustomerResponsePagedResponseApiResponseToJSON,
    UpdateCustomerRequestFromJSON,
    UpdateCustomerRequestToJSON,
} from '../models/index';

export interface ApiCustomersChangeStatusPutRequest {
    changeCustomerStatusRequest?: ChangeCustomerStatusRequest;
}

export interface ApiCustomersCreatePostRequest {
    createCustomerRequest?: CreateCustomerRequest;
}

export interface ApiCustomersDeleteDeleteRequest {
    deleteCustomerRequest?: DeleteCustomerRequest;
}

export interface ApiCustomersDetailGetRequest {
    id: number;
}

export interface ApiCustomersListGetRequest {
    fullName?: string;
    phone?: string;
    gender?: string;
    address?: string;
    city?: string;
    district?: string;
    ward?: string;
    status?: string;
}

export interface ApiCustomersListPagedGetRequest {
    keyword?: string;
    page?: number;
    pageSize?: number;
}

export interface ApiCustomersUpdatePutRequest {
    updateCustomerRequest?: UpdateCustomerRequest;
}

/**
 * CustomersApi - interface
 * 
 * @export
 * @interface CustomersApiInterface
 */
export interface CustomersApiInterface {
    /**
     * 
     * @param {ChangeCustomerStatusRequest} [changeCustomerStatusRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CustomersApiInterface
     */
    apiCustomersChangeStatusPutRaw(requestParameters: ApiCustomersChangeStatusPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DetailCustomerResponseApiResponse>>;

    /**
     */
    apiCustomersChangeStatusPut(requestParameters: ApiCustomersChangeStatusPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DetailCustomerResponseApiResponse>;

    /**
     * 
     * @param {CreateCustomerRequest} [createCustomerRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CustomersApiInterface
     */
    apiCustomersCreatePostRaw(requestParameters: ApiCustomersCreatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DetailCustomerResponseApiResponse>>;

    /**
     */
    apiCustomersCreatePost(requestParameters: ApiCustomersCreatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DetailCustomerResponseApiResponse>;

    /**
     * 
     * @param {DeleteCustomerRequest} [deleteCustomerRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CustomersApiInterface
     */
    apiCustomersDeleteDeleteRaw(requestParameters: ApiCustomersDeleteDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BooleanApiResponse>>;

    /**
     */
    apiCustomersDeleteDelete(requestParameters: ApiCustomersDeleteDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BooleanApiResponse>;

    /**
     * 
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CustomersApiInterface
     */
    apiCustomersDetailGetRaw(requestParameters: ApiCustomersDetailGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DetailCustomerResponseApiResponse>>;

    /**
     */
    apiCustomersDetailGet(requestParameters: ApiCustomersDetailGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DetailCustomerResponseApiResponse>;

    /**
     * 
     * @param {string} [fullName] 
     * @param {string} [phone] 
     * @param {string} [gender] 
     * @param {string} [address] 
     * @param {string} [city] 
     * @param {string} [district] 
     * @param {string} [ward] 
     * @param {string} [status] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CustomersApiInterface
     */
    apiCustomersListGetRaw(requestParameters: ApiCustomersListGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListCustomerResponseListApiResponse>>;

    /**
     */
    apiCustomersListGet(requestParameters: ApiCustomersListGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListCustomerResponseListApiResponse>;

    /**
     * 
     * @param {string} [keyword] 
     * @param {number} [page] 
     * @param {number} [pageSize] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CustomersApiInterface
     */
    apiCustomersListPagedGetRaw(requestParameters: ApiCustomersListPagedGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListCustomerResponsePagedResponseApiResponse>>;

    /**
     */
    apiCustomersListPagedGet(requestParameters: ApiCustomersListPagedGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListCustomerResponsePagedResponseApiResponse>;

    /**
     * 
     * @param {UpdateCustomerRequest} [updateCustomerRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CustomersApiInterface
     */
    apiCustomersUpdatePutRaw(requestParameters: ApiCustomersUpdatePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DetailCustomerResponseApiResponse>>;

    /**
     */
    apiCustomersUpdatePut(requestParameters: ApiCustomersUpdatePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DetailCustomerResponseApiResponse>;

}

/**
 * 
 */
export class CustomersApi extends runtime.BaseAPI implements CustomersApiInterface {

    /**
     */
    async apiCustomersChangeStatusPutRaw(requestParameters: ApiCustomersChangeStatusPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DetailCustomerResponseApiResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/Customers/change-status`;

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ChangeCustomerStatusRequestToJSON(requestParameters['changeCustomerStatusRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DetailCustomerResponseApiResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiCustomersChangeStatusPut(requestParameters: ApiCustomersChangeStatusPutRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DetailCustomerResponseApiResponse> {
        const response = await this.apiCustomersChangeStatusPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiCustomersCreatePostRaw(requestParameters: ApiCustomersCreatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DetailCustomerResponseApiResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/Customers/create`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateCustomerRequestToJSON(requestParameters['createCustomerRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DetailCustomerResponseApiResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiCustomersCreatePost(requestParameters: ApiCustomersCreatePostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DetailCustomerResponseApiResponse> {
        const response = await this.apiCustomersCreatePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiCustomersDeleteDeleteRaw(requestParameters: ApiCustomersDeleteDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BooleanApiResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/Customers/delete`;

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
            body: DeleteCustomerRequestToJSON(requestParameters['deleteCustomerRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BooleanApiResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiCustomersDeleteDelete(requestParameters: ApiCustomersDeleteDeleteRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BooleanApiResponse> {
        const response = await this.apiCustomersDeleteDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiCustomersDetailGetRaw(requestParameters: ApiCustomersDetailGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DetailCustomerResponseApiResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiCustomersDetailGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['id'] != null) {
            queryParameters['Id'] = requestParameters['id'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/Customers/detail`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DetailCustomerResponseApiResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiCustomersDetailGet(requestParameters: ApiCustomersDetailGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DetailCustomerResponseApiResponse> {
        const response = await this.apiCustomersDetailGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiCustomersListGetRaw(requestParameters: ApiCustomersListGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListCustomerResponseListApiResponse>> {
        const queryParameters: any = {};

        if (requestParameters['fullName'] != null) {
            queryParameters['FullName'] = requestParameters['fullName'];
        }

        if (requestParameters['phone'] != null) {
            queryParameters['Phone'] = requestParameters['phone'];
        }

        if (requestParameters['gender'] != null) {
            queryParameters['Gender'] = requestParameters['gender'];
        }

        if (requestParameters['address'] != null) {
            queryParameters['Address'] = requestParameters['address'];
        }

        if (requestParameters['city'] != null) {
            queryParameters['City'] = requestParameters['city'];
        }

        if (requestParameters['district'] != null) {
            queryParameters['District'] = requestParameters['district'];
        }

        if (requestParameters['ward'] != null) {
            queryParameters['Ward'] = requestParameters['ward'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['Status'] = requestParameters['status'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/Customers/list`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListCustomerResponseListApiResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiCustomersListGet(requestParameters: ApiCustomersListGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListCustomerResponseListApiResponse> {
        const response = await this.apiCustomersListGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiCustomersListPagedGetRaw(requestParameters: ApiCustomersListPagedGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListCustomerResponsePagedResponseApiResponse>> {
        const queryParameters: any = {};

        if (requestParameters['keyword'] != null) {
            queryParameters['Keyword'] = requestParameters['keyword'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['Page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['PageSize'] = requestParameters['pageSize'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/Customers/list-paged`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListCustomerResponsePagedResponseApiResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiCustomersListPagedGet(requestParameters: ApiCustomersListPagedGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListCustomerResponsePagedResponseApiResponse> {
        const response = await this.apiCustomersListPagedGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiCustomersUpdatePutRaw(requestParameters: ApiCustomersUpdatePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DetailCustomerResponseApiResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/Customers/update`;

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateCustomerRequestToJSON(requestParameters['updateCustomerRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DetailCustomerResponseApiResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiCustomersUpdatePut(requestParameters: ApiCustomersUpdatePutRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DetailCustomerResponseApiResponse> {
        const response = await this.apiCustomersUpdatePutRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
