/* tslint:disable */
/* eslint-disable */
/**
 * Badminton Court Management System API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  EmailResponseApiResponse,
} from '../models/index';
import {
    EmailResponseApiResponseFromJSON,
    EmailResponseApiResponseToJSON,
} from '../models/index';

/**
 * EmailApi - interface
 * 
 * @export
 * @interface EmailApiInterface
 */
export interface EmailApiInterface {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EmailApiInterface
     */
    apiEmailTestConfigurationPostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EmailResponseApiResponse>>;

    /**
     */
    apiEmailTestConfigurationPost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EmailResponseApiResponse>;

}

/**
 * 
 */
export class EmailApi extends runtime.BaseAPI implements EmailApiInterface {

    /**
     */
    async apiEmailTestConfigurationPostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EmailResponseApiResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // Bearer authentication
        }


        let urlPath = `/api/Email/test-configuration`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EmailResponseApiResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiEmailTestConfigurationPost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EmailResponseApiResponse> {
        const response = await this.apiEmailTestConfigurationPostRaw(initOverrides);
        return await response.value();
    }

}
