/* tslint:disable */
/* eslint-disable */
/**
 * Badminton Court Management System API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BooleanApiResponse,
  CreateFeedbackRequest,
  DetailFeedbackResponseApiResponse,
  ListFeedbackResponseListApiResponse,
  UpdateFeedbackRequest,
} from '../models/index';
import {
    BooleanApiResponseFromJSON,
    BooleanApiResponseToJSON,
    CreateFeedbackRequestFromJSON,
    CreateFeedbackRequestToJSON,
    DetailFeedbackResponseApiResponseFromJSON,
    DetailFeedbackResponseApiResponseToJSON,
    ListFeedbackResponseListApiResponseFromJSON,
    ListFeedbackResponseListApiResponseToJSON,
    UpdateFeedbackRequestFromJSON,
    UpdateFeedbackRequestToJSON,
} from '../models/index';

export interface ApiFeedbacksCreatePostRequest {
    createFeedbackRequest?: CreateFeedbackRequest;
}

export interface ApiFeedbacksDeleteDeleteRequest {
    id: number;
}

export interface ApiFeedbacksDetailGetRequest {
    id: number;
}

export interface ApiFeedbacksListBookingCourtOccurrenceIdGetRequest {
    bookingCourtOccurrenceId: string;
}

export interface ApiFeedbacksListCustomerIdGetRequest {
    customerId: number;
}

export interface ApiFeedbacksListGetRequest {
    id?: number;
    customerId?: number;
    bookingCourtOccurrenceId?: string;
    rating?: number;
    status?: string;
    from?: Date;
    to?: Date;
}

export interface ApiFeedbacksUpdatePutRequest {
    updateFeedbackRequest?: UpdateFeedbackRequest;
}

/**
 * FeedbacksApi - interface
 * 
 * @export
 * @interface FeedbacksApiInterface
 */
export interface FeedbacksApiInterface {
    /**
     * 
     * @param {CreateFeedbackRequest} [createFeedbackRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FeedbacksApiInterface
     */
    apiFeedbacksCreatePostRaw(requestParameters: ApiFeedbacksCreatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DetailFeedbackResponseApiResponse>>;

    /**
     */
    apiFeedbacksCreatePost(requestParameters: ApiFeedbacksCreatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DetailFeedbackResponseApiResponse>;

    /**
     * 
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FeedbacksApiInterface
     */
    apiFeedbacksDeleteDeleteRaw(requestParameters: ApiFeedbacksDeleteDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BooleanApiResponse>>;

    /**
     */
    apiFeedbacksDeleteDelete(requestParameters: ApiFeedbacksDeleteDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BooleanApiResponse>;

    /**
     * 
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FeedbacksApiInterface
     */
    apiFeedbacksDetailGetRaw(requestParameters: ApiFeedbacksDetailGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DetailFeedbackResponseApiResponse>>;

    /**
     */
    apiFeedbacksDetailGet(requestParameters: ApiFeedbacksDetailGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DetailFeedbackResponseApiResponse>;

    /**
     * 
     * @param {string} bookingCourtOccurrenceId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FeedbacksApiInterface
     */
    apiFeedbacksListBookingCourtOccurrenceIdGetRaw(requestParameters: ApiFeedbacksListBookingCourtOccurrenceIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListFeedbackResponseListApiResponse>>;

    /**
     */
    apiFeedbacksListBookingCourtOccurrenceIdGet(requestParameters: ApiFeedbacksListBookingCourtOccurrenceIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListFeedbackResponseListApiResponse>;

    /**
     * 
     * @param {number} customerId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FeedbacksApiInterface
     */
    apiFeedbacksListCustomerIdGetRaw(requestParameters: ApiFeedbacksListCustomerIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListFeedbackResponseListApiResponse>>;

    /**
     */
    apiFeedbacksListCustomerIdGet(requestParameters: ApiFeedbacksListCustomerIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListFeedbackResponseListApiResponse>;

    /**
     * 
     * @param {number} [id] 
     * @param {number} [customerId] 
     * @param {string} [bookingCourtOccurrenceId] 
     * @param {number} [rating] 
     * @param {string} [status] 
     * @param {Date} [from] 
     * @param {Date} [to] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FeedbacksApiInterface
     */
    apiFeedbacksListGetRaw(requestParameters: ApiFeedbacksListGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListFeedbackResponseListApiResponse>>;

    /**
     */
    apiFeedbacksListGet(requestParameters: ApiFeedbacksListGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListFeedbackResponseListApiResponse>;

    /**
     * 
     * @param {UpdateFeedbackRequest} [updateFeedbackRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FeedbacksApiInterface
     */
    apiFeedbacksUpdatePutRaw(requestParameters: ApiFeedbacksUpdatePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DetailFeedbackResponseApiResponse>>;

    /**
     */
    apiFeedbacksUpdatePut(requestParameters: ApiFeedbacksUpdatePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DetailFeedbackResponseApiResponse>;

}

/**
 * 
 */
export class FeedbacksApi extends runtime.BaseAPI implements FeedbacksApiInterface {

    /**
     */
    async apiFeedbacksCreatePostRaw(requestParameters: ApiFeedbacksCreatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DetailFeedbackResponseApiResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/Feedbacks/create`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateFeedbackRequestToJSON(requestParameters['createFeedbackRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DetailFeedbackResponseApiResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiFeedbacksCreatePost(requestParameters: ApiFeedbacksCreatePostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DetailFeedbackResponseApiResponse> {
        const response = await this.apiFeedbacksCreatePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiFeedbacksDeleteDeleteRaw(requestParameters: ApiFeedbacksDeleteDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BooleanApiResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiFeedbacksDeleteDelete().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['id'] != null) {
            queryParameters['Id'] = requestParameters['id'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/Feedbacks/delete`;

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BooleanApiResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiFeedbacksDeleteDelete(requestParameters: ApiFeedbacksDeleteDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BooleanApiResponse> {
        const response = await this.apiFeedbacksDeleteDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiFeedbacksDetailGetRaw(requestParameters: ApiFeedbacksDetailGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DetailFeedbackResponseApiResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiFeedbacksDetailGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['id'] != null) {
            queryParameters['Id'] = requestParameters['id'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/Feedbacks/detail`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DetailFeedbackResponseApiResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiFeedbacksDetailGet(requestParameters: ApiFeedbacksDetailGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DetailFeedbackResponseApiResponse> {
        const response = await this.apiFeedbacksDetailGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiFeedbacksListBookingCourtOccurrenceIdGetRaw(requestParameters: ApiFeedbacksListBookingCourtOccurrenceIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListFeedbackResponseListApiResponse>> {
        if (requestParameters['bookingCourtOccurrenceId'] == null) {
            throw new runtime.RequiredError(
                'bookingCourtOccurrenceId',
                'Required parameter "bookingCourtOccurrenceId" was null or undefined when calling apiFeedbacksListBookingCourtOccurrenceIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/Feedbacks/list/{BookingCourtOccurrenceId}`;
        urlPath = urlPath.replace(`{${"BookingCourtOccurrenceId"}}`, encodeURIComponent(String(requestParameters['bookingCourtOccurrenceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListFeedbackResponseListApiResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiFeedbacksListBookingCourtOccurrenceIdGet(requestParameters: ApiFeedbacksListBookingCourtOccurrenceIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListFeedbackResponseListApiResponse> {
        const response = await this.apiFeedbacksListBookingCourtOccurrenceIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiFeedbacksListCustomerIdGetRaw(requestParameters: ApiFeedbacksListCustomerIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListFeedbackResponseListApiResponse>> {
        if (requestParameters['customerId'] == null) {
            throw new runtime.RequiredError(
                'customerId',
                'Required parameter "customerId" was null or undefined when calling apiFeedbacksListCustomerIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/Feedbacks/list/{CustomerId}`;
        urlPath = urlPath.replace(`{${"CustomerId"}}`, encodeURIComponent(String(requestParameters['customerId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListFeedbackResponseListApiResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiFeedbacksListCustomerIdGet(requestParameters: ApiFeedbacksListCustomerIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListFeedbackResponseListApiResponse> {
        const response = await this.apiFeedbacksListCustomerIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiFeedbacksListGetRaw(requestParameters: ApiFeedbacksListGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListFeedbackResponseListApiResponse>> {
        const queryParameters: any = {};

        if (requestParameters['id'] != null) {
            queryParameters['Id'] = requestParameters['id'];
        }

        if (requestParameters['customerId'] != null) {
            queryParameters['CustomerId'] = requestParameters['customerId'];
        }

        if (requestParameters['bookingCourtOccurrenceId'] != null) {
            queryParameters['BookingCourtOccurrenceId'] = requestParameters['bookingCourtOccurrenceId'];
        }

        if (requestParameters['rating'] != null) {
            queryParameters['Rating'] = requestParameters['rating'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['Status'] = requestParameters['status'];
        }

        if (requestParameters['from'] != null) {
            queryParameters['From'] = (requestParameters['from'] as any).toISOString();
        }

        if (requestParameters['to'] != null) {
            queryParameters['To'] = (requestParameters['to'] as any).toISOString();
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/Feedbacks/list`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListFeedbackResponseListApiResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiFeedbacksListGet(requestParameters: ApiFeedbacksListGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListFeedbackResponseListApiResponse> {
        const response = await this.apiFeedbacksListGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiFeedbacksUpdatePutRaw(requestParameters: ApiFeedbacksUpdatePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DetailFeedbackResponseApiResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/Feedbacks/update`;

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateFeedbackRequestToJSON(requestParameters['updateFeedbackRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DetailFeedbackResponseApiResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiFeedbacksUpdatePut(requestParameters: ApiFeedbacksUpdatePutRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DetailFeedbackResponseApiResponse> {
        const response = await this.apiFeedbacksUpdatePutRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
