/* tslint:disable */
/* eslint-disable */
/**
 * Badminton Court Management System API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ListByProductResponseListApiResponse,
} from '../models/index';
import {
    ListByProductResponseListApiResponseFromJSON,
    ListByProductResponseListApiResponseToJSON,
} from '../models/index';

export interface ApiInventoryCardsListByProductGetRequest {
    productId?: number;
}

/**
 * InventoryCardsApi - interface
 * 
 * @export
 * @interface InventoryCardsApiInterface
 */
export interface InventoryCardsApiInterface {
    /**
     * 
     * @param {number} [productId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InventoryCardsApiInterface
     */
    apiInventoryCardsListByProductGetRaw(requestParameters: ApiInventoryCardsListByProductGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListByProductResponseListApiResponse>>;

    /**
     */
    apiInventoryCardsListByProductGet(requestParameters: ApiInventoryCardsListByProductGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListByProductResponseListApiResponse>;

}

/**
 * 
 */
export class InventoryCardsApi extends runtime.BaseAPI implements InventoryCardsApiInterface {

    /**
     */
    async apiInventoryCardsListByProductGetRaw(requestParameters: ApiInventoryCardsListByProductGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListByProductResponseListApiResponse>> {
        const queryParameters: any = {};

        if (requestParameters['productId'] != null) {
            queryParameters['productId'] = requestParameters['productId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/InventoryCards/list-by-product`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListByProductResponseListApiResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiInventoryCardsListByProductGet(requestParameters: ApiInventoryCardsListByProductGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListByProductResponseListApiResponse> {
        const response = await this.apiInventoryCardsListByProductGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
