/* tslint:disable */
/* eslint-disable */
/**
 * Badminton Court Management System API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreatePayrollRequest,
} from '../models/index';
import {
    CreatePayrollRequestFromJSON,
    CreatePayrollRequestToJSON,
} from '../models/index';

export interface ApiPayrollGetRequest {
    keyword?: string;
    status?: string;
    startDateOperator?: string;
    startDate?: Date;
    endDateOperator?: string;
    endDate?: Date;
}

export interface ApiPayrollItemsByStaffStaffIdGetRequest {
    staffId: number;
}

export interface ApiPayrollPayItemPayrollItemIdPostRequest {
    payrollItemId: number;
    amount?: number;
}

export interface ApiPayrollPayrollIdDeleteRequest {
    payrollId: number;
}

export interface ApiPayrollPayrollIdGetRequest {
    payrollId: number;
}

export interface ApiPayrollPostRequest {
    createPayrollRequest?: CreatePayrollRequest;
}

export interface ApiPayrollRefreshPayrollIdPostRequest {
    payrollId: number;
}

/**
 * PayrollApi - interface
 * 
 * @export
 * @interface PayrollApiInterface
 */
export interface PayrollApiInterface {
    /**
     * 
     * @param {string} [keyword] 
     * @param {string} [status] 
     * @param {string} [startDateOperator] 
     * @param {Date} [startDate] 
     * @param {string} [endDateOperator] 
     * @param {Date} [endDate] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PayrollApiInterface
     */
    apiPayrollGetRaw(requestParameters: ApiPayrollGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     */
    apiPayrollGet(requestParameters: ApiPayrollGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @param {number} staffId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PayrollApiInterface
     */
    apiPayrollItemsByStaffStaffIdGetRaw(requestParameters: ApiPayrollItemsByStaffStaffIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     */
    apiPayrollItemsByStaffStaffIdGet(requestParameters: ApiPayrollItemsByStaffStaffIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @param {number} payrollItemId 
     * @param {number} [amount] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PayrollApiInterface
     */
    apiPayrollPayItemPayrollItemIdPostRaw(requestParameters: ApiPayrollPayItemPayrollItemIdPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     */
    apiPayrollPayItemPayrollItemIdPost(requestParameters: ApiPayrollPayItemPayrollItemIdPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @param {number} payrollId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PayrollApiInterface
     */
    apiPayrollPayrollIdDeleteRaw(requestParameters: ApiPayrollPayrollIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     */
    apiPayrollPayrollIdDelete(requestParameters: ApiPayrollPayrollIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @param {number} payrollId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PayrollApiInterface
     */
    apiPayrollPayrollIdGetRaw(requestParameters: ApiPayrollPayrollIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     */
    apiPayrollPayrollIdGet(requestParameters: ApiPayrollPayrollIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @param {CreatePayrollRequest} [createPayrollRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PayrollApiInterface
     */
    apiPayrollPostRaw(requestParameters: ApiPayrollPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     */
    apiPayrollPost(requestParameters: ApiPayrollPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @param {number} payrollId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PayrollApiInterface
     */
    apiPayrollRefreshPayrollIdPostRaw(requestParameters: ApiPayrollRefreshPayrollIdPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     */
    apiPayrollRefreshPayrollIdPost(requestParameters: ApiPayrollRefreshPayrollIdPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

}

/**
 * 
 */
export class PayrollApi extends runtime.BaseAPI implements PayrollApiInterface {

    /**
     */
    async apiPayrollGetRaw(requestParameters: ApiPayrollGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        if (requestParameters['keyword'] != null) {
            queryParameters['Keyword'] = requestParameters['keyword'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['Status'] = requestParameters['status'];
        }

        if (requestParameters['startDateOperator'] != null) {
            queryParameters['StartDateOperator'] = requestParameters['startDateOperator'];
        }

        if (requestParameters['startDate'] != null) {
            queryParameters['StartDate'] = (requestParameters['startDate'] as any).toISOString();
        }

        if (requestParameters['endDateOperator'] != null) {
            queryParameters['EndDateOperator'] = requestParameters['endDateOperator'];
        }

        if (requestParameters['endDate'] != null) {
            queryParameters['EndDate'] = (requestParameters['endDate'] as any).toISOString();
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // Bearer authentication
        }


        let urlPath = `/api/Payroll`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiPayrollGet(requestParameters: ApiPayrollGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiPayrollGetRaw(requestParameters, initOverrides);
    }

    /**
     */
    async apiPayrollItemsByStaffStaffIdGetRaw(requestParameters: ApiPayrollItemsByStaffStaffIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['staffId'] == null) {
            throw new runtime.RequiredError(
                'staffId',
                'Required parameter "staffId" was null or undefined when calling apiPayrollItemsByStaffStaffIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // Bearer authentication
        }


        let urlPath = `/api/Payroll/items/by-staff/{staffId}`;
        urlPath = urlPath.replace(`{${"staffId"}}`, encodeURIComponent(String(requestParameters['staffId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiPayrollItemsByStaffStaffIdGet(requestParameters: ApiPayrollItemsByStaffStaffIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiPayrollItemsByStaffStaffIdGetRaw(requestParameters, initOverrides);
    }

    /**
     */
    async apiPayrollPayItemPayrollItemIdPostRaw(requestParameters: ApiPayrollPayItemPayrollItemIdPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['payrollItemId'] == null) {
            throw new runtime.RequiredError(
                'payrollItemId',
                'Required parameter "payrollItemId" was null or undefined when calling apiPayrollPayItemPayrollItemIdPost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['amount'] != null) {
            queryParameters['amount'] = requestParameters['amount'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // Bearer authentication
        }


        let urlPath = `/api/Payroll/pay-item/{payrollItemId}`;
        urlPath = urlPath.replace(`{${"payrollItemId"}}`, encodeURIComponent(String(requestParameters['payrollItemId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiPayrollPayItemPayrollItemIdPost(requestParameters: ApiPayrollPayItemPayrollItemIdPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiPayrollPayItemPayrollItemIdPostRaw(requestParameters, initOverrides);
    }

    /**
     */
    async apiPayrollPayrollIdDeleteRaw(requestParameters: ApiPayrollPayrollIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['payrollId'] == null) {
            throw new runtime.RequiredError(
                'payrollId',
                'Required parameter "payrollId" was null or undefined when calling apiPayrollPayrollIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // Bearer authentication
        }


        let urlPath = `/api/Payroll/{payrollId}`;
        urlPath = urlPath.replace(`{${"payrollId"}}`, encodeURIComponent(String(requestParameters['payrollId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiPayrollPayrollIdDelete(requestParameters: ApiPayrollPayrollIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiPayrollPayrollIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     */
    async apiPayrollPayrollIdGetRaw(requestParameters: ApiPayrollPayrollIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['payrollId'] == null) {
            throw new runtime.RequiredError(
                'payrollId',
                'Required parameter "payrollId" was null or undefined when calling apiPayrollPayrollIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // Bearer authentication
        }


        let urlPath = `/api/Payroll/{payrollId}`;
        urlPath = urlPath.replace(`{${"payrollId"}}`, encodeURIComponent(String(requestParameters['payrollId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiPayrollPayrollIdGet(requestParameters: ApiPayrollPayrollIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiPayrollPayrollIdGetRaw(requestParameters, initOverrides);
    }

    /**
     */
    async apiPayrollPostRaw(requestParameters: ApiPayrollPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // Bearer authentication
        }


        let urlPath = `/api/Payroll`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreatePayrollRequestToJSON(requestParameters['createPayrollRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiPayrollPost(requestParameters: ApiPayrollPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiPayrollPostRaw(requestParameters, initOverrides);
    }

    /**
     */
    async apiPayrollRefreshPayrollIdPostRaw(requestParameters: ApiPayrollRefreshPayrollIdPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['payrollId'] == null) {
            throw new runtime.RequiredError(
                'payrollId',
                'Required parameter "payrollId" was null or undefined when calling apiPayrollRefreshPayrollIdPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // Bearer authentication
        }


        let urlPath = `/api/Payroll/refresh/{payrollId}`;
        urlPath = urlPath.replace(`{${"payrollId"}}`, encodeURIComponent(String(requestParameters['payrollId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiPayrollRefreshPayrollIdPost(requestParameters: ApiPayrollRefreshPayrollIdPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiPayrollRefreshPayrollIdPostRaw(requestParameters, initOverrides);
    }

}
