/* tslint:disable */
/* eslint-disable */
/**
 * Badminton Court Management System API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateRoleRequest,
  DetailRoleResponseApiResponse,
  ListRoleResponseListApiResponse,
  ObjectApiResponse,
  UpdateRoleRequest,
} from '../models/index';
import {
    CreateRoleRequestFromJSON,
    CreateRoleRequestToJSON,
    DetailRoleResponseApiResponseFromJSON,
    DetailRoleResponseApiResponseToJSON,
    ListRoleResponseListApiResponseFromJSON,
    ListRoleResponseListApiResponseToJSON,
    ObjectApiResponseFromJSON,
    ObjectApiResponseToJSON,
    UpdateRoleRequestFromJSON,
    UpdateRoleRequestToJSON,
} from '../models/index';

export interface ApiRolesCreatePostRequest {
    createRoleRequest?: CreateRoleRequest;
}

export interface ApiRolesDeleteDeleteRequest {
    roleId: string;
}

export interface ApiRolesDetailGetRequest {
    roleId: string;
}

export interface ApiRolesListGetRequest {
    roleName?: string;
}

export interface ApiRolesUpdatePutRequest {
    updateRoleRequest?: UpdateRoleRequest;
}

/**
 * RolesApi - interface
 * 
 * @export
 * @interface RolesApiInterface
 */
export interface RolesApiInterface {
    /**
     * 
     * @param {CreateRoleRequest} [createRoleRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RolesApiInterface
     */
    apiRolesCreatePostRaw(requestParameters: ApiRolesCreatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ObjectApiResponse>>;

    /**
     */
    apiRolesCreatePost(requestParameters: ApiRolesCreatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ObjectApiResponse>;

    /**
     * 
     * @param {string} roleId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RolesApiInterface
     */
    apiRolesDeleteDeleteRaw(requestParameters: ApiRolesDeleteDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ObjectApiResponse>>;

    /**
     */
    apiRolesDeleteDelete(requestParameters: ApiRolesDeleteDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ObjectApiResponse>;

    /**
     * 
     * @param {string} roleId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RolesApiInterface
     */
    apiRolesDetailGetRaw(requestParameters: ApiRolesDetailGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DetailRoleResponseApiResponse>>;

    /**
     */
    apiRolesDetailGet(requestParameters: ApiRolesDetailGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DetailRoleResponseApiResponse>;

    /**
     * 
     * @param {string} [roleName] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RolesApiInterface
     */
    apiRolesListGetRaw(requestParameters: ApiRolesListGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListRoleResponseListApiResponse>>;

    /**
     */
    apiRolesListGet(requestParameters: ApiRolesListGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListRoleResponseListApiResponse>;

    /**
     * 
     * @param {UpdateRoleRequest} [updateRoleRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RolesApiInterface
     */
    apiRolesUpdatePutRaw(requestParameters: ApiRolesUpdatePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ObjectApiResponse>>;

    /**
     */
    apiRolesUpdatePut(requestParameters: ApiRolesUpdatePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ObjectApiResponse>;

}

/**
 * 
 */
export class RolesApi extends runtime.BaseAPI implements RolesApiInterface {

    /**
     */
    async apiRolesCreatePostRaw(requestParameters: ApiRolesCreatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ObjectApiResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/Roles/create`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateRoleRequestToJSON(requestParameters['createRoleRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ObjectApiResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiRolesCreatePost(requestParameters: ApiRolesCreatePostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ObjectApiResponse> {
        const response = await this.apiRolesCreatePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiRolesDeleteDeleteRaw(requestParameters: ApiRolesDeleteDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ObjectApiResponse>> {
        if (requestParameters['roleId'] == null) {
            throw new runtime.RequiredError(
                'roleId',
                'Required parameter "roleId" was null or undefined when calling apiRolesDeleteDelete().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['roleId'] != null) {
            queryParameters['RoleId'] = requestParameters['roleId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/Roles/delete`;

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ObjectApiResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiRolesDeleteDelete(requestParameters: ApiRolesDeleteDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ObjectApiResponse> {
        const response = await this.apiRolesDeleteDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiRolesDetailGetRaw(requestParameters: ApiRolesDetailGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DetailRoleResponseApiResponse>> {
        if (requestParameters['roleId'] == null) {
            throw new runtime.RequiredError(
                'roleId',
                'Required parameter "roleId" was null or undefined when calling apiRolesDetailGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['roleId'] != null) {
            queryParameters['RoleId'] = requestParameters['roleId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/Roles/detail`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DetailRoleResponseApiResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiRolesDetailGet(requestParameters: ApiRolesDetailGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DetailRoleResponseApiResponse> {
        const response = await this.apiRolesDetailGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiRolesListGetRaw(requestParameters: ApiRolesListGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListRoleResponseListApiResponse>> {
        const queryParameters: any = {};

        if (requestParameters['roleName'] != null) {
            queryParameters['RoleName'] = requestParameters['roleName'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/Roles/list`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListRoleResponseListApiResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiRolesListGet(requestParameters: ApiRolesListGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListRoleResponseListApiResponse> {
        const response = await this.apiRolesListGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiRolesUpdatePutRaw(requestParameters: ApiRolesUpdatePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ObjectApiResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/Roles/update`;

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateRoleRequestToJSON(requestParameters['updateRoleRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ObjectApiResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiRolesUpdatePut(requestParameters: ApiRolesUpdatePutRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ObjectApiResponse> {
        const response = await this.apiRolesUpdatePutRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
