/* tslint:disable */
/* eslint-disable */
/**
 * Badminton Court Management System API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BooleanApiResponse,
  ObjectApiResponse,
  ScheduleByShiftResponseListApiResponse,
  ScheduleByStaffResponseListApiResponse,
  ScheduleRequest,
} from '../models/index';
import {
    BooleanApiResponseFromJSON,
    BooleanApiResponseToJSON,
    ObjectApiResponseFromJSON,
    ObjectApiResponseToJSON,
    ScheduleByShiftResponseListApiResponseFromJSON,
    ScheduleByShiftResponseListApiResponseToJSON,
    ScheduleByStaffResponseListApiResponseFromJSON,
    ScheduleByStaffResponseListApiResponseToJSON,
    ScheduleRequestFromJSON,
    ScheduleRequestToJSON,
} from '../models/index';

export interface ApiScheduleAssignPostRequest {
    scheduleRequest?: ScheduleRequest;
}

export interface ApiScheduleByShiftGetRequest {
    startDate?: Date;
    endDate?: Date;
}

export interface ApiScheduleByStaffGetRequest {
    startDate?: Date;
    endDate?: Date;
}

export interface ApiScheduleRemoveDeleteRequest {
    scheduleRequest?: ScheduleRequest;
}

/**
 * ScheduleApi - interface
 * 
 * @export
 * @interface ScheduleApiInterface
 */
export interface ScheduleApiInterface {
    /**
     * 
     * @param {ScheduleRequest} [scheduleRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ScheduleApiInterface
     */
    apiScheduleAssignPostRaw(requestParameters: ApiScheduleAssignPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BooleanApiResponse>>;

    /**
     */
    apiScheduleAssignPost(requestParameters: ApiScheduleAssignPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BooleanApiResponse>;

    /**
     * 
     * @param {Date} [startDate] 
     * @param {Date} [endDate] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ScheduleApiInterface
     */
    apiScheduleByShiftGetRaw(requestParameters: ApiScheduleByShiftGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ScheduleByShiftResponseListApiResponse>>;

    /**
     */
    apiScheduleByShiftGet(requestParameters: ApiScheduleByShiftGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ScheduleByShiftResponseListApiResponse>;

    /**
     * 
     * @param {Date} [startDate] 
     * @param {Date} [endDate] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ScheduleApiInterface
     */
    apiScheduleByStaffGetRaw(requestParameters: ApiScheduleByStaffGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ScheduleByStaffResponseListApiResponse>>;

    /**
     */
    apiScheduleByStaffGet(requestParameters: ApiScheduleByStaffGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ScheduleByStaffResponseListApiResponse>;

    /**
     * 
     * @param {ScheduleRequest} [scheduleRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ScheduleApiInterface
     */
    apiScheduleRemoveDeleteRaw(requestParameters: ApiScheduleRemoveDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ObjectApiResponse>>;

    /**
     */
    apiScheduleRemoveDelete(requestParameters: ApiScheduleRemoveDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ObjectApiResponse>;

}

/**
 * 
 */
export class ScheduleApi extends runtime.BaseAPI implements ScheduleApiInterface {

    /**
     */
    async apiScheduleAssignPostRaw(requestParameters: ApiScheduleAssignPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BooleanApiResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/Schedule/assign`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ScheduleRequestToJSON(requestParameters['scheduleRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BooleanApiResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiScheduleAssignPost(requestParameters: ApiScheduleAssignPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BooleanApiResponse> {
        const response = await this.apiScheduleAssignPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiScheduleByShiftGetRaw(requestParameters: ApiScheduleByShiftGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ScheduleByShiftResponseListApiResponse>> {
        const queryParameters: any = {};

        if (requestParameters['startDate'] != null) {
            queryParameters['startDate'] = (requestParameters['startDate'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['endDate'] != null) {
            queryParameters['endDate'] = (requestParameters['endDate'] as any).toISOString().substring(0,10);
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/Schedule/by-shift`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ScheduleByShiftResponseListApiResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiScheduleByShiftGet(requestParameters: ApiScheduleByShiftGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ScheduleByShiftResponseListApiResponse> {
        const response = await this.apiScheduleByShiftGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiScheduleByStaffGetRaw(requestParameters: ApiScheduleByStaffGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ScheduleByStaffResponseListApiResponse>> {
        const queryParameters: any = {};

        if (requestParameters['startDate'] != null) {
            queryParameters['startDate'] = (requestParameters['startDate'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['endDate'] != null) {
            queryParameters['endDate'] = (requestParameters['endDate'] as any).toISOString().substring(0,10);
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/Schedule/by-staff`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ScheduleByStaffResponseListApiResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiScheduleByStaffGet(requestParameters: ApiScheduleByStaffGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ScheduleByStaffResponseListApiResponse> {
        const response = await this.apiScheduleByStaffGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiScheduleRemoveDeleteRaw(requestParameters: ApiScheduleRemoveDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ObjectApiResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/Schedule/remove`;

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
            body: ScheduleRequestToJSON(requestParameters['scheduleRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ObjectApiResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiScheduleRemoveDelete(requestParameters: ApiScheduleRemoveDeleteRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ObjectApiResponse> {
        const response = await this.apiScheduleRemoveDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
