/* tslint:disable */
/* eslint-disable */
/**
 * Badminton Court Management System API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateStoreBankAccountRequest,
  StoreBankAccountResponse,
} from '../models/index';
import {
    CreateStoreBankAccountRequestFromJSON,
    CreateStoreBankAccountRequestToJSON,
    StoreBankAccountResponseFromJSON,
    StoreBankAccountResponseToJSON,
} from '../models/index';

export interface ApiStoreBankAccountsPostRequest {
    createStoreBankAccountRequest?: CreateStoreBankAccountRequest;
}

/**
 * StoreBankAccountsApi - interface
 * 
 * @export
 * @interface StoreBankAccountsApiInterface
 */
export interface StoreBankAccountsApiInterface {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof StoreBankAccountsApiInterface
     */
    apiStoreBankAccountsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<StoreBankAccountResponse>>>;

    /**
     */
    apiStoreBankAccountsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<StoreBankAccountResponse>>;

    /**
     * 
     * @param {CreateStoreBankAccountRequest} [createStoreBankAccountRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof StoreBankAccountsApiInterface
     */
    apiStoreBankAccountsPostRaw(requestParameters: ApiStoreBankAccountsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StoreBankAccountResponse>>;

    /**
     */
    apiStoreBankAccountsPost(requestParameters: ApiStoreBankAccountsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StoreBankAccountResponse>;

}

/**
 * 
 */
export class StoreBankAccountsApi extends runtime.BaseAPI implements StoreBankAccountsApiInterface {

    /**
     */
    async apiStoreBankAccountsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<StoreBankAccountResponse>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/store-bank-accounts`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(StoreBankAccountResponseFromJSON));
    }

    /**
     */
    async apiStoreBankAccountsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<StoreBankAccountResponse>> {
        const response = await this.apiStoreBankAccountsGetRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async apiStoreBankAccountsPostRaw(requestParameters: ApiStoreBankAccountsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StoreBankAccountResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/store-bank-accounts`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateStoreBankAccountRequestToJSON(requestParameters['createStoreBankAccountRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StoreBankAccountResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiStoreBankAccountsPost(requestParameters: ApiStoreBankAccountsPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StoreBankAccountResponse> {
        const response = await this.apiStoreBankAccountsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
