/* tslint:disable */
/* eslint-disable */
/**
 * Badminton Court Management System API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BooleanApiResponse,
  SystemConfigRequest,
  SystemConfigResponseApiResponse,
  SystemConfigResponseListApiResponse,
} from '../models/index';
import {
    BooleanApiResponseFromJSON,
    BooleanApiResponseToJSON,
    SystemConfigRequestFromJSON,
    SystemConfigRequestToJSON,
    SystemConfigResponseApiResponseFromJSON,
    SystemConfigResponseApiResponseToJSON,
    SystemConfigResponseListApiResponseFromJSON,
    SystemConfigResponseListApiResponseToJSON,
} from '../models/index';

export interface ApiSystemConfigGroupGroupGetRequest {
    group: string;
}

export interface ApiSystemConfigKeyGetRequest {
    key: string;
}

export interface ApiSystemConfigKeyPutRequest {
    key: string;
    systemConfigRequest?: SystemConfigRequest;
}

/**
 * SystemConfigApi - interface
 * 
 * @export
 * @interface SystemConfigApiInterface
 */
export interface SystemConfigApiInterface {
    /**
     * 
     * @param {string} group 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SystemConfigApiInterface
     */
    apiSystemConfigGroupGroupGetRaw(requestParameters: ApiSystemConfigGroupGroupGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SystemConfigResponseListApiResponse>>;

    /**
     */
    apiSystemConfigGroupGroupGet(requestParameters: ApiSystemConfigGroupGroupGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SystemConfigResponseListApiResponse>;

    /**
     * 
     * @param {string} key 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SystemConfigApiInterface
     */
    apiSystemConfigKeyGetRaw(requestParameters: ApiSystemConfigKeyGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SystemConfigResponseApiResponse>>;

    /**
     */
    apiSystemConfigKeyGet(requestParameters: ApiSystemConfigKeyGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SystemConfigResponseApiResponse>;

    /**
     * 
     * @param {string} key 
     * @param {SystemConfigRequest} [systemConfigRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SystemConfigApiInterface
     */
    apiSystemConfigKeyPutRaw(requestParameters: ApiSystemConfigKeyPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BooleanApiResponse>>;

    /**
     */
    apiSystemConfigKeyPut(requestParameters: ApiSystemConfigKeyPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BooleanApiResponse>;

}

/**
 * 
 */
export class SystemConfigApi extends runtime.BaseAPI implements SystemConfigApiInterface {

    /**
     */
    async apiSystemConfigGroupGroupGetRaw(requestParameters: ApiSystemConfigGroupGroupGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SystemConfigResponseListApiResponse>> {
        if (requestParameters['group'] == null) {
            throw new runtime.RequiredError(
                'group',
                'Required parameter "group" was null or undefined when calling apiSystemConfigGroupGroupGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // Bearer authentication
        }


        let urlPath = `/api/SystemConfig/group/{group}`;
        urlPath = urlPath.replace(`{${"group"}}`, encodeURIComponent(String(requestParameters['group'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SystemConfigResponseListApiResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiSystemConfigGroupGroupGet(requestParameters: ApiSystemConfigGroupGroupGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SystemConfigResponseListApiResponse> {
        const response = await this.apiSystemConfigGroupGroupGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiSystemConfigKeyGetRaw(requestParameters: ApiSystemConfigKeyGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SystemConfigResponseApiResponse>> {
        if (requestParameters['key'] == null) {
            throw new runtime.RequiredError(
                'key',
                'Required parameter "key" was null or undefined when calling apiSystemConfigKeyGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // Bearer authentication
        }


        let urlPath = `/api/SystemConfig/{key}`;
        urlPath = urlPath.replace(`{${"key"}}`, encodeURIComponent(String(requestParameters['key'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SystemConfigResponseApiResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiSystemConfigKeyGet(requestParameters: ApiSystemConfigKeyGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SystemConfigResponseApiResponse> {
        const response = await this.apiSystemConfigKeyGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiSystemConfigKeyPutRaw(requestParameters: ApiSystemConfigKeyPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BooleanApiResponse>> {
        if (requestParameters['key'] == null) {
            throw new runtime.RequiredError(
                'key',
                'Required parameter "key" was null or undefined when calling apiSystemConfigKeyPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // Bearer authentication
        }


        let urlPath = `/api/SystemConfig/{key}`;
        urlPath = urlPath.replace(`{${"key"}}`, encodeURIComponent(String(requestParameters['key'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: SystemConfigRequestToJSON(requestParameters['systemConfigRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BooleanApiResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiSystemConfigKeyPut(requestParameters: ApiSystemConfigKeyPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BooleanApiResponse> {
        const response = await this.apiSystemConfigKeyPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
